// ----------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
// EDIT THE CORRESPONDENT .ts FILE INSTEAD

//  ---------------------------------------------------------------------------
import Exchange from './abstract/asretether.js';
//  ---------------------------------------------------------------------------
/**
 * @class asretether
 * @augments Exchange
 * @description Set rateLimit to 1000 if fully verified
 */
export default class asretether extends Exchange {
    describe() {
        return this.deepExtend(super.describe(), {
            'id': 'asretether',
            'name': 'Asretether',
            'countries': ['IR'],
            'rateLimit': 1000,
            'version': '2',
            'certified': false,
            'pro': false,
            'has': {
                'CORS': undefined,
                'spot': true,
                'margin': false,
                'swap': false,
                'future': false,
                'option': false,
                'addMargin': false,
                'cancelAllOrders': false,
                'cancelOrder': false,
                'cancelOrders': false,
                'createDepositAddress': false,
                'createOrder': false,
                'createStopLimitOrder': false,
                'createStopMarketOrder': false,
                'createStopOrder': false,
                'editOrder': false,
                'fetchBalance': false,
                'fetchBorrowInterest': false,
                'fetchBorrowRateHistories': false,
                'fetchBorrowRateHistory': false,
                'fetchClosedOrders': false,
                'fetchCrossBorrowRate': false,
                'fetchCrossBorrowRates': false,
                'fetchCurrencies': false,
                'fetchDepositAddress': false,
                'fetchDeposits': false,
                'fetchFundingHistory': false,
                'fetchFundingRate': false,
                'fetchFundingRateHistory': false,
                'fetchFundingRates': false,
                'fetchIndexOHLCV': false,
                'fetchIsolatedBorrowRate': false,
                'fetchIsolatedBorrowRates': false,
                'fetchL2OrderBook': false,
                'fetchL3OrderBook': false,
                'fetchLedger': false,
                'fetchLedgerEntry': false,
                'fetchLeverageTiers': false,
                'fetchMarkets': true,
                'fetchMarkOHLCV': false,
                'fetchMyTrades': false,
                'fetchOHLCV': false,
                'fetchOpenInterestHistory': false,
                'fetchOpenOrders': false,
                'fetchOrder': false,
                'fetchOrderBook': false,
                'fetchOrders': false,
                'fetchOrderTrades': false,
                'fetchPositions': false,
                'fetchPremiumIndexOHLCV': false,
                'fetchTicker': true,
                'fetchTickers': true,
                'fetchTime': false,
                'fetchTrades': false,
                'fetchTradingFee': false,
                'fetchTradingFees': false,
                'fetchWithdrawals': false,
                'otc': true,
                'setLeverage': false,
                'setMarginMode': false,
                'transfer': false,
                'withdraw': false,
            },
            'comment': 'OTC market for USDT and other cryptocurrencies',
            'urls': {
                'logo': 'https://cdn.arz.digital/cr-odin/img/exchanges/asretether/64x64.png',
                'api': {
                    'public': 'https://api.asretether.com',
                },
                'www': 'https://asretether.com',
                'doc': [
                    'https://api.asretether.com/docs',
                ],
            },
            'api': {
                'public': {
                    'get': {
                        'v2/market': 1,
                    },
                },
            },
            'fees': {
                'trading': {
                    'tierBased': false,
                    'percentage': true,
                    'maker': this.parseNumber('0'),
                    'taker': this.parseNumber('0'),
                },
            },
        });
    }
    async fetchMarkets(params = {}) {
        /**
         * @method
         * @name asretether#fetchMarkets
         * @description retrieves data on all markets for asretether
         * @param {object} [params] extra parameters specific to the exchange API endpoint
         * @returns {object[]} an array of objects representing market data
         */
        const response = await this.publicGetV2Market(params);
        const data = this.safeList(response, 'data', []);
        const result = [];
        for (let i = 0; i < data.length; i++) {
            const market = this.parseMarket(data[i]);
            result.push(market);
        }
        return result;
    }
    parseMarket(market) {
        //         {
        // id: 2,
        // symbol: "USDT-IRT",
        // status: "ACTIVE",
        // high_24h: "181978",
        // low_24h: "172874",
        // irt_high_24h: 0,
        // irt_low_24h: 0,
        // change_24h: 0,
        // volume_24h: 100000,
        // price: {
        // price_buy: "178410",
        // price_sell: "176402",
        // price_in_tether: "1.0000"
        // },
        // base_currency: {
        // slug: "USDT",
        // decimals: 6,
        // full_name: "Tether",
        // persian_name: "تتر",
        // icon_url: "https://box.asretether.com/currency-icons/usdt.png"
        // },
        // quote_currency: {
        // slug: "IRT",
        // decimals: 0,
        // full_name: "IR Toman",
        // persian_name: "تومان",
        // icon_url: "https://box.asretether.com/currency-icons/irt.png"
        // }
        // },
        const id = this.safeString(market, 'symbol');
        const baseCurrency = this.safeDict(market, 'base_currency', {});
        const quoteCurrency = this.safeDict(market, 'quote_currency', {});
        const baseId = this.safeString(baseCurrency, 'slug');
        const quoteId = this.safeString(quoteCurrency, 'slug');
        const base = this.safeCurrencyCode(baseId);
        const quote = this.safeCurrencyCode(quoteId);
        const basePrecision = this.safeInteger(baseCurrency, 'decimals');
        const quotePrecision = this.safeInteger(quoteCurrency, 'decimals');
        const status = this.safeString(market, 'status');
        const enabled = status === 'ACTIVE';
        return {
            'id': id,
            'symbol': base + '/' + quote,
            'base': base,
            'quote': quote,
            'settle': undefined,
            'baseId': baseId,
            'quoteId': quoteId,
            'settleId': undefined,
            'type': 'otc',
            'spot': false,
            'margin': false,
            'swap': false,
            'future': false,
            'option': false,
            'active': enabled,
            'contract': false,
            'linear': undefined,
            'inverse': undefined,
            'contractSize': undefined,
            'expiry': undefined,
            'expiryDatetime': undefined,
            'strike': undefined,
            'optionType': undefined,
            'precision': {
                'amount': basePrecision,
                'price': quotePrecision,
            },
            'limits': {
                'leverage': {
                    'min': undefined,
                    'max': undefined,
                },
                'amount': {
                    'min': undefined,
                    'max': undefined,
                },
                'price': {
                    'min': undefined,
                    'max': undefined,
                },
                'cost': {
                    'min': undefined,
                    'max': undefined,
                },
            },
            'created': undefined,
            'info': market,
        };
    }
    async fetchTickers(symbols = undefined, params = {}) {
        /**
         * @method
         * @name asretether#fetchTickers
         * @description fetches price tickers for multiple markets, statistical information calculated over the past 24 hours for each market
         * @param {string[]|undefined} symbols unified symbols of the markets to fetch the ticker for, all market tickers are returned if not assigned
         * @param {object} [params] extra parameters specific to the exchange API endpoint
         * @returns {object} a dictionary of [ticker structures]{@link https://docs.ccxt.com/#/?id=ticker-structure}
         */
        await this.loadMarkets();
        if (symbols !== undefined) {
            symbols = this.marketSymbols(symbols);
        }
        const response = await this.publicGetV2Market(params);
        const data = this.safeList(response, 'data', []);
        const result = {};
        for (let i = 0; i < data.length; i++) {
            const ticker = this.parseTicker(data[i]);
            const symbol = ticker['symbol'];
            result[symbol] = ticker;
        }
        return this.filterByArrayTickers(result, 'symbol', symbols);
    }
    async fetchTicker(symbol, params = {}) {
        /**
         * @method
         * @name asretether#fetchTicker
         * @description fetches a price ticker, a statistical calculation with the information calculated over the past 24 hours for a specific market
         * @param {string} symbol unified symbol of the market to fetch the ticker for
         * @param {object} [params] extra parameters specific to the exchange API endpoint
         * @returns {object} a [ticker structure]{@link https://docs.ccxt.com/#/?id=ticker-structure}
         */
        await this.loadMarkets();
        const market = this.market(symbol);
        const request = {
            'symbol': market['id'],
        };
        const response = await this.publicGetV2Market(request);
        const data = this.safeList(response, 'data', []);
        if (data.length > 0) {
            return this.parseTicker(data[0], market);
        }
        throw new Error('Ticker not found');
    }
    parseTicker(ticker, market = undefined) {
        const baseCurrency = this.safeDict(ticker, 'base_currency', {});
        const quoteCurrency = this.safeDict(ticker, 'quote_currency', {});
        const baseId = this.safeString(baseCurrency, 'slug');
        const quoteId = this.safeString(quoteCurrency, 'slug');
        const base = this.safeCurrencyCode(baseId);
        const quote = this.safeCurrencyCode(quoteId);
        const symbol = base + '/' + quote;
        // Handle price selection based on quote currency
        const price = this.safeDict(ticker, 'price', {});
        let last = undefined;
        if (quote === 'IRT') {
            last = this.safeFloat(price, 'price_sell');
        }
        else if (quote === 'USDT') {
            last = this.safeFloat(price, 'price_in_tether');
        }
        const high = this.safeFloat(ticker, 'high_24h');
        const low = this.safeFloat(ticker, 'low_24h');
        const baseVolume = this.safeFloat(ticker, 'volume_24h');
        return this.safeTicker({
            'symbol': symbol,
            'timestamp': undefined,
            'datetime': undefined,
            'high': high,
            'low': low,
            'bid': undefined,
            'bidVolume': undefined,
            'ask': undefined,
            'askVolume': undefined,
            'vwap': undefined,
            'open': undefined,
            'close': last,
            'last': last,
            'previousClose': undefined,
            'change': this.safeFloat(ticker, 'change_24h'),
            'percentage': undefined,
            'average': undefined,
            'baseVolume': baseVolume,
            'quoteVolume': undefined,
            'info': ticker,
        }, market);
    }
    sign(path, api = 'public', method = 'GET', params = {}, headers = undefined, body = undefined) {
        let url = this.urls['api']['public'] + '/' + path;
        const query = this.omit(params, this.extractParams(path));
        query['limit'] = this.safeString(query, 'limit', '1000');
        // Add query parameters if any remain
        if (Object.keys(query).length) {
            url = url + '?' + this.urlencode(query);
        }
        headers = { 'Content-Type': 'application/json' };
        return { 'url': url, 'method': method, 'body': body, 'headers': headers };
    }
}
