// ----------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
// EDIT THE CORRESPONDENT .ts FILE INSTEAD

//  ---------------------------------------------------------------------------
import Exchange from './base/Exchange.js';
import { ExchangeError } from './base/errors.js';
//  ---------------------------------------------------------------------------
/**
 * @class digikalagold
 * @augments Exchange
 */
export default class digikalagold extends Exchange {
    describe() {
        return this.deepExtend(super.describe(), {
            'id': 'digikalagold',
            'name': 'Digikala Gold',
            'countries': ['IR'],
            'rateLimit': 1000,
            'version': 'v1',
            'certified': false,
            'pro': false,
            'has': {
                'CORS': undefined,
                'spot': false,
                'margin': false,
                'swap': false,
                'future': false,
                'option': false,
                'fetchMarkets': true,
                'fetchTicker': true,
                'fetchTickers': true,
                'otc': true,
            },
            'options': {
                'defaultType': 'otc',
            },
            'urls': {
                'api': {
                    'public': 'https://api.digikala.com',
                },
                'www': 'https://www.digikala.com',
                'doc': 'https://api.digikala.com/non-inventory/v1/prices/',
            },
            'api': {
                'public': {
                    'get': {
                        'non-inventory/v1/prices/': 1,
                    },
                },
            },
        });
    }
    async fetchMarkets(params = {}) {
        const response = await this.fetchPrice(params);
        return [
            this.parseMarketEntry(response, 'gold18'),
            this.parseMarketEntry(response, 'silver999'),
        ];
    }
    async fetchPrice(params = {}) {
        const response = await this.publicGetNonInventoryV1Prices(params);
        const gold = this.safeDict(response, 'gold18', {});
        if (this.safeNumber(gold, 'price') !== undefined) {
            return response;
        }
        throw new ExchangeError(this.id + ' returned an invalid response');
    }
    parseMarketEntry(response, id) {
        const isGold = id === 'gold18';
        let base = 'XAG';
        if (isGold) {
            base = 'XAU18';
        }
        const quote = 'IRT';
        const info = this.safeDict(response, id, {});
        return {
            'id': base + quote,
            'symbol': base + '/' + quote,
            'base': base,
            'quote': quote,
            'settle': undefined,
            'baseId': id,
            'quoteId': quote,
            'settleId': undefined,
            'type': 'otc',
            'spot': false,
            'margin': false,
            'swap': false,
            'future': false,
            'option': false,
            'active': true,
            'contract': false,
            'linear': undefined,
            'inverse': undefined,
            'contractSize': undefined,
            'expiry': undefined,
            'expiryDatetime': undefined,
            'strike': undefined,
            'optionType': undefined,
            'precision': {
                'amount': undefined,
                'price': undefined,
            },
            'limits': {
                'leverage': { 'min': undefined, 'max': undefined },
                'amount': { 'min': undefined, 'max': undefined },
                'price': { 'min': undefined, 'max': undefined },
                'cost': { 'min': undefined, 'max': undefined },
            },
            'created': undefined,
            'info': info,
        };
    }
    async fetchTicker(symbol, params = {}) {
        await this.loadMarkets();
        const market = this.market(symbol);
        const response = await this.fetchPrice(params);
        return this.parseTicker(response, market);
    }
    async fetchTickers(symbols = undefined, params = {}) {
        await this.loadMarkets();
        if (symbols !== undefined) {
            symbols = this.marketSymbols(symbols);
        }
        const response = await this.fetchPrice(params);
        const result = {};
        const marketSymbols = ['XAU18/IRT', 'XAG/IRT'];
        for (let i = 0; i < marketSymbols.length; i++) {
            const symbol = marketSymbols[i];
            const market = this.market(symbol);
            const ticker = this.parseTicker(response, market);
            result[ticker['symbol']] = ticker;
        }
        return this.filterByArrayTickers(result, 'symbol', symbols);
    }
    parseTicker(response, market = undefined) {
        const data = this.safeDict(response, market['baseId'], {});
        let price = this.safeNumber(data, 'price');
        if (price !== undefined) {
            price = price * 100;
        }
        return this.safeTicker({
            'symbol': market['symbol'],
            'timestamp': undefined,
            'datetime': undefined,
            'high': undefined,
            'low': undefined,
            'bid': price,
            'bidVolume': undefined,
            'ask': price,
            'askVolume': undefined,
            'vwap': undefined,
            'open': undefined,
            'close': price,
            'last': price,
            'previousClose': undefined,
            'change': undefined,
            'percentage': undefined,
            'average': undefined,
            'baseVolume': undefined,
            'quoteVolume': undefined,
            'info': data,
        }, market);
    }
    sign(path, api = 'public', method = 'GET', params = {}, headers = undefined, body = undefined) {
        let url = this.urls['api'][api] + '/' + this.implodeParams(path, params);
        const query = this.omit(params, this.extractParams(path));
        if (Object.keys(query).length) {
            url += '?' + this.urlencode(query);
        }
        headers = { 'Accept': 'application/json' };
        return { 'url': url, 'method': method, 'body': body, 'headers': headers };
    }
}
