// ----------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
// EDIT THE CORRESPONDENT .ts FILE INSTEAD

//  ---------------------------------------------------------------------------
import Exchange from './base/Exchange.js';
//  ---------------------------------------------------------------------------
/**
 * @class wallgold
 * @augments Exchange
 */
export default class wallgold extends Exchange {
    describe() {
        return this.deepExtend(super.describe(), {
            'id': 'wallgold',
            'name': 'WallGold',
            'countries': ['IR'],
            'rateLimit': 1000,
            'version': '1',
            'certified': false,
            'pro': false,
            'has': {
                'CORS': undefined,
                'spot': false,
                'margin': false,
                'swap': false,
                'future': false,
                'option': false,
                'fetchMarkets': true,
                'fetchTicker': true,
                'fetchTickers': true,
                'otc': true,
            },
            'options': {
                'defaultType': 'otc',
            },
            'urls': {
                'api': {
                    'public': 'https://api.wallgold.ir',
                },
                'www': 'https://wallgold.ir',
                'doc': 'https://wallgold.ir',
            },
            'api': {
                'public': {
                    'get': {
                        'api/v1/price': 1,
                    },
                },
            },
        });
    }
    async fetchMarkets(params = {}) {
        const response = await this.fetchPrice('buy', params);
        return [this.parseMarket(response)];
    }
    fetchPrice(side, params = {}) {
        return this.publicGetApiV1Price(this.extend({
            'side': side,
            'symbol': 'GLD_18C_750TMN',
        }, params));
    }
    parseMarket(response) {
        return {
            'id': 'XAU18IRT',
            'symbol': 'XAU18/IRT',
            'base': 'XAU18',
            'quote': 'IRT',
            'settle': undefined,
            'baseId': 'XAU18',
            'quoteId': 'IRT',
            'settleId': undefined,
            'type': 'otc',
            'spot': false,
            'margin': false,
            'swap': false,
            'future': false,
            'option': false,
            'active': this.safeBool(response, 'success', true),
            'contract': false,
            'linear': undefined,
            'inverse': undefined,
            'contractSize': undefined,
            'expiry': undefined,
            'expiryDatetime': undefined,
            'strike': undefined,
            'optionType': undefined,
            'precision': {
                'amount': undefined,
                'price': undefined,
            },
            'limits': {
                'leverage': { 'min': undefined, 'max': undefined },
                'amount': { 'min': undefined, 'max': undefined },
                'price': { 'min': undefined, 'max': undefined },
                'cost': { 'min': undefined, 'max': undefined },
            },
            'created': undefined,
            'info': response,
        };
    }
    async fetchTicker(symbol, params = {}) {
        await this.loadMarkets();
        const market = this.market(symbol);
        const buyResponse = await this.fetchPrice('buy', params);
        const sellResponse = await this.fetchPrice('sell', params);
        return this.parseTicker(buyResponse, market, sellResponse);
    }
    async fetchTickers(symbols = undefined, params = {}) {
        await this.loadMarkets();
        if (symbols !== undefined) {
            symbols = this.marketSymbols(symbols);
        }
        const market = this.market('XAU18/IRT');
        const buyResponse = await this.fetchPrice('buy', params);
        const sellResponse = await this.fetchPrice('sell', params);
        const ticker = this.parseTicker(buyResponse, market, sellResponse);
        const result = {};
        result[ticker['symbol']] = ticker;
        return this.filterByArrayTickers(result, 'symbol', symbols);
    }
    parseTicker(buyResponse, market = undefined, sellResponse = undefined) {
        const buyResult = this.safeDict(buyResponse, 'result', {});
        const sellResult = this.safeDict(sellResponse, 'result', buyResult);
        const bid = this.safeNumber(buyResult, 'price');
        const ask = this.safeNumber(sellResult, 'price');
        const currentTime = this.safeString(buyResult, 'currentTime');
        const timestamp = currentTime ? this.parse8601(currentTime) : undefined;
        return this.safeTicker({
            'symbol': market['symbol'],
            'timestamp': timestamp,
            'datetime': undefined,
            'high': undefined,
            'low': undefined,
            'bid': bid,
            'bidVolume': undefined,
            'ask': ask,
            'askVolume': undefined,
            'vwap': undefined,
            'open': undefined,
            'close': ask,
            'last': ask,
            'previousClose': undefined,
            'change': undefined,
            'percentage': undefined,
            'average': undefined,
            'baseVolume': undefined,
            'quoteVolume': undefined,
            'info': { 'buy': buyResponse, 'sell': sellResponse },
        }, market);
    }
    sign(path, api = 'public', method = 'GET', params = {}, headers = undefined, body = undefined) {
        let url = this.urls['api'][api] + '/' + this.implodeParams(path, params);
        const query = this.omit(params, this.extractParams(path));
        if (Object.keys(query).length) {
            url += '?' + this.urlencode(query);
        }
        headers = { 'Content-Type': 'application/json' };
        return { 'url': url, 'method': method, 'body': body, 'headers': headers };
    }
}
