// ----------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
// EDIT THE CORRESPONDENT .ts FILE INSTEAD

import ariomex from './src/ariomex.js';
import poulyar from './src/poulyar.js';
import ourbit from './src/ourbit.js';
import ubitex from './src/ubitex.js';
async function testTicker(exchange, name, params = {}) {
    try {
        await exchange.loadMarkets(false, params);
        const symbol = exchange.markets['BTC/USDT'] ? 'BTC/USDT' : exchange.symbols[0];
        if (symbol === undefined) {
            throw new Error(`${name} returned no markets`);
        }
        const ticker = await exchange.fetchTicker(symbol);
        if (ticker.symbol !== symbol) {
            throw new Error(`${name} returned ticker for ${ticker.symbol} instead of ${symbol}`);
        }
        console.log(`${name} ${symbol} ticker:`, {
            symbol: ticker.symbol,
            timestamp: ticker.timestamp,
            datetime: ticker.datetime,
            last: ticker.last,
            bid: ticker.bid,
            ask: ticker.ask,
        });
    }
    finally {
        await exchange.close();
    }
}
async function run() {
    await testTicker(new ariomex({ enableRateLimit: true, timeout: 30000 }), 'Ariomex');
    await testTicker(new poulyar({ enableRateLimit: true, timeout: 30000 }), 'Poulyar');
    await testTicker(new ourbit({ enableRateLimit: true, timeout: 30000 }), 'Ourbit', { type: 'spot' });
    await testTicker(new ubitex({ enableRateLimit: true, timeout: 30000 }), 'Ubitex');
}
void run();
