// ----------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
// EDIT THE CORRESPONDENT .ts FILE INSTEAD

import ccxt from './ccxt';
async function testsaraf() {
    const exchange = new ccxt.saraf({
        enableRateLimit: true,
        timeout: 20000,
    });
    try {
        const params = { 'type': 'otc' };
        const markets = await exchange.fetchMarkets(params);
        console.log('saraf markets count:', markets.length);
        console.log('saraf first markets:', markets.slice(0, 10).map((market) => ({
            symbol: market.symbol,
            id: market.id,
            type: market.type,
            active: market.active,
            amountPrecision: market.precision && market.precision.amount,
            pricePrecision: market.precision && market.precision.price,
        })));
        const tickers = await exchange.fetchTickers(undefined, params);
        const tickerSymbols = Object.keys(tickers);
        console.log('saraf tickers count:', tickerSymbols.length);
        const missingFromFetchTickers = [];
        const fetchTickerFailures = [];
        const sampleTickers = [];
        for (let j = 0; j < markets.length; j++) {
            const market = markets[j];
            const symbol = market.symbol;
            const tickerFromBulk = tickers[symbol];
            if (tickerFromBulk === undefined) {
                missingFromFetchTickers.push(symbol);
                continue;
            }
            if (sampleTickers.length < 10) {
                sampleTickers.push({
                    symbol: tickerFromBulk.symbol,
                    type: market.type,
                    last: tickerFromBulk.last,
                    bid: tickerFromBulk.bid,
                    ask: tickerFromBulk.ask,
                    high: tickerFromBulk.high,
                    low: tickerFromBulk.low,
                    baseVolume: tickerFromBulk.baseVolume,
                    quoteVolume: tickerFromBulk.quoteVolume,
                });
            }
            try {
                const singleTicker = await exchange.fetchTicker(symbol, params);
                console.log('checked saraf ticker:', {
                    symbol: singleTicker.symbol,
                    type: market.type,
                    last: singleTicker.last,
                    bid: singleTicker.bid,
                    ask: singleTicker.ask,
                });
            }
            catch (error) {
                fetchTickerFailures.push({
                    symbol,
                    type: market.type,
                    message: error instanceof Error ? error.message : String(error),
                });
            }
        }
        console.log('saraf sample bulk tickers:', sampleTickers);
        console.log('saraf missing from fetchTickers:', missingFromFetchTickers);
        console.log('saraf fetchTicker failures:', fetchTickerFailures);
        console.log('saraf summary:', {
            marketsCount: markets.length,
            tickersCount: tickerSymbols.length,
            missingFromFetchTickersCount: missingFromFetchTickers.length,
            fetchTickerFailuresCount: fetchTickerFailures.length,
        });
    }
    catch (error) {
        console.error('Error during testing saraf:', error);
    }
    finally {
        if (exchange.close) {
            await exchange.close();
        }
    }
}
testsaraf();
