# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.base.exchange import Exchange
from ccxt.abstract.asretether import ImplicitAPI
from ccxt.base.types import Any, Market, Strings, Ticker, Tickers
from typing import List


class asretether(Exchange, ImplicitAPI):

    def describe(self) -> Any:
        return self.deep_extend(super(asretether, self).describe(), {
            'id': 'asretether',
            'name': 'Asretether',
            'countries': ['IR'],
            'rateLimit': 1000,
            'version': '2',
            'certified': False,
            'pro': False,
            'has': {
                'CORS': None,
                'spot': True,
                'margin': False,
                'swap': False,
                'future': False,
                'option': False,
                'addMargin': False,
                'cancelAllOrders': False,
                'cancelOrder': False,
                'cancelOrders': False,
                'createDepositAddress': False,
                'createOrder': False,
                'createStopLimitOrder': False,
                'createStopMarketOrder': False,
                'createStopOrder': False,
                'editOrder': False,
                'fetchBalance': False,
                'fetchBorrowInterest': False,
                'fetchBorrowRateHistories': False,
                'fetchBorrowRateHistory': False,
                'fetchClosedOrders': False,
                'fetchCrossBorrowRate': False,
                'fetchCrossBorrowRates': False,
                'fetchCurrencies': False,
                'fetchDepositAddress': False,
                'fetchDeposits': False,
                'fetchFundingHistory': False,
                'fetchFundingRate': False,
                'fetchFundingRateHistory': False,
                'fetchFundingRates': False,
                'fetchIndexOHLCV': False,
                'fetchIsolatedBorrowRate': False,
                'fetchIsolatedBorrowRates': False,
                'fetchL2OrderBook': False,
                'fetchL3OrderBook': False,
                'fetchLedger': False,
                'fetchLedgerEntry': False,
                'fetchLeverageTiers': False,
                'fetchMarkets': True,
                'fetchMarkOHLCV': False,
                'fetchMyTrades': False,
                'fetchOHLCV': False,
                'fetchOpenInterestHistory': False,
                'fetchOpenOrders': False,
                'fetchOrder': False,
                'fetchOrderBook': False,
                'fetchOrders': False,
                'fetchOrderTrades': False,
                'fetchPositions': False,
                'fetchPremiumIndexOHLCV': False,
                'fetchTicker': True,
                'fetchTickers': True,
                'fetchTime': False,
                'fetchTrades': False,
                'fetchTradingFee': False,
                'fetchTradingFees': False,
                'fetchWithdrawals': False,
                'otc': True,
                'setLeverage': False,
                'setMarginMode': False,
                'transfer': False,
                'withdraw': False,
            },
            'comment': 'OTC market for USDT and other cryptocurrencies',
            'urls': {
                'logo': 'https://cdn.arz.digital/cr-odin/img/exchanges/asretether/64x64.png',
                'api': {
                    'public': 'https://api.asretether.com',
                },
                'www': 'https://asretether.com',
                'doc': [
                    'https://api.asretether.com/docs',
                ],
            },
            'api': {
                'public': {
                    'get': {
                        'v2/market': 1,
                    },
                },
            },
            'fees': {
                'trading': {
                    'tierBased': False,
                    'percentage': True,
                    'maker': self.parse_number('0'),
                    'taker': self.parse_number('0'),
                },
            },
        })

    def fetch_markets(self, params={}) -> List[Market]:
        """
        retrieves data on all markets for asretether
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict[]: an array of objects representing market data
        """
        response = self.publicGetV2Market(params)
        data = self.safe_list(response, 'data', [])
        result = []
        for i in range(0, len(data)):
            market = self.parse_market(data[i])
            result.append(market)
        return result

    def parse_market(self, market) -> Market:
        #         {
        # id: 2,
        # symbol: "USDT-IRT",
        # status: "ACTIVE",
        # high_24h: "181978",
        # low_24h: "172874",
        # irt_high_24h: 0,
        # irt_low_24h: 0,
        # change_24h: 0,
        # volume_24h: 100000,
        # price: {
        # price_buy: "178410",
        # price_sell: "176402",
        # price_in_tether: "1.0000"
        # },
        # base_currency: {
        # slug: "USDT",
        # decimals: 6,
        # full_name: "Tether",
        # persian_name: "تتر",
        # icon_url: "https://box.asretether.com/currency-icons/usdt.png"
        # },
        # quote_currency: {
        # slug: "IRT",
        # decimals: 0,
        # full_name: "IR Toman",
        # persian_name: "تومان",
        # icon_url: "https://box.asretether.com/currency-icons/irt.png"
        # }
        # },
        id = self.safe_string(market, 'symbol')
        baseCurrency = self.safe_dict(market, 'base_currency', {})
        quoteCurrency = self.safe_dict(market, 'quote_currency', {})
        baseId = self.safe_string(baseCurrency, 'slug')
        quoteId = self.safe_string(quoteCurrency, 'slug')
        base = self.safe_currency_code(baseId)
        quote = self.safe_currency_code(quoteId)
        basePrecision = self.safe_integer(baseCurrency, 'decimals')
        quotePrecision = self.safe_integer(quoteCurrency, 'decimals')
        status = self.safe_string(market, 'status')
        enabled = status == 'ACTIVE'
        return {
            'id': id,
            'symbol': base + '/' + quote,
            'base': base,
            'quote': quote,
            'settle': None,
            'baseId': baseId,
            'quoteId': quoteId,
            'settleId': None,
            'type': 'otc',
            'spot': False,
            'margin': False,
            'swap': False,
            'future': False,
            'option': False,
            'active': enabled,
            'contract': False,
            'linear': None,
            'inverse': None,
            'contractSize': None,
            'expiry': None,
            'expiryDatetime': None,
            'strike': None,
            'optionType': None,
            'precision': {
                'amount': basePrecision,
                'price': quotePrecision,
            },
            'limits': {
                'leverage': {
                    'min': None,
                    'max': None,
                },
                'amount': {
                    'min': None,
                    'max': None,
                },
                'price': {
                    'min': None,
                    'max': None,
                },
                'cost': {
                    'min': None,
                    'max': None,
                },
            },
            'created': None,
            'info': market,
        }

    def fetch_tickers(self, symbols: Strings = None, params={}) -> Tickers:
        """
        fetches price tickers for multiple markets, statistical information calculated over the past 24 hours for each market
        :param str[]|None symbols: unified symbols of the markets to fetch the ticker for, all market tickers are returned if not assigned
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a dictionary of `ticker structures <https://docs.ccxt.com/#/?id=ticker-structure>`
        """
        self.load_markets()
        if symbols is not None:
            symbols = self.market_symbols(symbols)
        response = self.publicGetV2Market(params)
        data = self.safe_list(response, 'data', [])
        result = {}
        for i in range(0, len(data)):
            ticker = self.parse_ticker(data[i])
            symbol = ticker['symbol']
            result[symbol] = ticker
        return self.filter_by_array_tickers(result, 'symbol', symbols)

    def fetch_ticker(self, symbol: str, params={}) -> Ticker:
        """
        fetches a price ticker, a statistical calculation with the information calculated over the past 24 hours for a specific market
        :param str symbol: unified symbol of the market to fetch the ticker for
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a `ticker structure <https://docs.ccxt.com/#/?id=ticker-structure>`
        """
        self.load_markets()
        market = self.market(symbol)
        request = {
            'symbol': market['id'],
        }
        response = self.publicGetV2Market(request)
        data = self.safe_list(response, 'data', [])
        if len(data) > 0:
            return self.parse_ticker(data[0], market)
        raise Error('Ticker not found')

    def parse_ticker(self, ticker, market: Market = None) -> Ticker:
        baseCurrency = self.safe_dict(ticker, 'base_currency', {})
        quoteCurrency = self.safe_dict(ticker, 'quote_currency', {})
        baseId = self.safe_string(baseCurrency, 'slug')
        quoteId = self.safe_string(quoteCurrency, 'slug')
        base = self.safe_currency_code(baseId)
        quote = self.safe_currency_code(quoteId)
        symbol = base + '/' + quote
        # Handle price selection based on quote currency
        price = self.safe_dict(ticker, 'price', {})
        last = None
        if quote == 'IRT':
            last = self.safe_float(price, 'price_sell')
        elif quote == 'USDT':
            last = self.safe_float(price, 'price_in_tether')
        high = self.safe_float(ticker, 'high_24h')
        low = self.safe_float(ticker, 'low_24h')
        baseVolume = self.safe_float(ticker, 'volume_24h')
        return self.safe_ticker({
            'symbol': symbol,
            'timestamp': None,
            'datetime': None,
            'high': high,
            'low': low,
            'bid': None,
            'bidVolume': None,
            'ask': None,
            'askVolume': None,
            'vwap': None,
            'open': None,
            'close': last,
            'last': last,
            'previousClose': None,
            'change': self.safe_float(ticker, 'change_24h'),
            'percentage': None,
            'average': None,
            'baseVolume': baseVolume,
            'quoteVolume': None,
            'info': ticker,
        }, market)

    def sign(self, path, api='public', method='GET', params={}, headers=None, body=None):
        url = self.urls['api']['public'] + '/' + path
        query = self.omit(params, self.extract_params(path))
        query['limit'] = self.safe_string(query, 'limit', '1000')
        # Add query parameters if any remain
        if query:
            url = url + '?' + self.urlencode(query)
        headers = {'Content-Type': 'application/json'}
        return {'url': url, 'method': method, 'body': body, 'headers': headers}
