# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.base.exchange import Exchange
from ccxt.abstract.bitwana import ImplicitAPI
from ccxt.base.types import Any, Market, Strings, Ticker, Tickers
from typing import List


class bitwana(Exchange, ImplicitAPI):

    def market_type_to_symbol(self, base: str, quote: str, marketType='spot') -> str:
        return base + '/' + quote

    def describe(self) -> Any:
        return self.deep_extend(super(bitwana, self).describe(), {
            'id': 'bitwana',
            'name': 'Bitwana',
            'countries': ['IR'],
            'rateLimit': 1000,
            'version': '1',
            'certified': False,
            'pro': False,
            'has': {
                'CORS': None,
                'spot': True,
                'margin': False,
                'swap': False,
                'future': False,
                'option': False,
                'addMargin': False,
                'cancelAllOrders': False,
                'cancelOrder': False,
                'cancelOrders': False,
                'createDepositAddress': False,
                'createOrder': False,
                'createStopLimitOrder': False,
                'createStopMarketOrder': False,
                'createStopOrder': False,
                'editOrder': False,
                'fetchBalance': False,
                'fetchBorrowInterest': False,
                'fetchBorrowRateHistories': False,
                'fetchBorrowRateHistory': False,
                'fetchClosedOrders': False,
                'fetchCrossBorrowRate': False,
                'fetchCrossBorrowRates': False,
                'fetchCurrencies': False,
                'fetchDepositAddress': False,
                'fetchDeposits': False,
                'fetchFundingHistory': False,
                'fetchFundingRate': False,
                'fetchFundingRateHistory': False,
                'fetchFundingRates': False,
                'fetchIndexOHLCV': False,
                'fetchIsolatedBorrowRate': False,
                'fetchIsolatedBorrowRates': False,
                'fetchL2OrderBook': False,
                'fetchL3OrderBook': False,
                'fetchLedger': False,
                'fetchLedgerEntry': False,
                'fetchLeverageTiers': False,
                'fetchMarkets': True,
                'fetchMarkOHLCV': False,
                'fetchMyTrades': False,
                'fetchOHLCV': False,
                'fetchOpenInterestHistory': False,
                'fetchOpenOrders': False,
                'fetchOrder': False,
                'fetchOrderBook': False,
                'fetchOrders': False,
                'fetchOrderTrades': 'emulated',
                'fetchPositions': False,
                'fetchPremiumIndexOHLCV': False,
                'fetchTicker': True,
                'fetchTickers': True,
                'fetchTime': False,
                'fetchTrades': False,
                'fetchTradingFee': False,
                'fetchTradingFees': False,
                'fetchWithdrawals': False,
                'otc': True,
                'setLeverage': False,
                'setMarginMode': False,
                'transfer': False,
                'withdraw': False,
            },
            'comment': 'This comment is optional',
            'urls': {
                'logo': 'https://bitwana.com/favicon.ico',
                'api': {
                    'public': 'https://bitwana.com',
                },
                'www': 'https://bitwana.com/',
                'doc': [
                    'https://bitwana.com/',
                ],
            },
            'api': {
                'public': {
                    'get': {
                        'api/1/markets': 1,
                        'api/1/markets/{id}': 1,
                    },
                },
            },
            'fees': {
            },
        })

    def parse_spot_market(self, market) -> Market:
        # {
        #     "id": "BTC_IRT",
        #     "symbol": "بیت‌کوین-تومان",
        #     "base": "BTC",
        #     "quote": "IRT",
        #     "buyPrice": "10222846365",
        #     "sellPrice": "10233403625",
        #     "userOrderPricePrecision": 0,
        #     "quantityPrecision": 6,
        #     "minimumOrder": 100000,
        #     "maximumOrder": 300000000,
        #     "lastTradedPrice": "10249911984",
        #     "lowestPrice": "10063564406",
        #     "highestPrice": "10320391247",
        #     "sourceVolume": "0.036557",
        #     "destinationVolume": "371770611.78",
        #     "tradingEnabled": True,
        #     "otcEnabled": False,
        # }
        id = self.safe_string(market, 'id')
        baseId = self.safe_string(market, 'base')
        quoteId = self.safe_string(market, 'quote')
        base = self.safe_currency_code(baseId)
        quote = self.safe_currency_code(quoteId)
        return {
            'id': id,
            'symbol': self.market_type_to_symbol(base, quote, 'spot'),
            'base': base,
            'quote': quote,
            'settle': None,
            'baseId': baseId,
            'quoteId': quoteId,
            'settleId': None,
            'type': 'spot',
            'spot': True,
            'margin': False,
            'swap': False,
            'future': False,
            'option': False,
            'active': True,
            'contract': False,
            'linear': None,
            'inverse': None,
            'contractSize': None,
            'expiry': None,
            'expiryDatetime': None,
            'strike': None,
            'optionType': None,
            'precision': {
                'amount': self.safe_integer(market, 'quantityPrecision'),
                'price': self.safe_integer(market, 'userOrderPricePrecision'),
            },
            'limits': {
                'leverage': {
                    'min': None,
                    'max': None,
                },
                'amount': {
                    'min': None,
                    'max': None,
                },
                'price': {
                    'min': None,
                    'max': None,
                },
                'cost': {
                    'min': self.safe_number(market, 'minimumOrder'),
                    'max': self.safe_number(market, 'maximumOrder'),
                },
            },
            'created': None,
            'info': market,
        }

    def parse_otc_market(self, market) -> Market:
        rawId = self.safe_string(market, 'id')
        baseId = self.safe_string(market, 'base')
        quoteId = self.safe_string(market, 'quote')
        base = self.safe_currency_code(baseId)
        quote = self.safe_currency_code(quoteId)
        return {
            'id': rawId + '_OTC',
            'symbol': self.market_type_to_symbol(base, quote, 'otc'),
            'base': base,
            'quote': quote,
            'settle': None,
            'baseId': baseId,
            'quoteId': quoteId,
            'settleId': None,
            'type': 'otc',
            'spot': False,
            'margin': False,
            'swap': False,
            'future': False,
            'option': False,
            'active': True,
            'contract': False,
            'linear': None,
            'inverse': None,
            'contractSize': None,
            'expiry': None,
            'expiryDatetime': None,
            'strike': None,
            'optionType': None,
            'precision': {
                'amount': self.safe_integer(market, 'quantityPrecision'),
                'price': self.safe_integer(market, 'userOrderPricePrecision'),
            },
            'limits': {
                'leverage': {
                    'min': None,
                    'max': None,
                },
                'amount': {
                    'min': None,
                    'max': None,
                },
                'price': {
                    'min': None,
                    'max': None,
                },
                'cost': {
                    'min': self.safe_number(market, 'minimumOrder'),
                    'max': self.safe_number(market, 'maximumOrder'),
                },
            },
            'created': None,
            'info': market,
        }

    def fetch_markets(self, params={}) -> List[Market]:
        """
        retrieves data on all markets for bitwana
        https://bitwana.com/api/1/markets?with_price=true
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict[]: an array of objects representing market data
        """
        marketType = self.safe_string(params, 'type', 'spot')
        request = {
            'with_price': True,
        }
        response = self.publicGetApi1Markets(self.extend(request, params))
        markets = self.safe_list(response, 'content', [])
        result = []
        for i in range(0, len(markets)):
            market = markets[i]
            if marketType == 'otc':
                result.append(self.parse_otc_market(market))
            else:
                result.append(self.parse_spot_market(market))
        return result

    def fetch_tickers(self, symbols: Strings = None, params={}) -> Tickers:
        """
        fetches price tickers for multiple markets, statistical information calculated over the past 24 hours for each market
        https://bitwana.com/api/1/markets?with_price=true
        :param str[]|None symbols: unified symbols of the markets to fetch the ticker for, all market tickers are returned if not assigned
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a dictionary of `ticker structures <https://docs.ccxt.com/#/?id=ticker-structure>`
        """
        marketType = self.safe_string(params, 'type', 'spot')
        self.load_markets(False, {'type': marketType})
        if symbols is not None:
            symbols = self.market_symbols(symbols)
        request = {
            'with_price': True,
        }
        response = self.publicGetApi1Markets(self.extend(request, params))
        markets = self.safe_list(response, 'content', [])
        result = {}
        for i in range(0, len(markets)):
            market = markets[i]
            if marketType == 'otc':
                otcTicker = self.parse_otc_ticker(market)
                result[otcTicker['symbol']] = otcTicker
            else:
                spotTicker = self.parse_spot_ticker(market)
                result[spotTicker['symbol']] = spotTicker
        return self.filter_by_array_tickers(result, 'symbol', symbols)

    def fetch_ticker(self, symbol: str, params={}) -> Ticker:
        """
        fetches a price ticker, a statistical calculation with the information calculated over the past 24 hours for a specific market
        https://bitwana.com/api/1/markets/BTC_IRT?with_price=true
        :param str symbol: unified symbol of the market to fetch the ticker for
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a `ticker structure <https://docs.ccxt.com/#/?id=ticker-structure>`
        """
        marketType = self.safe_string(params, 'type', 'spot')
        self.load_markets(False, {'type': marketType})
        market = self.market(symbol)
        request = {
            'id': self.safe_string(market['info'], 'id'),
            'with_price': True,
        }
        response = self.publicGetApi1MarketsId(self.extend(request, params))
        ticker = self.safe_dict(response, 'content')
        if marketType == 'otc':
            return self.parse_otc_ticker(ticker, market)
        return self.parse_spot_ticker(ticker, market)

    def parse_spot_ticker(self, ticker, market: Market = None) -> Ticker:
        baseId = self.safe_string(ticker, 'base')
        quoteId = self.safe_string(ticker, 'quote')
        base = self.safe_currency_code(baseId)
        quote = self.safe_currency_code(quoteId)
        symbol = self.market_type_to_symbol(base, quote, 'spot')
        if market is not None:
            symbol = market['symbol']
        high = self.safe_number(ticker, 'highestPrice')
        low = self.safe_number(ticker, 'lowestPrice')
        bid = self.safe_number(ticker, 'buyPrice')
        ask = self.safe_number(ticker, 'sellPrice')
        last = self.safe_number(ticker, 'lastTradedPrice')
        change = self.safe_number(ticker, 'changePrice')
        percentage = self.safe_number(ticker, 'changeRate')
        baseVolume = self.safe_number(ticker, 'sourceVolume')
        quoteVolume = self.safe_number(ticker, 'destinationVolume')
        return self.safe_ticker({
            'symbol': symbol,
            'timestamp': None,
            'datetime': None,
            'high': high,
            'low': low,
            'bid': bid,
            'bidVolume': None,
            'ask': ask,
            'askVolume': None,
            'vwap': None,
            'open': None,
            'close': last,
            'last': last,
            'previousClose': None,
            'change': change,
            'percentage': percentage,
            'average': None,
            'baseVolume': baseVolume,
            'quoteVolume': quoteVolume,
            'info': ticker,
        }, market)

    def parse_otc_ticker(self, ticker, market: Market = None) -> Ticker:
        baseId = self.safe_string(ticker, 'base')
        quoteId = self.safe_string(ticker, 'quote')
        base = self.safe_currency_code(baseId)
        quote = self.safe_currency_code(quoteId)
        symbol = self.market_type_to_symbol(base, quote, 'otc')
        if market is not None:
            symbol = market['symbol']
        high = self.safe_number(ticker, 'highestPrice')
        low = self.safe_number(ticker, 'lowestPrice')
        bid = self.safe_number(ticker, 'buyPrice')
        ask = self.safe_number(ticker, 'sellPrice')
        last = self.safe_number(ticker, 'lastTradedPrice')
        change = self.safe_number(ticker, 'changePrice')
        percentage = self.safe_number(ticker, 'changeRate')
        return self.safe_ticker({
            'symbol': symbol,
            'timestamp': None,
            'datetime': None,
            'high': high,
            'low': low,
            'bid': bid,
            'bidVolume': None,
            'ask': ask,
            'askVolume': None,
            'vwap': None,
            'open': None,
            'close': last,
            'last': last,
            'previousClose': None,
            'change': change,
            'percentage': percentage,
            'average': None,
            'baseVolume': None,
            'quoteVolume': None,
            'info': ticker,
        }, market)

    def sign(self, path, api='public', method='GET', params={}, headers=None, body=None):
        query = self.omit(params, self.extract_params(path))
        url = self.urls['api'][api] + '/' + self.implode_params(path, params)
        if query:
            url += '?' + self.urlencode(query)
        headers = {'Content-Type': 'application/json'}
        return {'url': url, 'method': method, 'body': body, 'headers': headers}
