# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.base.exchange import Exchange
from ccxt.abstract.goldis import ImplicitAPI
from ccxt.base.types import Any, Market, Strings, Ticker, Tickers
from typing import List


class goldis(Exchange, ImplicitAPI):

    def describe(self) -> Any:
        return self.deep_extend(super(goldis, self).describe(), {
            'id': 'goldis',
            'name': 'Goldis',
            'countries': ['IR'],
            'rateLimit': 1000,
            'version': 'v1',
            'certified': False,
            'pro': False,
            'has': {
                'CORS': None,
                'spot': False,
                'margin': False,
                'swap': False,
                'future': False,
                'option': False,
                'fetchMarkets': True,
                'fetchTicker': True,
                'fetchTickers': True,
                'otc': True,
            },
            'options': {
                'defaultType': 'otc',
            },
            'urls': {
                'api': {
                    'public': 'https://goldis.ir',
                },
                'www': 'https://goldis.ir',
                'doc': 'https://goldis.ir/backend/api/v1/pricing/spot?metal=gold',
            },
            'api': {
                'public': {
                    'get': {
                        'backend/api/v1/pricing/spot': 1,
                    },
                },
            },
        })

    def fetch_price(self, params={}):
        return self.publicGetBackendApiV1PricingSpot(self.extend({'metal': 'gold'}, params))

    def fetch_markets(self, params={}) -> List[Market]:
        response = self.fetch_price(params)
        return [self.parse_market(response)]

    def parse_market(self, response) -> Market:
        return {
            'id': 'XAU18IRT',
            'symbol': 'XAU18/IRT',
            'base': 'XAU18',
            'quote': 'IRT',
            'settle': None,
            'baseId': 'XAU18',
            'quoteId': 'IRT',
            'settleId': None,
            'type': 'otc',
            'spot': False,
            'margin': False,
            'swap': False,
            'future': False,
            'option': False,
            'active': self.safe_number(response, 'price_per_gram_rial') is not None,
            'contract': False,
            'linear': None,
            'inverse': None,
            'contractSize': None,
            'expiry': None,
            'expiryDatetime': None,
            'strike': None,
            'optionType': None,
            'precision': {
                'amount': None,
                'price': None,
            },
            'limits': {
                'leverage': {'min': None, 'max': None},
                'amount': {'min': None, 'max': None},
                'price': {'min': None, 'max': None},
                'cost': {'min': None, 'max': None},
            },
            'created': None,
            'info': response,
        }

    def fetch_ticker(self, symbol: str, params={}) -> Ticker:
        self.load_markets()
        market = self.market(symbol)
        response = self.fetch_price(params)
        return self.parse_ticker(response, market)

    def fetch_tickers(self, symbols: Strings = None, params={}) -> Tickers:
        self.load_markets()
        if symbols is not None:
            symbols = self.market_symbols(symbols)
        response = self.fetch_price(params)
        market = self.market('XAU18/IRT')
        ticker = self.parse_ticker(response, market)
        result = {}
        result[ticker['symbol']] = ticker
        return self.filter_by_array_tickers(result, 'symbol', symbols)

    def parse_ticker(self, response, market: Market = None) -> Ticker:
        price = self.safe_number(response, 'price_per_gram_rial')
        if price is not None:
            price = price / 10
        return self.safe_ticker({
            'symbol': market['symbol'],
            'timestamp': self.parse8601(self.safe_string(response, 'as_of')),
            'datetime': None,
            'high': None,
            'low': None,
            'bid': price,
            'bidVolume': None,
            'ask': price,
            'askVolume': None,
            'vwap': None,
            'open': None,
            'close': price,
            'last': price,
            'previousClose': None,
            'change': None,
            'percentage': None,
            'average': None,
            'baseVolume': None,
            'quoteVolume': None,
            'info': response,
        }, market)

    def sign(self, path, api='public', method='GET', params={}, headers=None, body=None):
        url = self.urls['api'][api] + '/' + self.implode_params(path, params)
        query = self.omit(params, self.extract_params(path))
        if query:
            url += '?' + self.urlencode(query)
        headers = {'Accept': 'application/json'}
        return {'url': url, 'method': method, 'body': body, 'headers': headers}
