# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.base.exchange import Exchange
from ccxt.abstract.melligold import ImplicitAPI
from ccxt.base.types import Any, Market, Strings, Ticker, Tickers
from typing import List


class melligold(Exchange, ImplicitAPI):

    def describe(self) -> Any:
        return self.deep_extend(super(melligold, self).describe(), {
            'id': 'melligold',
            'name': 'MelliGold',
            'countries': ['IR'],
            'rateLimit': 1000,
            'version': '1',
            'certified': False,
            'pro': False,
            'has': {
                'CORS': None,
                'spot': False,
                'margin': False,
                'swap': False,
                'future': False,
                'option': False,
                'fetchMarkets': True,
                'fetchTicker': True,
                'fetchTickers': True,
                'otc': True,
            },
            'options': {
                'defaultType': 'otc',
                'melligoldCookie': '__arcscoc=arcookie-1788797140-383667a29094e04aa24dad8d82bc9a7b; __arcsco=04c5ea50d6d25aca86f87dc8eae62af2',
                'manualRedirect': True,
            },
            'urls': {
                'api': {
                    'public': 'https://melligold.com',
                },
                'www': 'https://melligold.com',
                'doc': 'https://melligold.com',
            },
            'api': {
                'public': {
                    'get': {
                        'api/v1/exchange/buy-sell-price/': 1,
                    },
                },
            },
        })

    def fetch_markets(self, params={}) -> List[Market]:
        symbols = ['XAU18', 'XAG']
        result = []
        for i in range(0, len(symbols)):
            response = self.request_with_cookie(self.extend({
                'symbol': symbols[i],
                'format': 'json',
            }, params))
            result.append(self.parse_market(response, symbols[i]))
        return result

    def request_with_cookie(self, params={}):
        try:
            return self.publicGetApiV1ExchangeBuySellPrice(params)
        except Exception as error:
            responseHeaders = self.last_response_headers or {}
            setCookie = self.safe_string(responseHeaders, 'Set-Cookie')
            if setCookie is not None:
                cookies = setCookie.split(', ')
                values = []
                for i in range(0, len(cookies)):
                    values.append(cookies[i].split(';')[0])
                cookie = '; '.join(values)
                if cookie != '' and cookie != self.options['melligoldCookie']:
                    self.options['melligoldCookie'] = cookie
                    return self.publicGetApiV1ExchangeBuySellPrice(params)
            raise error

    def parse_market(self, response, baseId: str = None) -> Market:
        data = self.safe_dict(response, 'data', {})
        lowerAmounts = self.safe_dict(data, 'lower_amounts', {})
        base = self.safe_currency_code(baseId)
        quote = 'IRT'
        return {
            'id': base + quote,
            'symbol': base + '/' + quote,
            'base': base,
            'quote': quote,
            'settle': None,
            'baseId': baseId,
            'quoteId': quote,
            'settleId': None,
            'type': 'otc',
            'spot': False,
            'margin': False,
            'swap': False,
            'future': False,
            'option': False,
            'active': True,
            'contract': False,
            'linear': None,
            'inverse': None,
            'contractSize': None,
            'expiry': None,
            'expiryDatetime': None,
            'strike': None,
            'optionType': None,
            'precision': {
                'amount': None,
                'price': None,
            },
            'limits': {
                'leverage': {'min': None, 'max': None},
                'amount': {'min': None, 'max': None},
                'price': {'min': None, 'max': None},
                'cost': {
                    'min': self.safe_number(lowerAmounts, 'buy_toman'),
                    'max': None,
                },
            },
            'created': None,
            'info': response,
        }

    def fetch_ticker(self, symbol: str, params={}) -> Ticker:
        self.load_markets()
        market = self.market(symbol)
        response = self.request_with_cookie(self.extend({
            'symbol': market['baseId'],
            'format': 'json',
        }, params))
        return self.parse_ticker(response, market)

    def fetch_tickers(self, symbols: Strings = None, params={}) -> Tickers:
        self.load_markets()
        if symbols is not None:
            symbols = self.market_symbols(symbols)
        result = {}
        marketSymbols = ['XAU18/IRT', 'XAG/IRT']
        for i in range(0, len(marketSymbols)):
            market = self.market(marketSymbols[i])
            response = self.request_with_cookie(self.extend({
                'symbol': market['baseId'],
                'format': 'json',
            }, params))
            ticker = self.parse_ticker(response, market)
            result[ticker['symbol']] = ticker
        return self.filter_by_array_tickers(result, 'symbol', symbols)

    def parse_ticker(self, response, market: Market = None) -> Ticker:
        data = self.safe_dict(response, 'data', {})
        buy = self.safe_number(data, 'price_buy')
        sell = self.safe_number(data, 'price_sell')
        return self.safe_ticker({
            'symbol': market['symbol'],
            'timestamp': self.safe_timestamp(data, 'timestamp'),
            'datetime': None,
            'high': None,
            'low': None,
            'bid': sell,
            'bidVolume': None,
            'ask': buy,
            'askVolume': None,
            'vwap': None,
            'open': None,
            'close': buy,
            'last': buy,
            'previousClose': None,
            'change': None,
            'percentage': None,
            'average': None,
            'baseVolume': None,
            'quoteVolume': None,
            'info': response,
        }, market)

    def sign(self, path, api='public', method='GET', params={}, headers=None, body=None):
        url = self.urls['api'][api] + '/' + self.implode_params(path, params)
        query = self.omit(params, self.extract_params(path))
        if query:
            url += '?' + self.urlencode(query)
        headers = {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
            'User-Agent': 'Mozilla/5.0(Windows NT 10.0; Win64; x64) AppleWebKit/537.36(KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
        }
        if self.options['melligoldCookie'] is not None:
            headers['Cookie'] = self.options['melligoldCookie']
        return {'url': url, 'method': method, 'body': body, 'headers': headers}
