# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.base.exchange import Exchange
from ccxt.abstract.raastin import ImplicitAPI
from ccxt.base.types import Any, Int, Market, OrderBook, Strings, Ticker, Tickers
from typing import List


class raastin(Exchange, ImplicitAPI):

    def describe(self) -> Any:
        return self.deep_extend(super(raastin, self).describe(), {
            'id': 'raastin',
            'name': 'Raastin',
            'countries': ['IR'],
            'rateLimit': 1000,
            'version': '1',
            'certified': False,
            'pro': False,
            'has': {
                'CORS': None,
                'spot': True,
                'margin': False,
                'swap': False,
                'future': False,
                'option': False,
                'addMargin': False,
                'cancelAllOrders': False,
                'cancelOrder': False,
                'cancelOrders': False,
                'createDepositAddress': False,
                'createOrder': False,
                'createStopLimitOrder': False,
                'createStopMarketOrder': False,
                'createStopOrder': False,
                'editOrder': False,
                'fetchBalance': False,
                'fetchBorrowInterest': False,
                'fetchBorrowRateHistories': False,
                'fetchBorrowRateHistory': False,
                'fetchClosedOrders': False,
                'fetchCrossBorrowRate': False,
                'fetchCrossBorrowRates': False,
                'fetchCurrencies': False,
                'fetchDepositAddress': False,
                'fetchDeposits': False,
                'fetchFundingHistory': False,
                'fetchFundingRate': False,
                'fetchFundingRateHistory': False,
                'fetchFundingRates': False,
                'fetchIndexOHLCV': False,
                'fetchIsolatedBorrowRate': False,
                'fetchIsolatedBorrowRates': False,
                'fetchL2OrderBook': False,
                'fetchL3OrderBook': False,
                'fetchLedger': False,
                'fetchLedgerEntry': False,
                'fetchLeverageTiers': False,
                'fetchMarkets': True,
                'fetchMarkOHLCV': False,
                'fetchMyTrades': False,
                'fetchOHLCV': False,
                'fetchOpenInterestHistory': False,
                'fetchOpenOrders': False,
                'fetchOrder': False,
                'fetchOrderBook': True,
                'fetchOrders': False,
                'fetchOrderTrades': 'emulated',
                'fetchPositions': False,
                'fetchPremiumIndexOHLCV': False,
                'fetchTicker': True,
                'fetchTickers': True,
                'fetchTime': False,
                'fetchTrades': False,
                'fetchTradingFee': False,
                'fetchTradingFees': False,
                'fetchWithdrawals': False,
                'setLeverage': False,
                'setMarginMode': False,
                'transfer': False,
                'withdraw': False,
            },
            'comment': 'This comment is optional',
            'urls': {
                'logo': 'https://cdn.arz.digital/cr-odin/img/exchanges/raastin/64x64.png',
                'api': {
                    'public': 'https://api.raastin.com',
                },
                'www': 'https://raastin.com',
                'doc': [
                    'https://api.raastin.com/docs',
                ],
            },
            'api': {
                'public': {
                    'get': {
                        'api/v1/market/symbols': 1,
                        'api/v1/market/symbols/{symbol}/': 1,
                        'api/v1/market/depth/{symbol}': 1,
                    },
                },
            },
            'fees': {
                'trading': {
                    'tierBased': False,
                    'percentage': True,
                    'maker': self.parse_number('0'),
                    'taker': self.parse_number('0.002'),
                },
            },
        })

    def fetch_markets(self, params={}) -> List[Market]:
        """
        retrieves data on all markets for raastin
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict[]: an array of objects representing market data
        """
        response = self.publicGetApiV1MarketSymbols(params)
        # Response is a flat array, not nested in 'result'
        markets = response
        result = []
        for i in range(0, len(markets)):
            market = self.parse_market(markets[i])
            result.append(market)
        return result

    def parse_market(self, market) -> Market:
        #  {
        #     "id": 1,
        #     "name": "USDTIRT",
        #     "asset": {
        #         "id": 4,
        #         "symbol": "USDT",
        #         "precision": 8,
        #         "step_size": 8,
        #         "name": "tether",
        #         "name_fa": "تتر",
        #         "logo": "https://cdn.raastin.com/core-media-public/coins/logo/USDT.png",
        #         "original_symbol": "USDT",
        #         "original_name_fa": "تتر",
        #         "trading_view_symbol": "BINANCE:USDTUSDT.P",
        #         "otc_status": "active",
        #         "price_page": True
        #     },
        #     "base_asset": {
        #         "id": 1,
        #         "symbol": "IRT",
        #         "precision": 0,
        #         "step_size": 8,
        #         "name": "toman",
        #         "name_fa": "تومان",
        #         "logo": "https://cdn.raastin.com/core-media-public/coins/logo/IRT.png",
        #         "original_symbol": "IRT",
        #         "original_name_fa": "تومان",
        #         "trading_view_symbol": "",
        #         "otc_status": "active",
        #         "price_page": True
        #     },
        #     "taker_fee": "0.002",
        #     "maker_fee": "0",
        #     "tick_size": 0,
        #     "step_size": 2,
        #     "min_trade_quantity": "0",
        #     "max_trade_quantity": "1000000000000000000",
        #     "enable": True,
        #     "bookmark": False,
        #     "margin_enable": True,
        #     "strategy_enable": True
        # }
        id = self.safe_string(market, 'name')
        asset = self.safe_dict(market, 'asset', {})
        baseAsset = self.safe_dict(market, 'base_asset', {})
        baseId = self.safe_string(asset, 'symbol')
        quoteId = self.safe_string(baseAsset, 'symbol')
        base = self.safe_currency_code(baseId)
        quote = self.safe_currency_code(quoteId)
        baseId = baseId.lower()
        quoteId = quoteId.lower()
        basePrecision = self.safe_integer(asset, 'precision')
        quotePrecision = self.safe_integer(baseAsset, 'precision')
        minAmount = self.safe_string(market, 'min_trade_quantity')
        maxAmount = self.safe_string(market, 'max_trade_quantity')
        enabled = self.safe_bool(market, 'enable', True)
        marginEnabled = self.safe_bool(market, 'margin_enable', False)
        return {
            'id': id,
            'symbol': base + '/' + quote,
            'base': base,
            'quote': quote,
            'settle': None,
            'baseId': baseId,
            'quoteId': quoteId,
            'settleId': None,
            'type': 'spot',
            'spot': True,
            'margin': marginEnabled,
            'swap': False,
            'future': False,
            'option': False,
            'active': enabled,
            'contract': False,
            'linear': None,
            'inverse': None,
            'contractSize': None,
            'expiry': None,
            'expiryDatetime': None,
            'strike': None,
            'optionType': None,
            'precision': {
                'amount': basePrecision,
                'price': quotePrecision,
            },
            'limits': {
                'leverage': {
                    'min': None,
                    'max': None,
                },
                'amount': {
                    'min': self.parse_number(minAmount),
                    'max': self.parse_number(maxAmount),
                },
                'price': {
                    'min': None,
                    'max': None,
                },
                'cost': {
                    'min': None,
                    'max': None,
                },
            },
            'created': None,
            'info': market,
        }

    def fetch_tickers(self, symbols: Strings = None, params={}) -> Tickers:
        """
        fetches price tickers for multiple markets, statistical information calculated over the past 24 hours for each market
        :param str[]|None symbols: unified symbols of the markets to fetch the ticker for, all market tickers are returned if not assigned
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a dictionary of `ticker structures <https://docs.ccxt.com/#/?id=ticker-structure>`
        """
        self.load_markets()
        if symbols is not None:
            symbols = self.market_symbols(symbols)
        response = self.publicGetApiV1MarketSymbols(params)
        markets = self.safe_list(response, response)
        result = {}
        for i in range(0, len(markets)):
            marketData = markets[i]
            ticker = self.parse_ticker(marketData)
            symbol = ticker['symbol']
            result[symbol] = ticker
        return self.filter_by_array_tickers(result, 'symbol', symbols)

    def fetch_ticker(self, symbol: str, params={}) -> Ticker:
        """
        fetches a price ticker, a statistical calculation with the information calculated over the past 24 hours for a specific market
        :param str symbol: unified symbol of the market to fetch the ticker for
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a `ticker structure <https://docs.ccxt.com/#/?id=ticker-structure>`
        """
        self.load_markets()
        market = self.market(symbol)
        request = {
            'symbol': market['id'],
        }
        response = self.publicGetApiV1MarketSymbolsSymbol(request)
        return self.parse_ticker(response, market)

    def parse_ticker(self, ticker, market: Market = None) -> Ticker:
        # Raastin ticker response has the same structure data
        # We extract available price/volume information
        marketType = 'spot'
        marketId = self.safe_string(ticker, 'name')
        symbol = self.safe_symbol(marketId, market, None, marketType)
        # Since the exact ticker fields are not provided in the user's example,
        # we'll set up the basic structure. These may need adjustment based on actual API response.
        last = self.safe_float(ticker, 'last_price', 0)
        high = self.safe_float(ticker, '24h_high', 0)
        low = self.safe_float(ticker, '24h_low', 0)
        baseVolume = self.safe_float(ticker, '24h_volume', 0)
        quoteVolume = self.safe_float(ticker, '24h_quote_volume', 0)
        bid = self.safe_float(ticker, 'bid_price', 0)
        ask = self.safe_float(ticker, 'ask_price', 0)
        return self.safe_ticker({
            'symbol': symbol,
            'timestamp': None,
            'datetime': None,
            'high': high,
            'low': low,
            'bid': bid,
            'bidVolume': None,
            'ask': ask,
            'askVolume': None,
            'vwap': None,
            'open': None,
            'close': last,
            'last': last,
            'previousClose': None,
            'change': None,
            'percentage': None,
            'average': None,
            'baseVolume': baseVolume,
            'quoteVolume': quoteVolume,
            'info': ticker,
        }, market)

    def fetch_order_book(self, symbol: str, limit: Int = None, params={}) -> OrderBook:
        """
        fetches information on open orders with bid(buy) and ask(sell) prices, volumes and other data
        :param str symbol: unified symbol of the market to fetch the order book for
        :param int [limit]: max number of entries per orderbook to return
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: A dictionary of `order book structures <https://docs.ccxt.com/#/?id=order-book-structure>` indexed by market symbols
        """
        self.load_markets()
        market = self.market(symbol)
        request = {
            'symbol': market['id'],
        }
        response = self.publicGetApiV1MarketDepthSymbol(request)
        # Response structure:
        # {
        #   "last_trade": {"amount": "0.31", "price": "164311", "total": "50936"},
        #   "bids": [{"price": "164003", "amount": "19.99", "depth": "1", "total": "3278419"}],
        #   "asks": [{"price": "166000", "amount": "47.79", "depth": "2", "total": "7933140"}]
        # }
        timestamp = Date.now()
        return self.parse_order_book(response, symbol, timestamp, 'bids', 'asks', 'price', 'amount')

    def sign(self, path, api='public', method='GET', params={}, headers=None, body=None):
        url = self.urls['api']['public'] + '/' + path
        # Handle path parameters like {symbol}
        if path.find('{symbol}') >= 0:
            symbol = self.safe_string(params, 'symbol')
            if symbol is not None:
                url = url.replace('{symbol}', symbol)
                params = self.omit(params, 'symbol')
        query = self.omit(params, self.extract_params(path))
        # Add query parameters if any remain
        if query:
            url = url + '?' + self.urlencode(query)
        headers = {'Content-Type': 'application/json'}
        return {'url': url, 'method': method, 'body': body, 'headers': headers}
