# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.base.exchange import Exchange
from ccxt.abstract.wallgold import ImplicitAPI
from ccxt.base.types import Any, Market, Strings, Ticker, Tickers
from typing import List


class wallgold(Exchange, ImplicitAPI):

    def describe(self) -> Any:
        return self.deep_extend(super(wallgold, self).describe(), {
            'id': 'wallgold',
            'name': 'WallGold',
            'countries': ['IR'],
            'rateLimit': 1000,
            'version': '1',
            'certified': False,
            'pro': False,
            'has': {
                'CORS': None,
                'spot': False,
                'margin': False,
                'swap': False,
                'future': False,
                'option': False,
                'fetchMarkets': True,
                'fetchTicker': True,
                'fetchTickers': True,
                'otc': True,
            },
            'options': {
                'defaultType': 'otc',
            },
            'urls': {
                'api': {
                    'public': 'https://api.wallgold.ir',
                },
                'www': 'https://wallgold.ir',
                'doc': 'https://wallgold.ir',
            },
            'api': {
                'public': {
                    'get': {
                        'api/v1/price': 1,
                    },
                },
            },
        })

    def fetch_markets(self, params={}) -> List[Market]:
        response = self.fetch_price('buy', params)
        return [self.parse_market(response)]

    def fetch_price(self, side: str, params={}):
        return self.publicGetApiV1Price(self.extend({
            'side': side,
            'symbol': 'GLD_18C_750TMN',
        }, params))

    def parse_market(self, response) -> Market:
        return {
            'id': 'XAU18IRT',
            'symbol': 'XAU18/IRT',
            'base': 'XAU18',
            'quote': 'IRT',
            'settle': None,
            'baseId': 'XAU18',
            'quoteId': 'IRT',
            'settleId': None,
            'type': 'otc',
            'spot': False,
            'margin': False,
            'swap': False,
            'future': False,
            'option': False,
            'active': self.safe_bool(response, 'success', True),
            'contract': False,
            'linear': None,
            'inverse': None,
            'contractSize': None,
            'expiry': None,
            'expiryDatetime': None,
            'strike': None,
            'optionType': None,
            'precision': {
                'amount': None,
                'price': None,
            },
            'limits': {
                'leverage': {'min': None, 'max': None},
                'amount': {'min': None, 'max': None},
                'price': {'min': None, 'max': None},
                'cost': {'min': None, 'max': None},
            },
            'created': None,
            'info': response,
        }

    def fetch_ticker(self, symbol: str, params={}) -> Ticker:
        self.load_markets()
        market = self.market(symbol)
        buyResponse = self.fetch_price('buy', params)
        sellResponse = self.fetch_price('sell', params)
        return self.parse_ticker(buyResponse, market, sellResponse)

    def fetch_tickers(self, symbols: Strings = None, params={}) -> Tickers:
        self.load_markets()
        if symbols is not None:
            symbols = self.market_symbols(symbols)
        market = self.market('XAU18/IRT')
        buyResponse = self.fetch_price('buy', params)
        sellResponse = self.fetch_price('sell', params)
        ticker = self.parse_ticker(buyResponse, market, sellResponse)
        result = {}
        result[ticker['symbol']] = ticker
        return self.filter_by_array_tickers(result, 'symbol', symbols)

    def parse_ticker(self, buyResponse, market: Market = None, sellResponse=None) -> Ticker:
        buyResult = self.safe_dict(buyResponse, 'result', {})
        sellResult = self.safe_dict(sellResponse, 'result', buyResult)
        bid = self.safe_number(buyResult, 'price')
        ask = self.safe_number(sellResult, 'price')
        currentTime = self.safe_string(buyResult, 'currentTime')
        timestamp = self.parse8601(currentTime) if currentTime else None
        return self.safe_ticker({
            'symbol': market['symbol'],
            'timestamp': timestamp,
            'datetime': None,
            'high': None,
            'low': None,
            'bid': bid,
            'bidVolume': None,
            'ask': ask,
            'askVolume': None,
            'vwap': None,
            'open': None,
            'close': ask,
            'last': ask,
            'previousClose': None,
            'change': None,
            'percentage': None,
            'average': None,
            'baseVolume': None,
            'quoteVolume': None,
            'info': {'buy': buyResponse, 'sell': sellResponse},
        }, market)

    def sign(self, path, api='public', method='GET', params={}, headers=None, body=None):
        url = self.urls['api'][api] + '/' + self.implode_params(path, params)
        query = self.omit(params, self.extract_params(path))
        if query:
            url += '?' + self.urlencode(query)
        headers = {'Content-Type': 'application/json'}
        return {'url': url, 'method': method, 'body': body, 'headers': headers}
