// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class ariomex : Exchange
{
    public ariomex (object args = null): base(args) {}

    public async Task<object> publicGetV1PublicMarketsDetails (object parameters = null)
    {
        return await this.callAsync ("publicGetV1PublicMarketsDetails",parameters);
    }

}