// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class asacoine : Exchange
{
    public asacoine (object args = null): base(args) {}

    public async Task<object> publicGetV1MarketPairsPricing (object parameters = null)
    {
        return await this.callAsync ("publicGetV1MarketPairsPricing",parameters);
    }

    public async Task<object> publicGetV1MarketPairsCumulative (object parameters = null)
    {
        return await this.callAsync ("publicGetV1MarketPairsCumulative",parameters);
    }

}