// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class asretether : Exchange
{
    public asretether (object args = null): base(args) {}

    public async Task<object> publicGetV2Market (object parameters = null)
    {
        return await this.callAsync ("publicGetV2Market",parameters);
    }

}