// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class baazar : Exchange
{
    public baazar (object args = null): base(args) {}

    public async Task<object> publicGetLandingV1PriceDAILY30 (object parameters = null)
    {
        return await this.callAsync ("publicGetLandingV1PriceDAILY30",parameters);
    }

}