// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class bidarz : Exchange
{
    public bidarz (object args = null): base(args) {}

    public async Task<object> publicGetV1ArzDigitalSpotMarkets (object parameters = null)
    {
        return await this.callAsync ("publicGetV1ArzDigitalSpotMarkets",parameters);
    }

    public async Task<object> publicGetV1ArzDigitalOtcMarkets (object parameters = null)
    {
        return await this.callAsync ("publicGetV1ArzDigitalOtcMarkets",parameters);
    }

}