// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class bitwana : Exchange
{
    public bitwana (object args = null): base(args) {}

    public async Task<object> publicGetApi1Markets (object parameters = null)
    {
        return await this.callAsync ("publicGetApi1Markets",parameters);
    }

    public async Task<object> publicGetApi1MarketsId (object parameters = null)
    {
        return await this.callAsync ("publicGetApi1MarketsId",parameters);
    }

}