// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class digikalagold : Exchange
{
    public digikalagold (object args = null): base(args) {}

    public async Task<object> publicGetNonInventoryV1Prices (object parameters = null)
    {
        return await this.callAsync ("publicGetNonInventoryV1Prices",parameters);
    }

}