// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class goldcore : Exchange
{
    public goldcore (object args = null): base(args) {}

    public async Task<object> publicGetV1Price (object parameters = null)
    {
        return await this.callAsync ("publicGetV1Price",parameters);
    }

}