// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class goldis : Exchange
{
    public goldis (object args = null): base(args) {}

    public async Task<object> publicGetBackendApiV1PricingSpot (object parameters = null)
    {
        return await this.callAsync ("publicGetBackendApiV1PricingSpot",parameters);
    }

}