// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class iranexchange : Exchange
{
    public iranexchange (object args = null): base(args) {}

    public async Task<object> publicGetV1ClientListProduct (object parameters = null)
    {
        return await this.callAsync ("publicGetV1ClientListProduct",parameters);
    }

    public async Task<object> publicGetV1ClientGetBySymbol (object parameters = null)
    {
        return await this.callAsync ("publicGetV1ClientGetBySymbol",parameters);
    }

}