// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class melligold : Exchange
{
    public melligold (object args = null): base(args) {}

    public async Task<object> publicGetApiV1ExchangeBuySellPrice (object parameters = null)
    {
        return await this.callAsync ("publicGetApiV1ExchangeBuySellPrice",parameters);
    }

}