// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class poulyar : Exchange
{
    public poulyar (object args = null): base(args) {}

    public async Task<object> publicGetApiV2MarketData (object parameters = null)
    {
        return await this.callAsync ("publicGetApiV2MarketData",parameters);
    }

}