// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class raastin : Exchange
{
    public raastin (object args = null): base(args) {}

    public async Task<object> publicGetApiV1MarketSymbols (object parameters = null)
    {
        return await this.callAsync ("publicGetApiV1MarketSymbols",parameters);
    }

    public async Task<object> publicGetApiV1MarketSymbolsSymbol (object parameters = null)
    {
        return await this.callAsync ("publicGetApiV1MarketSymbolsSymbol",parameters);
    }

    public async Task<object> publicGetApiV1MarketDepthSymbol (object parameters = null)
    {
        return await this.callAsync ("publicGetApiV1MarketDepthSymbol",parameters);
    }

}