// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class technogold : Exchange
{
    public technogold (object args = null): base(args) {}

    public async Task<object> publicGetCustomerTradeablesOnlyPrice1 (object parameters = null)
    {
        return await this.callAsync ("publicGetCustomerTradeablesOnlyPrice1",parameters);
    }

}