// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class tehran_exchange : Exchange
{
    public tehran_exchange (object args = null): base(args) {}

    public async Task<object> publicGetOtcV1MarketPair (object parameters = null)
    {
        return await this.callAsync ("publicGetOtcV1MarketPair",parameters);
    }

    public async Task<object> publicGetOtcV1MarketOrderPairPrice (object parameters = null)
    {
        return await this.callAsync ("publicGetOtcV1MarketOrderPairPrice",parameters);
    }

}