// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class wallgold : Exchange
{
    public wallgold (object args = null): base(args) {}

    public async Task<object> publicGetApiV1Price (object parameters = null)
    {
        return await this.callAsync ("publicGetApiV1Price",parameters);
    }

}