// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class zarminex : Exchange
{
    public zarminex (object args = null): base(args) {}

    public async Task<object> publicGetFunctionUrl (object parameters = null)
    {
        return await this.callAsync ("publicGetFunctionUrl",parameters);
    }

}