// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

import { implicitReturnType } from '../base/types.js';
import { Exchange as _Exchange } from '../base/Exchange.js';

interface Exchange {
    spotGetApiPlatformSpotMarketV2Tickers (params?: {}): Promise<implicitReturnType>;
    spotGetApiPlatformSpotMarketV2SymbolTicker (params?: {}): Promise<implicitReturnType>;
    futuresGetApiV1ContractTicker (params?: {}): Promise<implicitReturnType>;
}
abstract class Exchange extends _Exchange {}

export default Exchange
