// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package ccxt

func (this *ariomex) PublicGetV1PublicMarketsDetails (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetV1PublicMarketsDetails", args...)
}
