// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package ccxt

func (this *asacoine) PublicGetV1MarketPairsPricing (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetV1MarketPairsPricing", args...)
}

func (this *asacoine) PublicGetV1MarketPairsCumulative (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetV1MarketPairsCumulative", args...)
}
