// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package ccxt

func (this *bidarz) PublicGetV1ArzDigitalSpotMarkets (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetV1ArzDigitalSpotMarkets", args...)
}

func (this *bidarz) PublicGetV1ArzDigitalOtcMarkets (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetV1ArzDigitalOtcMarkets", args...)
}
