// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package ccxt

func (this *changefa) PublicGetV1MarketPrices1100 (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetV1MarketPrices1100", args...)
}
