// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package ccxt

func (this *digikalagold) PublicGetNonInventoryV1Prices (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetNonInventoryV1Prices", args...)
}
