// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package ccxt

func (this *iranexchange) PublicGetV1ClientListProduct (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetV1ClientListProduct", args...)
}

func (this *iranexchange) PublicGetV1ClientGetBySymbol (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetV1ClientGetBySymbol", args...)
}
