// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package ccxt

func (this *ourbit) SpotGetApiPlatformSpotMarketV2Tickers (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("spotGetApiPlatformSpotMarketV2Tickers", args...)
}

func (this *ourbit) SpotGetApiPlatformSpotMarketV2SymbolTicker (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("spotGetApiPlatformSpotMarketV2SymbolTicker", args...)
}

func (this *ourbit) FuturesGetApiV1ContractTicker (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("futuresGetApiV1ContractTicker", args...)
}
