// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package ccxt

func (this *raastin) PublicGetApiV1MarketSymbols (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetApiV1MarketSymbols", args...)
}

func (this *raastin) PublicGetApiV1MarketSymbolsSymbol (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetApiV1MarketSymbolsSymbol", args...)
}

func (this *raastin) PublicGetApiV1MarketDepthSymbol (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetApiV1MarketDepthSymbol", args...)
}

func (this *raastin) PublicGetApiV1Market (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetApiV1Market", args...)
}
