// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package ccxt

func (this *tehran_exchange) PublicGetOtcV1MarketPair (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetOtcV1MarketPair", args...)
}

func (this *tehran_exchange) PublicGetOtcV1MarketOrderPairPrice (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetOtcV1MarketOrderPairPrice", args...)
}
