// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package ccxt

func (this *zarminex) PublicGetFunctionUrl (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetFunctionUrl", args...)
}
