<?php

namespace ccxt\async;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use ccxt\async\abstract\bidarz as Exchange;
use \React\Async;
use \React\Promise\PromiseInterface;

class bidarz extends Exchange {

    public function describe(): mixed {
        return $this->deep_extend(parent::describe(), array(
            'id' => 'bidarz',
            'name' => 'Bidarz',
            'countries' => array( 'IR' ),
            'rateLimit' => 1000,
            'version' => '1',
            'certified' => false,
            'pro' => false,
            'has' => array(
                'CORS' => null,
                'spot' => true,
                'margin' => false,
                'swap' => false,
                'future' => false,
                'option' => false,
                'addMargin' => false,
                'cancelAllOrders' => false,
                'cancelOrder' => false,
                'cancelOrders' => false,
                'createDepositAddress' => false,
                'createOrder' => false,
                'createStopLimitOrder' => false,
                'createStopMarketOrder' => false,
                'createStopOrder' => false,
                'editOrder' => false,
                'fetchBalance' => false,
                'fetchBorrowInterest' => false,
                'fetchBorrowRateHistories' => false,
                'fetchBorrowRateHistory' => false,
                'fetchClosedOrders' => false,
                'fetchCrossBorrowRate' => false,
                'fetchCrossBorrowRates' => false,
                'fetchCurrencies' => false,
                'fetchDepositAddress' => false,
                'fetchDeposits' => false,
                'fetchFundingHistory' => false,
                'fetchFundingRate' => false,
                'fetchFundingRateHistory' => false,
                'fetchFundingRates' => false,
                'fetchIndexOHLCV' => false,
                'fetchIsolatedBorrowRate' => false,
                'fetchIsolatedBorrowRates' => false,
                'fetchL2OrderBook' => false,
                'fetchL3OrderBook' => false,
                'fetchLedger' => false,
                'fetchLedgerEntry' => false,
                'fetchLeverageTiers' => false,
                'fetchMarkets' => true,
                'fetchMarkOHLCV' => false,
                'fetchMyTrades' => false,
                'fetchOHLCV' => false,
                'fetchOpenInterestHistory' => false,
                'fetchOpenOrders' => false,
                'fetchOrder' => false,
                'fetchOrderBook' => false,
                'fetchOrders' => false,
                'fetchOrderTrades' => 'emulated',
                'fetchPositions' => false,
                'fetchPremiumIndexOHLCV' => false,
                'fetchTicker' => true,
                'fetchTickers' => true,
                'fetchTime' => false,
                'fetchTrades' => false,
                'fetchTradingFee' => false,
                'fetchTradingFees' => false,
                'fetchWithdrawals' => false,
                'otc' => true,
                'setLeverage' => false,
                'setMarginMode' => false,
                'transfer' => false,
                'withdraw' => false,
            ),
            'comment' => 'This comment is optional',
            'urls' => array(
                'logo' => 'https://cdn.arz.digital/cr-odin/img/exchanges/bidarz/64x64.png',
                'api' => array(
                    'public' => 'https://new-api.bidarz.ir',
                ),
                'www' => 'https://bidarz.ir/',
                'doc' => array(
                    'https://bidarz.ir/',
                ),
            ),
            'api' => array(
                'public' => array(
                    'get' => array(
                        'v1/arz-digital/spot/markets' => 1,
                        'v1/arz-digital/otc/markets' => 1,
                    ),
                ),
            ),
            'commonCurrencies' => array(
                'IRR' => 'IRT',
            ),
            'fees' => array(
                'trading' => array(
                    'tierBased' => false,
                    'percentage' => true,
                    'maker' => $this->parse_number('0.001'),
                    'taker' => $this->parse_number('0.001'),
                ),
            ),
        ));
    }

    public function fetch_markets($params = array ()): PromiseInterface {
        return Async\async(function () use ($params) {
            /**
             * retrieves data on all markets for bidarz, including spot and OTC markets
             * @see https://new-api.bidarz.ir/v1/arz-digital/spot/markets
             * @see https://new-api.bidarz.ir/v1/arz-digital/otc/markets
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {array[]} an array of objects representing $market data
             */
            $result = array();
            $spotResponse = Async\await($this->publicGetV1ArzDigitalSpotMarkets ($params));
            $spotData = $this->safe_dict($spotResponse, 'data', array());
            $spotSymbols = $this->safe_dict($spotData, 'symbols', array());
            $spotIds = is_array($spotSymbols) ? array_keys($spotSymbols) : array();
            for ($i = 0; $i < count($spotIds); $i++) {
                $market = $this->parse_market($spotSymbols[$spotIds[$i]], 'spot');
                $result[] = $market;
            }
            $otcResponse = Async\await($this->publicGetV1ArzDigitalOtcMarkets ($params));
            $otcData = $this->safe_dict($otcResponse, 'data', array());
            $otcSymbols = $this->safe_dict($otcData, 'symbols', array());
            $otcIds = is_array($otcSymbols) ? array_keys($otcSymbols) : array();
            for ($i = 0; $i < count($otcIds); $i++) {
                $market = $this->parse_market($otcSymbols[$otcIds[$i]], 'otc');
                $result[] = $market;
            }
            return $result;
        }) ();
    }

    public function parse_market($market, $type = 'spot'): array {
        // spot
        // {
        //     $symbol => "BTCIRR",
        //     baseAsset => "BTC",
        //     quoteAsset => "IRR",
        //     price => "128005355600",
        //     minPrice24h => "0",
        //     maxPrice24h => "0",
        //     volume24h => "0",
        //     price24h => "0",
        //     marketIcon => null
        // }
        // otc
        // {
        //     $symbol => "BTCIRR",
        //     baseAsset => "BTC",
        //     quoteAsset => "IRR",
        //     buyPrice => "128325368989",
        //     sellPrice => "127685342211"
        // }
        $rawId = $this->safe_string($market, 'symbol');
        $baseId = $this->safe_string($market, 'baseAsset');
        $quoteId = $this->safe_string($market, 'quoteAsset');
        $base = $this->safe_currency_code($baseId);
        $quote = $this->safe_currency_code($quoteId);
        $baseId = strtolower($baseId);
        $quoteId = strtolower($quoteId);
        $isOtc = ($type === 'otc');
        $id = $rawId;
        $symbol = $base . '/' . $quote;
        if ($isOtc) {
            $id .= ':OTC';
            $symbol .= ':OTC';
        }
        return array(
            'id' => $id,
            'symbol' => $symbol,
            'base' => $base,
            'quote' => $quote,
            'settle' => null,
            'baseId' => $baseId,
            'quoteId' => $quoteId,
            'settleId' => null,
            'type' => $isOtc ? 'otc' : 'spot',
            'spot' => !$isOtc,
            'margin' => false,
            'swap' => false,
            'future' => false,
            'option' => false,
            'active' => true,
            'contract' => false,
            'linear' => null,
            'inverse' => null,
            'contractSize' => null,
            'expiry' => null,
            'expiryDatetime' => null,
            'strike' => null,
            'optionType' => null,
            'precision' => array(
                'amount' => null,
                'price' => null,
            ),
            'limits' => array(
                'leverage' => array(
                    'min' => null,
                    'max' => null,
                ),
                'amount' => array(
                    'min' => null,
                    'max' => null,
                ),
                'price' => array(
                    'min' => null,
                    'max' => null,
                ),
                'cost' => array(
                    'min' => null,
                    'max' => null,
                ),
            ),
            'created' => null,
            'info' => $market,
        );
    }

    public function fetch_tickers(?array $symbols = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbols, $params) {
            /**
             * fetches price tickers for multiple markets
             * @see https://new-api.bidarz.ir/v1/arz-digital/spot/markets
             * @see https://new-api.bidarz.ir/v1/arz-digital/otc/markets
             * @param {string[]|null} $symbols unified $symbols of the markets to fetch the $ticker for, all market tickers are returned if not assigned
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {array} a dictionary of ~@link https://docs.ccxt.com/#/?id=$ticker-structure $ticker structures~
             */
            Async\await($this->load_markets());
            if ($symbols !== null) {
                $symbols = $this->market_symbols($symbols);
            }
            $result = array();
            $spotResponse = Async\await($this->publicGetV1ArzDigitalSpotMarkets ($params));
            $spotData = $this->safe_dict($spotResponse, 'data', array());
            $spotSymbols = $this->safe_dict($spotData, 'symbols', array());
            $spotIds = is_array($spotSymbols) ? array_keys($spotSymbols) : array();
            for ($i = 0; $i < count($spotIds); $i++) {
                $ticker = $this->parse_ticker($spotSymbols[$spotIds[$i]], null, 'spot');
                $result[$ticker['symbol']] = $ticker;
            }
            $otcResponse = Async\await($this->publicGetV1ArzDigitalOtcMarkets ($params));
            $otcData = $this->safe_dict($otcResponse, 'data', array());
            $otcSymbols = $this->safe_dict($otcData, 'symbols', array());
            $otcIds = is_array($otcSymbols) ? array_keys($otcSymbols) : array();
            for ($i = 0; $i < count($otcIds); $i++) {
                $ticker = $this->parse_ticker($otcSymbols[$otcIds[$i]], null, 'otc');
                $result[$ticker['symbol']] = $ticker;
            }
            return $this->filter_by_array_tickers($result, 'symbol', $symbols);
        }) ();
    }

    public function fetch_ticker(string $symbol, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $params) {
            /**
             * fetches a price $ticker, defaulting duplicate raw spot/OTC symbols to the spot market
             * @see https://new-api.bidarz.ir/v1/arz-digital/spot/markets
             * @param {string} $symbol unified $symbol of the market to fetch the $ticker for
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {array} a ~@link https://docs.ccxt.com/#/?id=$ticker-structure $ticker structure~
             */
            $ticker = Async\await($this->fetch_tickers(array( $symbol ), $params));
            return $ticker[$symbol];
        }) ();
    }

    public function parse_ticker($ticker, ?array $market = null, $type = 'spot'): array {
        $isOtc = ($type === 'otc');
        $marketId = $this->safe_string($ticker, 'symbol');
        if ($isOtc) {
            $marketId .= ':OTC';
        }
        $symbol = $this->safe_symbol($marketId, $market);
        $last = $this->convert_price($this->safe_string($ticker, 'price'));
        $bid = $this->convert_price($this->safe_string($ticker, 'sellPrice'));
        $ask = $this->convert_price($this->safe_string($ticker, 'buyPrice'));
        $high = $this->convert_price($this->safe_string($ticker, 'maxPrice24h'));
        $low = $this->convert_price($this->safe_string($ticker, 'minPrice24h'));
        $open = $this->convert_price($this->safe_string($ticker, 'price24h'));
        $quoteVolume = $this->convert_price($this->safe_string($ticker, 'volume24h'));
        $close = $last;
        if ($isOtc) {
            $close = null;
        }
        return $this->safe_ticker(array(
            'symbol' => $symbol,
            'timestamp' => null,
            'datetime' => null,
            'high' => $high,
            'low' => $low,
            'bid' => $bid,
            'bidVolume' => null,
            'ask' => $ask,
            'askVolume' => null,
            'vwap' => null,
            'open' => $open,
            'close' => $close,
            'last' => $close,
            'previousClose' => null,
            'change' => null,
            'percentage' => null,
            'average' => null,
            'baseVolume' => null,
            'quoteVolume' => $quoteVolume,
            'info' => $ticker,
        ), $market);
    }

    public function convert_price($price) {
        $value = $this->parse_number($price);
        return ($value === null) ? null : $value / 10;
    }

    public function sign($path, $api = 'public', $method = 'GET', $params = array (), $headers = null, $body = null) {
        $query = $this->omit($params, $this->extract_params($path));
        $url = $this->urls['api'][$api] . '/' . $this->implode_params($path, $params);
        if ($query) {
            $url .= '?' . $this->urlencode($query);
        }
        $headers = array( 'Content-Type' => 'application/json' );
        return array( 'url' => $url, 'method' => $method, 'body' => $body, 'headers' => $headers );
    }
}
