<?php

namespace ccxt\async;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use ccxt\async\abstract\iranexchange as Exchange;
use \React\Async;
use \React\Promise\PromiseInterface;

class iranexchange extends Exchange {

    public function describe(): mixed {
        return $this->deep_extend(parent::describe(), array(
            'id' => 'iranexchange',
            'name' => 'Iran Exchange',
            'countries' => array( 'IR' ),
            'rateLimit' => 1000,
            'version' => '1',
            'certified' => false,
            'pro' => false,
            'timeout' => 30000, // milliseconds = seconds * 1000
            'has' => array(
                'CORS' => null,
                'spot' => false,
                'margin' => false,
                'swap' => false,
                'future' => false,
                'option' => false,
                'addMargin' => false,
                'cancelAllOrders' => false,
                'cancelOrder' => false,
                'cancelOrders' => false,
                'createDepositAddress' => false,
                'createOrder' => false,
                'createStopLimitOrder' => false,
                'createStopMarketOrder' => false,
                'createStopOrder' => false,
                'editOrder' => false,
                'fetchBalance' => false,
                'fetchBorrowInterest' => false,
                'fetchBorrowRateHistories' => false,
                'fetchBorrowRateHistory' => false,
                'fetchClosedOrders' => false,
                'fetchCrossBorrowRate' => false,
                'fetchCrossBorrowRates' => false,
                'fetchCurrencies' => false,
                'fetchDepositAddress' => false,
                'fetchDeposits' => false,
                'fetchFundingHistory' => false,
                'fetchFundingRate' => false,
                'fetchFundingRateHistory' => false,
                'fetchFundingRates' => false,
                'fetchIndexOHLCV' => false,
                'fetchIsolatedBorrowRate' => false,
                'fetchIsolatedBorrowRates' => false,
                'fetchL2OrderBook' => false,
                'fetchLedger' => false,
                'fetchLedgerEntry' => false,
                'fetchLeverageTiers' => false,
                'fetchMarkets' => true,
                'fetchMarkOHLCV' => false,
                'fetchMyTrades' => false,
                'fetchOHLCV' => false,
                'fetchOpenInterestHistory' => false,
                'fetchOpenOrders' => false,
                'fetchOrder' => false,
                'fetchOrderBook' => false,
                'fetchOrders' => false,
                'fetchOrderTrades' => 'emulated',
                'fetchPositions' => false,
                'fetchPremiumIndexOHLCV' => false,
                'fetchTicker' => true,
                'fetchTickers' => true,
                'fetchTime' => false,
                'fetchTrades' => false,
                'fetchTradingFee' => false,
                'fetchTradingFees' => false,
                'fetchWithdrawals' => false,
                'otc' => true,
                'setLeverage' => false,
                'setMarginMode' => false,
                'transfer' => false,
                'withdraw' => false,
            ),
            'comment' => 'This comment is optional',
            'urls' => array(
                'logo' => 'https://cdn.arz.digital/cr-odin/img/exchanges/iran-exchange/64x64.png',
                'api' => array(
                    'public' => 'https://api.iranexchange.com/api/public/modules/crypto',
                ),
                'www' => 'https://iranexchange.com/',
                'doc' => array(
                    'https://iranexchange.com/',
                ),
            ),
            'api' => array(
                'public' => array(
                    'get' => array(
                        'v1/client/listProduct' => 1,
                        'v1/client/getBySymbol' => 1,
                    ),
                ),
            ),
            'fees' => array(
                'trading' => array(
                    'tierBased' => false,
                    'percentage' => true,
                    'maker' => $this->parse_number('0.001'),
                    'taker' => $this->parse_number('0.001'),
                ),
            ),
        ));
    }

    public function fetch_markets($params = array ()): PromiseInterface {
        return Async\async(function () use ($params) {
            /**
             * retrieves data on all $markets for iranexchange
             * @see https://iranexchange.co/
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {array[]} an array of objects representing $market data
             */
            $response = Async\await($this->publicGetV1ClientListProduct ());
            $markets = $this->safe_list($response, 'data');
            $result = array();
            for ($i = 0; $i < count($markets); $i++) {
                $market = $this->parse_market($markets[$i]);
                $result[] = $market;
            }
            return $result;
        }) ();
    }

    public function parse_market($market): array {
        // {
        // _id => "60b08a57b202353abb592032",
        // name => "Bitcoin",
        // fa_name => "بیت کوین",
        // symbol => "BTC",
        // slug => "bitcoin",
        // is_sell_to_customer_active => 1,
        // is_fast_sell_to_customer_active => 1,
        // is_buy_from_customer_active => 1,
        // logo => "https://iranexchange.com/strapi/media/BTC_78d99b9d12.png",
        // dollar_price => 89240.18,
        // sell_to_iranicard_currency_price => 1234526,
        // buy_from_iranicard_currency_price => 1239474,
        // fast_sell_to_iranicard_currency_price => 1234526,
        // buy_from_iranicard_network_list => [
        // {
        // network => "BTC",
        // name => "Bitcoin",
        // addressRegex => "^[13][a-km-zA-HJ-NP-Z1-9]array(25,34)$|^[(bc1q)|(bc1p)][0-9A-Za-z]array(37,62)$",
        // coin => "BTC",
        // withdrawEnable => true,
        // depositEnable => true,
        // withdrawMin => "0.000100000",
        // withdrawMax => null,
        // withdrawFee => "0.000100000",
        // sameAddress => false,
        // memoRegex => null,
        // tradeEnable => true
        // }
        // ],
        // sell_to_iranicard_network_list => [
        // array(
        // network => "BTC",
        // name => "Bitcoin",
        // addressRegex => "^[13][a-km-zA-HJ-NP-Z1-9]array(25,34)$|^[(bc1q)|(bc1p)][0-9A-Za-z]array(37,62)$",
        // coin => "BTC",
        // withdrawEnable => true,
        // depositEnable => true,
        // withdrawMin => "0.000100000",
        // withdrawMax => null,
        // withdrawFee => "0.000100000",
        // sameAddress => false,
        // memoRegex => null,
        // tradeEnable => true
        // }
        // ],
        // is_price_maker_active => 1,
        // quotation => array(
        // maxPrice => "90199.99",
        // minPrice => "88925",
        // dailyChangePercent => "-0.26"
        // ),
        // dailyChangePercent => -0.26,
        // order => 0,
        // stock_status => "in_stock",
        // stock_label => null,
        // stock_description => null
        // ),
        $id = $this->safe_string($market, 'symbol') . '_' . 'IRT';
        $baseId = $this->safe_string($market, 'symbol');
        $quoteId = 'IRT';
        $base = $this->safe_currency_code($baseId);
        $quote = $this->safe_currency_code($quoteId);
        $baseId = strtolower($baseId);
        $quoteId = strtolower($quoteId);
        return array(
            'id' => $id,
            'symbol' => $base . '/' . $quote,
            'base' => $base,
            'quote' => $quote,
            'settle' => null,
            'baseId' => $baseId,
            'quoteId' => $quoteId,
            'settleId' => null,
            'type' => 'otc',
            'spot' => false,
            'margin' => false,
            'swap' => false,
            'future' => false,
            'option' => false,
            'active' => true,
            'contract' => false,
            'linear' => null,
            'inverse' => null,
            'contractSize' => null,
            'expiry' => null,
            'expiryDatetime' => null,
            'strike' => null,
            'optionType' => null,
            'precision' => array(
                'amount' => null,
                'price' => null,
            ),
            'limits' => array(
                'leverage' => array(
                    'min' => null,
                    'max' => null,
                ),
                'amount' => array(
                    'min' => null,
                    'max' => null,
                ),
                'price' => array(
                    'min' => null,
                    'max' => null,
                ),
                'cost' => array(
                    'min' => null,
                    'max' => null,
                ),
            ),
            'created' => null,
            'info' => $market,
        );
    }

    public function fetch_tickers(?array $symbols = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbols, $params) {
            /**
             * fetches price tickers for multiple $markets, statistical information calculated over the past 24 hours for each market
             * @see https://iranexchange.co/
             * @param {string[]|null} $symbols unified $symbols of the $markets to fetch the $ticker for, all market tickers are returned if not assigned
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {array} a dictionary of ~@link https://docs.ccxt.com/#/?id=$ticker-structure $ticker structures~
             */
            Async\await($this->load_markets());
            if ($symbols !== null) {
                $symbols = $this->market_symbols($symbols);
            }
            $response = Async\await($this->publicGetV1ClientListProduct ());
            $markets = $this->safe_list($response, 'data');
            $result = array();
            for ($i = 0; $i < count($markets); $i++) {
                $ticker = $this->parse_ticker($markets[$i]);
                $symbol = $ticker['symbol'];
                $result[$symbol] = $ticker;
            }
            return $this->filter_by_array_tickers($result, 'symbol', $symbols);
        }) ();
    }

    public function fetch_ticker(string $symbol, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $params) {
            /**
             * fetches a price $ticker, a statistical calculation with the information calculated over the past 24 hours for a specific $market
             * @see https://iranexchange.co/
             * @param {string} $symbol unified $symbol of the $market to fetch the $ticker for
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {array} a ~@link https://docs.ccxt.com/#/?id=$ticker-structure $ticker structure~
             */
            Async\await($this->load_markets());
            $market = $this->market($symbol);
            $request = array(
                'id' => $market['base'],
            );
            $response = Async\await($this->publicGetV1ClientGetBySymbol ($request));
            $marketData = $this->safe_dict($response, 'data');
            $ticker = $this->parse_ticker($marketData);
            return $ticker;
        }) ();
    }

    public function parse_ticker($ticker, ?array $market = null): array {
        // {
        // _id => "60b08a57b202353abb592032",
        // name => "Bitcoin",
        // fa_name => "بیت کوین",
        // $symbol => "BTC",
        // slug => "bitcoin",
        // is_sell_to_customer_active => 1,
        // is_fast_sell_to_customer_active => 1,
        // is_buy_from_customer_active => 1,
        // logo => "https://iranexchange.com/strapi/media/BTC_78d99b9d12.png",
        // dollar_price => 89240.18,
        // sell_to_iranicard_currency_price => 1234526,
        // buy_from_iranicard_currency_price => 1239474,
        // fast_sell_to_iranicard_currency_price => 1234526,
        // buy_from_iranicard_network_list => [
        // {
        // network => "BTC",
        // name => "Bitcoin",
        // addressRegex => "^[13][a-km-zA-HJ-NP-Z1-9]array(25,34)$|^[(bc1q)|(bc1p)][0-9A-Za-z]array(37,62)$",
        // coin => "BTC",
        // withdrawEnable => true,
        // depositEnable => true,
        // withdrawMin => "0.000100000",
        // withdrawMax => null,
        // withdrawFee => "0.000100000",
        // sameAddress => false,
        // memoRegex => null,
        // tradeEnable => true
        // }
        // ],
        // sell_to_iranicard_network_list => [
        // {
        // network => "BTC",
        // name => "Bitcoin",
        // addressRegex => "^[13][a-km-zA-HJ-NP-Z1-9]array(25,34)$|^[(bc1q)|(bc1p)][0-9A-Za-z]array(37,62)$",
        // coin => "BTC",
        // withdrawEnable => true,
        // depositEnable => true,
        // withdrawMin => "0.000100000",
        // withdrawMax => null,
        // withdrawFee => "0.000100000",
        // sameAddress => false,
        // memoRegex => null,
        // tradeEnable => true
        // }
        // ],
        // is_price_maker_active => 1,
        // $quotation => array(
        // maxPrice => "90199.99",
        // minPrice => "88925",
        // dailyChangePercent => "-0.26"
        // ),
        // dailyChangePercent => -0.26,
        // order => 0,
        // stock_status => "in_stock",
        // stock_label => null,
        // stock_description => null
        // }
        $marketType = 'otc';
        $marketId = $this->safe_string($ticker, 'symbol') . '_' . 'IRT';
        $symbol = $this->safe_symbol($marketId, $market, null, $marketType);
        $quotation = $this->safe_value($ticker, 'quotation', array());
        $high = $this->safe_float($quotation, 'maxPrice', 0);
        $low = $this->safe_float($quotation, 'minPrice', 0);
        $bid = $this->safe_float($ticker, 'sell_to_iranicard_currency_price', 0);
        $ask = $this->safe_float($ticker, 'buy_from_iranicard_currency_price', 0);
        $last = $this->safe_float($ticker, 'sell_to_iranicard_currency_price', 0);
        $change = $this->safe_float($quotation, 'dailyChangePercent', 0);
        return $this->safe_ticker(array(
            'symbol' => $symbol,
            'timestamp' => null,
            'datetime' => null,
            'high' => $high,
            'low' => $low,
            'bid' => $bid,
            'bidVolume' => null,
            'ask' => $ask,
            'askVolume' => null,
            'vwap' => null,
            'open' => $last,
            'close' => $last,
            'last' => $last,
            'previousClose' => null,
            'change' => $change,
            'percentage' => $change,
            'average' => null,
            'baseVolume' => null,
            'quoteVolume' => null,
            'info' => $ticker,
        ), $market);
    }

    public function sign($path, $api = 'public', $method = 'GET', $params = array (), $headers = null, $body = null) {
        $query = $this->omit($params, $this->extract_params($path));
        $url = $this->urls['api']['public'] . '/' . $path . '?' . $this->urlencode($query);
        $pair_id = $this->safe_string($params, 'id');
        if ($pair_id !== null) {
            $url = $this->urls['api']['public'] . '/' . $path . '/' . $pair_id;
        }
        $headers = array( 'Content-Type' => 'application/json' );
        return array( 'url' => $url, 'method' => $method, 'body' => $body, 'headers' => $headers );
    }
}
