<?php

namespace ccxt\async;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use ccxt\async\abstract\talaavan as Exchange;
use \React\Async;
use \React\Promise\PromiseInterface;

class talaavan extends Exchange {

    public function describe(): mixed {
        return $this->deep_extend(parent::describe(), array(
            'id' => 'talaavan',
            'name' => 'Talaavan',
            'countries' => array( 'IR' ),
            'rateLimit' => 1000,
            'version' => 'v1',
            'certified' => false,
            'pro' => false,
            'has' => array(
                'CORS' => null,
                'spot' => false,
                'margin' => false,
                'swap' => false,
                'future' => false,
                'option' => false,
                'fetchMarkets' => true,
                'fetchTicker' => true,
                'fetchTickers' => true,
                'otc' => true,
            ),
            'options' => array(
                'defaultType' => 'otc',
            ),
            'urls' => array(
                'api' => array(
                    'public' => 'https://goldcore.talaavan.com',
                ),
                'www' => 'https://goldcore.talaavan.com',
                'doc' => 'https://goldcore.talaavan.com/v1/price',
            ),
            'api' => array(
                'public' => array(
                    'get' => array(
                        'v1/price' => 1,
                    ),
                ),
            ),
        ));
    }

    public function fetch_markets($params = array ()): PromiseInterface {
        return Async\async(function () use ($params) {
            $response = Async\await($this->publicGetV1Price ($params));
            return array( $this->parse_market($response) );
        }) ();
    }

    public function parse_market($response): array {
        return array(
            'id' => 'XAU18IRT',
            'symbol' => 'XAU18/IRT',
            'base' => 'XAU18',
            'quote' => 'IRT',
            'settle' => null,
            'baseId' => 'XAU18',
            'quoteId' => 'IRT',
            'settleId' => null,
            'type' => 'otc',
            'spot' => false,
            'margin' => false,
            'swap' => false,
            'future' => false,
            'option' => false,
            'active' => $this->safe_bool($response, 'status', false),
            'contract' => false,
            'linear' => null,
            'inverse' => null,
            'contractSize' => null,
            'expiry' => null,
            'expiryDatetime' => null,
            'strike' => null,
            'optionType' => null,
            'precision' => array(
                'amount' => null,
                'price' => null,
            ),
            'limits' => array(
                'leverage' => array( 'min' => null, 'max' => null ),
                'amount' => array( 'min' => null, 'max' => null ),
                'price' => array( 'min' => null, 'max' => null ),
                'cost' => array( 'min' => null, 'max' => null ),
            ),
            'created' => null,
            'info' => $response,
        );
    }

    public function fetch_ticker(string $symbol, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $params) {
            Async\await($this->load_markets());
            $market = $this->market($symbol);
            $response = Async\await($this->publicGetV1Price ($params));
            return $this->parse_ticker($response, $market);
        }) ();
    }

    public function fetch_tickers(?array $symbols = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbols, $params) {
            Async\await($this->load_markets());
            if ($symbols !== null) {
                $symbols = $this->market_symbols($symbols);
            }
            $response = Async\await($this->publicGetV1Price ($params));
            $market = $this->market('XAU18/IRT');
            $ticker = $this->parse_ticker($response, $market);
            $result = array();
            $result[$ticker['symbol']] = $ticker;
            return $this->filter_by_array_tickers($result, 'symbol', $symbols);
        }) ();
    }

    public function parse_ticker($response, ?array $market = null): array {
        $data = $this->safe_dict($response, 'data', array());
        $price = $this->safe_number($data, 'rate');
        if ($price !== null) {
            $price = $price / 10;
        }
        return $this->safe_ticker(array(
            'symbol' => $market['symbol'],
            'timestamp' => $this->parse8601($this->safe_string($data, 'date')),
            'datetime' => null,
            'high' => null,
            'low' => null,
            'bid' => $price,
            'bidVolume' => null,
            'ask' => $price,
            'askVolume' => null,
            'vwap' => null,
            'open' => null,
            'close' => $price,
            'last' => $price,
            'previousClose' => null,
            'change' => null,
            'percentage' => null,
            'average' => null,
            'baseVolume' => null,
            'quoteVolume' => null,
            'info' => $data,
        ), $market);
    }

    public function sign($path, $api = 'public', $method = 'GET', $params = array (), $headers = null, $body = null) {
        $url = $this->urls['api'][$api] . '/' . $this->implode_params($path, $params);
        $query = $this->omit($params, $this->extract_params($path));
        if ($query) {
            $url .= '?' . $this->urlencode($query);
        }
        $headers = array( 'Accept' => 'application/json' );
        return array( 'url' => $url, 'method' => $method, 'body' => $body, 'headers' => $headers );
    }
}
