<?php

namespace ccxt\async;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use ccxt\async\abstract\wallgold as Exchange;
use \React\Async;
use \React\Promise\PromiseInterface;

class wallgold extends Exchange {

    public function describe(): mixed {
        return $this->deep_extend(parent::describe(), array(
            'id' => 'wallgold',
            'name' => 'WallGold',
            'countries' => array( 'IR' ),
            'rateLimit' => 1000,
            'version' => '1',
            'certified' => false,
            'pro' => false,
            'has' => array(
                'CORS' => null,
                'spot' => false,
                'margin' => false,
                'swap' => false,
                'future' => false,
                'option' => false,
                'fetchMarkets' => true,
                'fetchTicker' => true,
                'fetchTickers' => true,
                'otc' => true,
            ),
            'options' => array(
                'defaultType' => 'otc',
            ),
            'urls' => array(
                'api' => array(
                    'public' => 'https://api.wallgold.ir',
                ),
                'www' => 'https://wallgold.ir',
                'doc' => 'https://wallgold.ir',
            ),
            'api' => array(
                'public' => array(
                    'get' => array(
                        'api/v1/price' => 1,
                    ),
                ),
            ),
        ));
    }

    public function fetch_markets($params = array ()): PromiseInterface {
        return Async\async(function () use ($params) {
            $response = Async\await($this->fetch_price('buy', $params));
            return array( $this->parse_market($response) );
        }) ();
    }

    public function fetch_price(string $side, $params = array ()) {
        return $this->publicGetApiV1Price ($this->extend(array(
            'side' => $side,
            'symbol' => 'GLD_18C_750TMN',
        ), $params));
    }

    public function parse_market($response): array {
        return array(
            'id' => 'XAU18IRT',
            'symbol' => 'XAU18/IRT',
            'base' => 'XAU18',
            'quote' => 'IRT',
            'settle' => null,
            'baseId' => 'XAU18',
            'quoteId' => 'IRT',
            'settleId' => null,
            'type' => 'otc',
            'spot' => false,
            'margin' => false,
            'swap' => false,
            'future' => false,
            'option' => false,
            'active' => $this->safe_bool($response, 'success', true),
            'contract' => false,
            'linear' => null,
            'inverse' => null,
            'contractSize' => null,
            'expiry' => null,
            'expiryDatetime' => null,
            'strike' => null,
            'optionType' => null,
            'precision' => array(
                'amount' => null,
                'price' => null,
            ),
            'limits' => array(
                'leverage' => array( 'min' => null, 'max' => null ),
                'amount' => array( 'min' => null, 'max' => null ),
                'price' => array( 'min' => null, 'max' => null ),
                'cost' => array( 'min' => null, 'max' => null ),
            ),
            'created' => null,
            'info' => $response,
        );
    }

    public function fetch_ticker(string $symbol, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $params) {
            Async\await($this->load_markets());
            $market = $this->market($symbol);
            $buyResponse = Async\await($this->fetch_price('buy', $params));
            $sellResponse = Async\await($this->fetch_price('sell', $params));
            return $this->parse_ticker($buyResponse, $market, $sellResponse);
        }) ();
    }

    public function fetch_tickers(?array $symbols = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbols, $params) {
            Async\await($this->load_markets());
            if ($symbols !== null) {
                $symbols = $this->market_symbols($symbols);
            }
            $market = $this->market('XAU18/IRT');
            $buyResponse = Async\await($this->fetch_price('buy', $params));
            $sellResponse = Async\await($this->fetch_price('sell', $params));
            $ticker = $this->parse_ticker($buyResponse, $market, $sellResponse);
            $result = array();
            $result[$ticker['symbol']] = $ticker;
            return $this->filter_by_array_tickers($result, 'symbol', $symbols);
        }) ();
    }

    public function parse_ticker($buyResponse, ?array $market = null, $sellResponse = null): array {
        $buyResult = $this->safe_dict($buyResponse, 'result', array());
        $sellResult = $this->safe_dict($sellResponse, 'result', $buyResult);
        $bid = $this->safe_number($buyResult, 'price');
        $ask = $this->safe_number($sellResult, 'price');
        $currentTime = $this->safe_string($buyResult, 'currentTime');
        $timestamp = $currentTime ? $this->parse8601($currentTime) : null;
        return $this->safe_ticker(array(
            'symbol' => $market['symbol'],
            'timestamp' => $timestamp,
            'datetime' => null,
            'high' => null,
            'low' => null,
            'bid' => $bid,
            'bidVolume' => null,
            'ask' => $ask,
            'askVolume' => null,
            'vwap' => null,
            'open' => null,
            'close' => $ask,
            'last' => $ask,
            'previousClose' => null,
            'change' => null,
            'percentage' => null,
            'average' => null,
            'baseVolume' => null,
            'quoteVolume' => null,
            'info' => array( 'buy' => $buyResponse, 'sell' => $sellResponse ),
        ), $market);
    }

    public function sign($path, $api = 'public', $method = 'GET', $params = array (), $headers = null, $body = null) {
        $url = $this->urls['api'][$api] . '/' . $this->implode_params($path, $params);
        $query = $this->omit($params, $this->extract_params($path));
        if ($query) {
            $url .= '?' . $this->urlencode($query);
        }
        $headers = array( 'Content-Type' => 'application/json' );
        return array( 'url' => $url, 'method' => $method, 'body' => $body, 'headers' => $headers );
    }
}
