<?php

namespace ccxt\async;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use ccxt\async\abstract\zarpin as Exchange;
use \React\Async;
use \React\Promise\PromiseInterface;

class zarpin extends Exchange {

    public function describe(): mixed {
        return $this->deep_extend(parent::describe(), array(
            'id' => 'zarpin',
            'name' => 'Zarpin',
            'countries' => array( 'IR' ),
            'rateLimit' => 1000,
            'version' => 'v1',
            'certified' => false,
            'pro' => false,
            'has' => array(
                'CORS' => null,
                'spot' => false,
                'margin' => false,
                'swap' => false,
                'future' => false,
                'option' => false,
                'fetchMarkets' => true,
                'fetchTicker' => true,
                'fetchTickers' => true,
                'otc' => true,
            ),
            'options' => array(
                'defaultType' => 'otc',
            ),
            'urls' => array(
                'api' => array(
                    'public' => 'https://api-khazaneh.zarpin.com',
                ),
                'www' => 'https://zarpin.com',
                'doc' => 'https://api-khazaneh.zarpin.com/v1/prc/prices',
            ),
            'api' => array(
                'public' => array(
                    'get' => array(
                        'v1/prc/prices' => 1,
                    ),
                ),
            ),
        ));
    }

    public function fetch_markets($params = array ()): PromiseInterface {
        return Async\async(function () use ($params) {
            $response = Async\await($this->publicGetV1PrcPrices ($params));
            return $this->parse_markets($response);
        }) ();
    }

    public function parse_markets($response): array {
        $prices = array();
        if (gettype($response) === 'array' && array_keys($response) === array_keys(array_keys($response))) {
            $prices = $response;
        }
        $result = array();
        for ($i = 0; $i < count($prices); $i++) {
            $price = $prices[$i];
            $code = $this->safe_string($price, 'code');
            if ($code === 'GOLD_IRT' || $code === 'SILVER_IRT') {
                $result[] = $this->parse_market($price);
            }
        }
        return $result;
    }

    public function parse_market($market): array {
        $code = $this->safe_string($market, 'code');
        $base = 'XAG-1G';
        if ($code === 'GOLD_IRT') {
            $base = 'XAU18';
        }
        $quote = 'IRT';
        return array(
            'id' => $code,
            'symbol' => $base . '/' . $quote,
            'base' => $base,
            'quote' => $quote,
            'settle' => null,
            'baseId' => $code,
            'quoteId' => $quote,
            'settleId' => null,
            'type' => 'otc',
            'spot' => false,
            'margin' => false,
            'swap' => false,
            'future' => false,
            'option' => false,
            'active' => $this->safe_number($market, 'price') !== null,
            'contract' => false,
            'linear' => null,
            'inverse' => null,
            'contractSize' => null,
            'expiry' => null,
            'expiryDatetime' => null,
            'strike' => null,
            'optionType' => null,
            'precision' => array(
                'amount' => null,
                'price' => null,
            ),
            'limits' => array(
                'leverage' => array( 'min' => null, 'max' => null ),
                'amount' => array( 'min' => null, 'max' => null ),
                'price' => array( 'min' => null, 'max' => null ),
                'cost' => array( 'min' => null, 'max' => null ),
            ),
            'created' => null,
            'info' => $market,
        );
    }

    public function fetch_ticker(string $symbol, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $params) {
            Async\await($this->load_markets());
            $market = $this->market($symbol);
            $response = Async\await($this->publicGetV1PrcPrices ($params));
            return $this->parse_ticker($response, $market);
        }) ();
    }

    public function fetch_tickers(?array $symbols = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbols, $params) {
            Async\await($this->load_markets());
            if ($symbols !== null) {
                $symbols = $this->market_symbols($symbols);
            }
            $response = Async\await($this->publicGetV1PrcPrices ($params));
            $markets = $this->parse_markets($response);
            $result = array();
            for ($i = 0; $i < count($markets); $i++) {
                $ticker = $this->parse_ticker($response, $markets[$i]);
                $result[$ticker['symbol']] = $ticker;
            }
            return $this->filter_by_array_tickers($result, 'symbol', $symbols);
        }) ();
    }

    public function parse_ticker($response, ?array $market = null): array {
        $prices = array();
        if (gettype($response) === 'array' && array_keys($response) === array_keys(array_keys($response))) {
            $prices = $response;
        }
        $price = array();
        for ($i = 0; $i < count($prices); $i++) {
            $entry = $prices[$i];
            if ($this->safe_string($entry, 'code') === $market['baseId']) {
                $price = $entry;
                break;
            }
        }
        return $this->safe_ticker(array(
            'symbol' => $market['symbol'],
            'timestamp' => null,
            'datetime' => null,
            'high' => $this->safe_number($price, 'max_24h_price'),
            'low' => $this->safe_number($price, 'min_24h_price'),
            'bid' => $this->safe_number($price, 'price'),
            'bidVolume' => null,
            'ask' => $this->safe_number($price, 'price'),
            'askVolume' => null,
            'vwap' => null,
            'open' => $this->safe_number($price, 'price_at_in_last_24h'),
            'close' => $this->safe_number($price, 'price'),
            'last' => $this->safe_number($price, 'price'),
            'previousClose' => $this->safe_number($price, 'price_at_in_last_24h'),
            'change' => null,
            'percentage' => $this->safe_number($price, 'price_change_24h'),
            'average' => null,
            'baseVolume' => null,
            'quoteVolume' => null,
            'info' => $price,
        ), $market);
    }

    public function sign($path, $api = 'public', $method = 'GET', $params = array (), $headers = null, $body = null) {
        $url = $this->urls['api'][$api] . '/' . $this->implode_params($path, $params);
        $query = $this->omit($params, $this->extract_params($path));
        if ($query) {
            $url .= '?' . $this->urlencode($query);
        }
        $headers = array( 'Accept' => 'application/json' );
        return array( 'url' => $url, 'method' => $method, 'body' => $body, 'headers' => $headers );
    }
}
