# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.async_support.base.exchange import Exchange
from ccxt.abstract.ariomex import ImplicitAPI
from ccxt.base.types import Any, Market, Strings, Ticker, Tickers
from typing import List


class ariomex(Exchange, ImplicitAPI):

    def describe(self) -> Any:
        return self.deep_extend(super(ariomex, self).describe(), {
            'id': 'ariomex',
            'name': 'Ariomex',
            'countries': ['IR'],
            'rateLimit': 1000,
            'version': 'v1',
            'certified': False,
            'pro': False,
            'has': {
                'CORS': None,
                'spot': True,
                'margin': False,
                'swap': False,
                'future': False,
                'option': False,
                'fetchMarkets': True,
                'fetchTicker': True,
                'fetchTickers': True,
                'fetchTime': True,
            },
            'urls': {
                'api': {
                    'public': 'https://api.ariomex.ir',
                },
                'www': 'https://ariomex.ir',
                'doc': 'https://api.ariomex.ir/v1/public/markets_details',
            },
            'api': {
                'public': {
                    'get': {
                        'v1/public/markets_details': 1,
                    },
                },
            },
        })

    async def fetch_markets(self, params={}) -> List[Market]:
        """
        retrieves data on all markets for ariomex
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict[]: an array of objects representing market data
        """
        response = await self.publicGetV1PublicMarketsDetails(params)
        markets = self.safe_list(response, 'result')
        result = []
        for i in range(0, len(markets)):
            result.append(self.parse_market(markets[i]))
        return result

    def parse_market(self, market) -> Market:
        # {
        #     'symbol': 'btcusdt',
        #     'base': 'btc',
        #     'quote': 'usdt',
        #     'spot_enabled': 'true',
        #     'base_market_precision': '5',
        #     'quote_market_precision': '2',
        #     'base_coin_precision': '8',
        #     'quote_coin_precision': '8',
        # }
        id = self.safe_string(market, 'symbol')
        baseId = self.safe_string(market, 'base')
        quoteId = self.safe_string(market, 'quote')
        base = self.safe_currency_code(baseId)
        quote = self.safe_currency_code(quoteId)
        return {
            'id': id,
            'symbol': base + '/' + quote,
            'base': base,
            'quote': quote,
            'settle': None,
            'baseId': baseId,
            'quoteId': quoteId,
            'settleId': None,
            'type': 'spot',
            'spot': True,
            'margin': False,
            'swap': False,
            'future': False,
            'option': False,
            'active': self.safe_bool(market, 'spot_enabled'),
            'contract': False,
            'linear': None,
            'inverse': None,
            'contractSize': None,
            'expiry': None,
            'expiryDatetime': None,
            'strike': None,
            'optionType': None,
            'precision': {
                'amount': self.safe_number(market, 'base_market_precision'),
                'price': self.safe_number(market, 'quote_market_precision'),
            },
            'limits': {
                'leverage': {'min': None, 'max': None},
                'amount': {'min': None, 'max': None},
                'price': {'min': None, 'max': None},
                'cost': {'min': None, 'max': None},
            },
            'created': self.safe_integer(market, 'time_listed'),
            'info': market,
        }

    async def fetch_time(self, params={}) -> float:
        response = await self.publicGetV1PublicMarketsDetails(params)
        return self.safe_integer(response, 'serverTime')

    async def fetch_ticker(self, symbol: str, params={}) -> Ticker:
        """
        fetches a price ticker for a market
        :param str symbol: unified symbol of the market to fetch the ticker for
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a `ticker structure <https://docs.ccxt.com/#/?id=ticker-structure>`
        """
        tickers = await self.fetch_tickers([symbol], params)
        return tickers[symbol]

    async def fetch_tickers(self, symbols: Strings = None, params={}) -> Tickers:
        """
        fetches price tickers for all markets
        :param str[]|None symbols: unified symbols of the markets to fetch the tickers for
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a dictionary of `ticker structures <https://docs.ccxt.com/#/?id=ticker-structure>`
        """
        await self.load_markets()
        if symbols is not None:
            symbols = self.market_symbols(symbols)
        response = await self.publicGetV1PublicMarketsDetails(params)
        timestamp = self.safe_integer(response, 'serverTime')
        markets = self.safe_list(response, 'result')
        result = {}
        for i in range(0, len(markets)):
            markets[i]['timestamp'] = timestamp
            ticker = self.parse_ticker(markets[i])
            result[ticker['symbol']] = ticker
        return self.filter_by_array_tickers(result, 'symbol', symbols)

    def parse_ticker(self, ticker, market: Market = None) -> Ticker:
        marketId = self.safe_string(ticker, 'symbol')
        market = self.safe_market(marketId, market)
        return self.safe_ticker({
            'symbol': market['symbol'],
            'timestamp': self.safe_integer(ticker, 'timestamp'),
            'datetime': None,
            'high': self.safe_string(ticker, 'highest_price'),
            'low': self.safe_string(ticker, 'lowest_price'),
            'bid': self.safe_string(ticker, 'bid_price'),
            'bidVolume': None,
            'ask': self.safe_string(ticker, 'ask_price'),
            'askVolume': None,
            'vwap': None,
            'open': None,
            'close': self.safe_string(ticker, 'last_price'),
            'last': self.safe_string(ticker, 'last_price'),
            'previousClose': None,
            'change': self.safe_string(ticker, 'change_price'),
            'percentage': self.safe_string(ticker, 'change_percentage'),
            'average': None,
            'baseVolume': self.safe_string(ticker, 'volume'),
            'quoteVolume': None,
            'info': ticker,
        }, market)

    def sign(self, path, api='public', method='GET', params={}, headers=None, body=None):
        url = self.urls['api'][api] + '/' + self.implode_params(path, params)
        query = self.omit(params, self.extract_params(path))
        if query:
            url += '?' + self.urlencode(query)
        headers = {'Accept': 'application/json'}
        return {'url': url, 'method': method, 'body': body, 'headers': headers}
