# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.async_support.base.exchange import Exchange
from ccxt.abstract.daric import ImplicitAPI
from ccxt.base.types import Any, Market, Strings, Ticker, Tickers
from typing import List


class daric(Exchange, ImplicitAPI):

    def describe(self) -> Any:
        return self.deep_extend(super(daric, self).describe(), {
            'id': 'daric',
            'name': 'Daric',
            'countries': ['IR'],
            'rateLimit': 1000,
            'version': '1',
            'certified': False,
            'pro': False,
            'has': {
                'CORS': None,
                'spot': False,
                'margin': False,
                'swap': False,
                'future': False,
                'option': False,
                'fetchMarkets': True,
                'fetchTicker': True,
                'fetchTickers': True,
                'otc': True,
            },
            'options': {
                'defaultType': 'otc',
            },
            'urls': {
                'api': {
                    'public': 'https://apie.daric.gold',
                },
                'www': 'https://daric.gold',
                'doc': 'https://apie.daric.gold/public/general/PairList?src=TMN',
            },
            'api': {
                'public': {
                    'get': {
                        'public/general/PairList': 1,
                    },
                },
            },
        })

    async def fetch_markets(self, params={}) -> List[Market]:
        response = await self.fetch_pair_list(params)
        return self.parse_markets(response)

    def fetch_pair_list(self, params={}):
        return self.publicGetPublicGeneralPairList(self.extend({'src': 'TMN'}, params))

    def parse_markets(self, response) -> List[Market]:
        markets = []
        if isinstance(response, list):
            markets = response
        result = []
        for i in range(0, len(markets)):
            market = markets[i]
            baseId = self.safe_string(market, 'destinationCoinSymbol')
            if baseId == 'GOLD18' or baseId == 'SILVER':
                result.append(self.parse_market(market))
        return result

    def parse_market(self, market) -> Market:
        baseId = self.safe_string(market, 'destinationCoinSymbol')
        base = 'XAG'
        if baseId == 'GOLD18':
            base = 'XAU18'
        quote = 'IRT'
        return {
            'id': self.safe_string(market, 'id'),
            'symbol': base + '/' + quote,
            'base': base,
            'quote': quote,
            'settle': None,
            'baseId': baseId,
            'quoteId': self.safe_string(market, 'sourceCoinSymbol'),
            'settleId': None,
            'type': 'otc',
            'spot': False,
            'margin': False,
            'swap': False,
            'future': False,
            'option': False,
            'active': True,
            'contract': False,
            'linear': None,
            'inverse': None,
            'contractSize': None,
            'expiry': None,
            'expiryDatetime': None,
            'strike': None,
            'optionType': None,
            'precision': {
                'amount': None,
                'price': self.safe_integer(market, 'decimalLength'),
            },
            'limits': {
                'leverage': {'min': None, 'max': None},
                'amount': {'min': None, 'max': None},
                'price': {'min': None, 'max': None},
                'cost': {'min': None, 'max': None},
            },
            'created': None,
            'info': market,
        }

    async def fetch_ticker(self, symbol: str, params={}) -> Ticker:
        await self.load_markets()
        market = self.market(symbol)
        response = await self.fetch_pair_list(params)
        return self.parse_ticker(response, market)

    async def fetch_tickers(self, symbols: Strings = None, params={}) -> Tickers:
        await self.load_markets()
        if symbols is not None:
            symbols = self.market_symbols(symbols)
        response = await self.fetch_pair_list(params)
        result = {}
        markets = self.parse_markets(response)
        for i in range(0, len(markets)):
            ticker = self.parse_ticker(response, markets[i])
            result[ticker['symbol']] = ticker
        return self.filter_by_array_tickers(result, 'symbol', symbols)

    def parse_ticker(self, response, market: Market = None) -> Ticker:
        markets = []
        if isinstance(response, list):
            markets = response
        ticker = self.filter_by(markets, 'destinationCoinSymbol', market['baseId'])[0]
        return self.safe_ticker({
            'symbol': market['symbol'],
            'timestamp': None,
            'datetime': None,
            'high': self.safe_number(ticker, 'highestRecentOrder'),
            'low': self.safe_number(ticker, 'lowestRecentOrder'),
            'bid': self.safe_number(ticker, 'bestBuy'),
            'bidVolume': None,
            'ask': self.safe_number(ticker, 'bestSell'),
            'askVolume': None,
            'vwap': None,
            'open': None,
            'close': self.safe_number(ticker, 'lastOrderPrice'),
            'last': self.safe_number(ticker, 'lastOrderPrice'),
            'previousClose': None,
            'change': None,
            'percentage': self.safe_number(ticker, 'change'),
            'average': None,
            'baseVolume': self.safe_number(ticker, 'todayTradeAmount'),
            'quoteVolume': self.safe_number(ticker, 'todayTradeTotal'),
            'info': ticker,
        }, market)

    def sign(self, path, api='public', method='GET', params={}, headers=None, body=None):
        url = self.urls['api'][api] + '/' + self.implode_params(path, params)
        query = self.omit(params, self.extract_params(path))
        if query:
            url += '?' + self.urlencode(query)
        headers = {'Accept': 'application/json'}
        return {'url': url, 'method': method, 'body': body, 'headers': headers}
