# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.async_support.base.exchange import Exchange
from ccxt.abstract.digikalagold import ImplicitAPI
from ccxt.base.types import Any, Market, Strings, Ticker, Tickers
from typing import List
from ccxt.base.errors import ExchangeError


class digikalagold(Exchange, ImplicitAPI):

    def describe(self) -> Any:
        return self.deep_extend(super(digikalagold, self).describe(), {
            'id': 'digikalagold',
            'name': 'Digikala Gold',
            'countries': ['IR'],
            'rateLimit': 1000,
            'version': 'v1',
            'certified': False,
            'pro': False,
            'has': {
                'CORS': None,
                'spot': False,
                'margin': False,
                'swap': False,
                'future': False,
                'option': False,
                'fetchMarkets': True,
                'fetchTicker': True,
                'fetchTickers': True,
                'otc': True,
            },
            'options': {
                'defaultType': 'otc',
            },
            'urls': {
                'api': {
                    'public': 'https://api.digikala.com',
                },
                'www': 'https://www.digikala.com',
                'doc': 'https://api.digikala.com/non-inventory/v1/prices/',
            },
            'api': {
                'public': {
                    'get': {
                        'non-inventory/v1/prices/': 1,
                    },
                },
            },
        })

    async def fetch_markets(self, params={}) -> List[Market]:
        response = await self.fetch_price(params)
        return [
            self.parse_market_entry(response, 'gold18'),
            self.parse_market_entry(response, 'silver999'),
        ]

    async def fetch_price(self, params={}):
        response = await self.publicGetNonInventoryV1Prices(params)
        gold = self.safe_dict(response, 'gold18', {})
        if self.safe_number(gold, 'price') is not None:
            return response
        raise ExchangeError(self.id + ' returned an invalid response')

    def parse_market_entry(self, response, id: str) -> Market:
        isGold = id == 'gold18'
        base = 'XAG'
        if isGold:
            base = 'XAU18'
        quote = 'IRT'
        info = self.safe_dict(response, id, {})
        return {
            'id': base + quote,
            'symbol': base + '/' + quote,
            'base': base,
            'quote': quote,
            'settle': None,
            'baseId': id,
            'quoteId': quote,
            'settleId': None,
            'type': 'otc',
            'spot': False,
            'margin': False,
            'swap': False,
            'future': False,
            'option': False,
            'active': True,
            'contract': False,
            'linear': None,
            'inverse': None,
            'contractSize': None,
            'expiry': None,
            'expiryDatetime': None,
            'strike': None,
            'optionType': None,
            'precision': {
                'amount': None,
                'price': None,
            },
            'limits': {
                'leverage': {'min': None, 'max': None},
                'amount': {'min': None, 'max': None},
                'price': {'min': None, 'max': None},
                'cost': {'min': None, 'max': None},
            },
            'created': None,
            'info': info,
        }

    async def fetch_ticker(self, symbol: str, params={}) -> Ticker:
        await self.load_markets()
        market = self.market(symbol)
        response = await self.fetch_price(params)
        return self.parse_ticker(response, market)

    async def fetch_tickers(self, symbols: Strings = None, params={}) -> Tickers:
        await self.load_markets()
        if symbols is not None:
            symbols = self.market_symbols(symbols)
        response = await self.fetch_price(params)
        result = {}
        marketSymbols = ['XAU18/IRT', 'XAG/IRT']
        for i in range(0, len(marketSymbols)):
            symbol = marketSymbols[i]
            market = self.market(symbol)
            ticker = self.parse_ticker(response, market)
            result[ticker['symbol']] = ticker
        return self.filter_by_array_tickers(result, 'symbol', symbols)

    def parse_ticker(self, response, market: Market = None) -> Ticker:
        data = self.safe_dict(response, market['baseId'], {})
        price = self.safe_number(data, 'price')
        if price is not None:
            price = price * 100
        return self.safe_ticker({
            'symbol': market['symbol'],
            'timestamp': None,
            'datetime': None,
            'high': None,
            'low': None,
            'bid': price,
            'bidVolume': None,
            'ask': price,
            'askVolume': None,
            'vwap': None,
            'open': None,
            'close': price,
            'last': price,
            'previousClose': None,
            'change': None,
            'percentage': None,
            'average': None,
            'baseVolume': None,
            'quoteVolume': None,
            'info': data,
        }, market)

    def sign(self, path, api='public', method='GET', params={}, headers=None, body=None):
        url = self.urls['api'][api] + '/' + self.implode_params(path, params)
        query = self.omit(params, self.extract_params(path))
        if query:
            url += '?' + self.urlencode(query)
        headers = {'Accept': 'application/json'}
        return {'url': url, 'method': method, 'body': body, 'headers': headers}
