# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.async_support.base.exchange import Exchange
from ccxt.abstract.goldika import ImplicitAPI
from ccxt.base.types import Any, Market, Strings, Ticker, Tickers
from typing import List


class goldika(Exchange, ImplicitAPI):

    def describe(self) -> Any:
        return self.deep_extend(super(goldika, self).describe(), {
            'id': 'goldika',
            'name': 'Goldika',
            'countries': ['IR'],
            'rateLimit': 1000,
            'version': 'v2',
            'certified': False,
            'pro': False,
            'has': {
                'CORS': None,
                'spot': False,
                'margin': False,
                'swap': False,
                'future': False,
                'option': False,
                'fetchMarkets': True,
                'fetchTicker': True,
                'fetchTickers': True,
                'otc': True,
            },
            'options': {
                'defaultType': 'otc',
            },
            'urls': {
                'api': {
                    'public': 'https://api.goldika.ir',
                },
                'www': 'https://goldika.ir',
                'doc': 'https://api.goldika.ir/api/v2/public/price',
            },
            'api': {
                'public': {
                    'get': {
                        'api/v2/public/price': 1,
                    },
                },
            },
        })

    async def fetch_markets(self, params={}) -> List[Market]:
        response = await self.publicGetApiV2PublicPrice(params)
        return [self.parse_market(response)]

    def parse_market(self, response) -> Market:
        data = self.safe_dict(response, 'data', {})
        oldPrice = self.safe_dict(data, 'old_price', {})
        return {
            'id': 'XAU18IRT',
            'symbol': 'XAU18/IRT',
            'base': 'XAU18',
            'quote': 'IRT',
            'settle': None,
            'baseId': 'XAU18',
            'quoteId': 'IRT',
            'settleId': None,
            'type': 'otc',
            'spot': False,
            'margin': False,
            'swap': False,
            'future': False,
            'option': False,
            'active': True,
            'contract': False,
            'linear': None,
            'inverse': None,
            'contractSize': None,
            'expiry': None,
            'expiryDatetime': None,
            'strike': None,
            'optionType': None,
            'precision': {
                'amount': None,
                'price': None,
            },
            'limits': {
                'leverage': {'min': None, 'max': None},
                'amount': {'min': None, 'max': None},
                'price': {'min': None, 'max': None},
                'cost': {'min': None, 'max': None},
            },
            'created': None,
            'info': oldPrice,
        }

    async def fetch_ticker(self, symbol: str, params={}) -> Ticker:
        await self.load_markets()
        market = self.market(symbol)
        response = await self.publicGetApiV2PublicPrice(params)
        return self.parse_ticker(response, market)

    async def fetch_tickers(self, symbols: Strings = None, params={}) -> Tickers:
        await self.load_markets()
        if symbols is not None:
            symbols = self.market_symbols(symbols)
        response = await self.publicGetApiV2PublicPrice(params)
        market = self.market('XAU18/IRT')
        ticker = self.parse_ticker(response, market)
        result = {}
        result[ticker['symbol']] = ticker
        return self.filter_by_array_tickers(result, 'symbol', symbols)

    def parse_ticker(self, response, market: Market = None) -> Ticker:
        data = self.safe_dict(response, 'data', {})
        oldPrice = self.safe_dict(data, 'old_price', {})
        timestamp = self.parse8601(self.safe_string(oldPrice, 'created_at'))
        bid = self.safe_number(oldPrice, 'buy')
        ask = self.safe_number(oldPrice, 'sell')
        if bid is not None:
            bid = bid / 10
        if ask is not None:
            ask = ask / 10
        return self.safe_ticker({
            'symbol': market['symbol'],
            'timestamp': timestamp,
            'datetime': None,
            'high': None,
            'low': None,
            'bid': bid,
            'bidVolume': None,
            'ask': ask,
            'askVolume': None,
            'vwap': None,
            'open': None,
            'close': ask,
            'last': ask,
            'previousClose': None,
            'change': None,
            'percentage': self.safe_number(data, 'daily_change_percent'),
            'average': None,
            'baseVolume': None,
            'quoteVolume': None,
            'info': oldPrice,
        }, market)

    def sign(self, path, api='public', method='GET', params={}, headers=None, body=None):
        url = self.urls['api'][api] + '/' + self.implode_params(path, params)
        query = self.omit(params, self.extract_params(path))
        if query:
            url += '?' + self.urlencode(query)
        headers = {'Accept': 'application/json'}
        return {'url': url, 'method': method, 'body': body, 'headers': headers}
