# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.async_support.base.exchange import Exchange
from ccxt.abstract.ourbit import ImplicitAPI
from ccxt.base.types import Any, Market, Strings, Ticker, Tickers
from typing import List


class ourbit(Exchange, ImplicitAPI):

    def describe(self) -> Any:
        return self.deep_extend(super(ourbit, self).describe(), {
            'id': 'ourbit',
            'name': 'Ourbit',
            'countries': ['VG'],
            'rateLimit': 100,
            'has': {
                'CORS': None,
                'spot': True,
                'margin': False,
                'swap': False,
                'future': True,
                'option': False,
                'fetchMarkets': True,
                'fetchTicker': True,
                'fetchTickers': True,
            },
            'urls': {
                'api': {
                    'spot': 'https://www.ourbit.com',
                    'futures': 'https://futures.ourbit.com',
                },
                'www': 'https://www.ourbit.com',
                'doc': 'https://www.ourbit.com',
            },
            'api': {
                'spot': {
                    'get': [
                        'api/platform/spot/market/v2/tickers',
                        'api/platform/spot/market/v2/symbol/ticker',
                    ],
                },
                'futures': {
                    'get': [
                        'api/v1/contract/ticker',
                    ],
                },
            },
        })

    async def fetch_markets(self, params={}) -> List[Market]:
        """
        retrieves data on all available markets for ourbit
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict[]: an array of objects representing market data
        """
        type = self.safe_string(params, 'type')
        params = self.omit(params, ['type'])
        fetchSpot = (type is None) or (type == 'spot')
        fetchFutures = (type is None) or (type == 'future') or (type == 'swap')
        result = []
        if fetchSpot:
            response = await self.spotGetApiPlatformSpotMarketV2Tickers(params)
            markets = response
            if not isinstance(markets, list):
                markets = self.safe_list(response, 'data', [])
            for i in range(0, len(markets)):
                result.append(self.parse_spot_market(markets[i]))
        if fetchFutures:
            response = await self.futuresGetApiV1ContractTicker(params)
            markets = self.safe_list(response, 'data', [])
            for i in range(0, len(markets)):
                result.append(self.parse_future_market(markets[i]))
        return result

    def parse_spot_market(self, market) -> Market:
        marketId = self.safe_string(market, 'sb')
        parts = []
        if marketId is not None:
            parts = marketId.split('_')
        baseId = self.safe_string(parts, 0)
        quoteId = self.safe_string(parts, 1)
        base = self.safe_currency_code(baseId)
        quote = self.safe_currency_code(quoteId)
        return {
            'id': marketId,
            'symbol': base + '/' + quote,
            'base': base,
            'quote': quote,
            'settle': None,
            'baseId': baseId,
            'quoteId': quoteId,
            'settleId': None,
            'type': 'spot',
            'spot': True,
            'margin': False,
            'swap': False,
            'future': False,
            'option': False,
            'active': self.safe_integer(market, 'sts') == 1,
            'contract': False,
            'linear': None,
            'inverse': None,
            'contractSize': None,
            'expiry': None,
            'expiryDatetime': None,
            'strike': None,
            'optionType': None,
            'precision': {
                'amount': None,
                'price': None,
            },
            'limits': {
                'leverage': {
                    'min': None,
                    'max': None,
                },
                'amount': {
                    'min': None,
                    'max': None,
                },
                'price': {
                    'min': None,
                    'max': None,
                },
                'cost': {
                    'min': None,
                    'max': None,
                },
            },
            'created': None,
            'info': market,
        }

    def parse_future_market(self, market) -> Market:
        marketId = self.safe_string(market, 'symbol')
        parts = []
        if marketId is not None:
            parts = marketId.split('_')
        baseId = self.safe_string(parts, 0)
        quoteId = self.safe_string(parts, 1)
        base = self.safe_currency_code(baseId)
        quote = self.safe_currency_code(quoteId)
        settle = quote
        return {
            'id': marketId,
            'symbol': base + '/' + quote + ':' + settle,
            'base': base,
            'quote': quote,
            'settle': settle,
            'baseId': baseId,
            'quoteId': quoteId,
            'settleId': quoteId,
            'type': 'future',
            'spot': False,
            'margin': False,
            'swap': False,
            'future': True,
            'option': False,
            'active': True,
            'contract': True,
            'linear': True,
            'inverse': False,
            'contractSize': None,
            'expiry': None,
            'expiryDatetime': None,
            'strike': None,
            'optionType': None,
            'precision': {
                'amount': None,
                'price': None,
            },
            'limits': {
                'leverage': {
                    'min': None,
                    'max': None,
                },
                'amount': {
                    'min': None,
                    'max': None,
                },
                'price': {
                    'min': None,
                    'max': None,
                },
                'cost': {
                    'min': None,
                    'max': None,
                },
            },
            'created': None,
            'info': market,
        }

    async def fetch_tickers(self, symbols: Strings = None, params={}) -> Tickers:
        """
        fetches price tickers for multiple markets
        :param str[]|None symbols: unified symbols of the markets to fetch the ticker for, all market tickers are returned if not assigned
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a dictionary of `ticker structures <https://docs.ccxt.com/#/?id=ticker-structure>`
        """
        await self.load_markets()
        if symbols is not None:
            symbols = self.market_symbols(symbols)
        type = self.safe_string(params, 'type')
        params = self.omit(params, ['type'])
        result = {}
        fetchSpot = (type is None) or (type == 'spot')
        fetchFutures = (type is None) or (type == 'future') or (type == 'swap')
        if fetchSpot:
            response = await self.spotGetApiPlatformSpotMarketV2Tickers(params)
            tickers = response
            if not isinstance(tickers, list):
                tickers = self.safe_list(response, 'data', [])
            for i in range(0, len(tickers)):
                ticker = tickers[i]
                parsed = self.parse_ticker(ticker, None, 'spot')
                result[parsed['symbol']] = parsed
        if fetchFutures:
            response = await self.futuresGetApiV1ContractTicker(params)
            tickers = self.safe_list(response, 'data', [])
            for i in range(0, len(tickers)):
                ticker = tickers[i]
                parsed = self.parse_ticker(ticker, None, 'future')
                result[parsed['symbol']] = parsed
        return self.filter_by_array_tickers(result, 'symbol', symbols)

    async def fetch_ticker(self, symbol: str, params={}) -> Ticker:
        """
        fetches a price ticker for a single market
        :param str symbol: unified symbol of the market to fetch the ticker for
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a `ticker structure <https://docs.ccxt.com/#/?id=ticker-structure>`
        """
        await self.load_markets()
        market = self.market(symbol)
        marketType = self.safe_string(params, 'type', self.safe_string(market, 'type'))
        params = self.omit(params, ['type'])
        request = {
            'symbol': market['id'],
        }
        if (marketType == 'future') or (marketType == 'swap'):
            responseData = await self.futuresGetApiV1ContractTicker(self.extend(request, params))
            tickerList = self.safe_dict(responseData, 'data', responseData)
            tickerList['timestamp'] = self.safe_string(responseData, 'timestamp')
            return self.parse_ticker(tickerList, market, 'future')
        response = await self.spotGetApiPlatformSpotMarketV2SymbolTicker(self.extend(request, params))
        ticker = self.safe_dict(response, 'data', response)
        ticker['timestamp'] = self.safe_string(response, 'timestamp')
        return self.parse_ticker(ticker, market, 'spot')

    def parse_ticker(self, ticker: dict, market: Market = None, marketType: str = None) -> Ticker:
        isFuture = (marketType == 'future') or (marketType == 'swap') or (market is None and self.safe_string(ticker, 'contractId') is not None)
        marketId = self.safe_string_2(ticker, 'sb', 'symbol')
        timestamp = self.safe_integer_2(ticker, 'timestamp', 'ts')
        last = self.safe_number_2(ticker, 'c', 'lastPrice')
        high = self.safe_number_2(ticker, 'h', 'high24Price')
        low = self.safe_number_2(ticker, 'l', 'lower24Price')
        open = self.safe_number(ticker, 'o')
        change = self.safe_number(ticker, 'riseFallValue')
        percentage = self.safe_number_2(ticker, 'r8', 'riseFallRate')
        bid = self.safe_number_2(ticker, 'bid1', 'bid1Price')
        ask = self.safe_number_2(ticker, 'ask1', 'ask1Price')
        bidVolume = self.safe_number_2(ticker, 'bid1Size', 'bidSz')
        askVolume = self.safe_number_2(ticker, 'ask1Size', 'askSz')
        baseVolume = self.safe_number_2(ticker, 'q', 'volume24')
        quoteVolume = self.safe_number_2(ticker, 'a', 'amount24')
        indexPrice = self.safe_number(ticker, 'indexPrice')
        markPrice = self.safe_number_2(ticker, 'fairPrice', 'markPrice')
        if percentage is not None:
            percentage *= 100
        if isFuture:
            if (open is None) and (last is not None) and (change is not None):
                open = last - change
        else:
            if (change is None) and (open is not None) and (last is not None):
                change = last - open
        if market is None:
            parts = []
            if marketId is not None:
                parts = marketId.split('_')
            base = self.safe_currency_code(self.safe_string(parts, 0))
            quote = self.safe_currency_code(self.safe_string(parts, 1))
            quoteId = self.safe_string(parts, 1)
            settle = None
            symbol = base + '/' + quote
            inferredMarketType = 'spot'
            if isFuture:
                settle = quote
                symbol = base + '/' + quote + ':' + settle
                inferredMarketType = 'future'
            market = self.safe_market_structure({
                'id': marketId,
                'symbol': symbol,
                'base': base,
                'quote': quote,
                'settle': settle,
                'baseId': self.safe_string(parts, 0),
                'quoteId': quoteId,
                'settleId': quoteId,
                'type': inferredMarketType,
                'spot': not isFuture,
                'margin': False,
                'swap': False,
                'future': isFuture,
                'option': False,
                'active': True,
                'contract': isFuture,
                'linear': isFuture,
                'inverse': False,
                'contractSize': None,
                'expiry': None,
                'expiryDatetime': None,
                'strike': None,
                'optionType': None,
                'precision': {
                    'amount': None,
                    'price': None,
                },
                'limits': {
                    'leverage': {
                        'min': None,
                        'max': None,
                    },
                    'amount': {
                        'min': None,
                        'max': None,
                    },
                    'price': {
                        'min': None,
                        'max': None,
                    },
                    'cost': {
                        'min': None,
                        'max': None,
                    },
                },
                'created': None,
                'info': ticker,
            })
        return self.safe_ticker({
            'symbol': market['symbol'],
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'high': high,
            'low': low,
            'bid': bid,
            'bidVolume': bidVolume,
            'ask': ask,
            'askVolume': askVolume,
            'vwap': None,
            'open': open,
            'close': last,
            'last': last,
            'previousClose': None,
            'change': change,
            'percentage': percentage,
            'average': None,
            'baseVolume': baseVolume,
            'quoteVolume': quoteVolume,
            'markPrice': markPrice,
            'indexPrice': indexPrice,
            'info': ticker,
        }, market)

    def sign(self, path, api='spot', method='GET', params={}, headers=None, body=None):
        query = self.omit(params, self.extract_params(path))
        url = self.urls['api'][api] + '/' + self.implode_params(path, params)
        if query:
            url += '?' + self.urlencode(query)
        headers = {
            'Content-Type': 'application/json',
        }
        return {'url': url, 'method': method, 'body': body, 'headers': headers}
