# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.async_support.base.exchange import Exchange
from ccxt.abstract.poulyar import ImplicitAPI
from ccxt.base.types import Any, Market, Strings, Ticker, Tickers
from typing import List


class poulyar(Exchange, ImplicitAPI):

    def describe(self) -> Any:
        return self.deep_extend(super(poulyar, self).describe(), {
            'id': 'poulyar',
            'name': 'Poulyar',
            'countries': ['IR'],
            'rateLimit': 1000,
            'version': 'v2',
            'certified': False,
            'pro': False,
            'has': {
                'CORS': None,
                'spot': False,
                'margin': False,
                'swap': False,
                'future': False,
                'option': False,
                'fetchMarkets': True,
                'fetchTicker': True,
                'fetchTickers': True,
                'otc': True,
            },
            'options': {
                'defaultType': 'otc',
            },
            'urls': {
                'api': {
                    'public': 'https://api.poulyar.com',
                },
                'www': 'https://poulyar.com',
                'doc': 'https://api.poulyar.com/api/v2/market-data',
            },
            'api': {
                'public': {
                    'get': {
                        'api/v2/market-data': 1,
                    },
                },
            },
        })

    async def fetch_markets(self, params={}) -> List[Market]:
        """
        retrieves data on all OTC markets for poulyar
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict[]: an array of objects representing market data
        """
        response = await self.publicGetApiV2MarketData(params)
        result = self.safe_dict(response, 'result', {})
        markets = self.safe_dict(result, 'symbols', {})
        marketIds = list(markets.keys())
        parsedMarkets = []
        for i in range(0, len(marketIds)):
            parsedMarkets.append(self.parse_market(markets[marketIds[i]]))
        return parsedMarkets

    def parse_market(self, market) -> Market:
        id = self.safe_string(market, 'symbol')
        baseId = self.safe_string(market, 'baseAsset')
        quoteId = self.safe_string(market, 'quoteAsset')
        base = self.safe_currency_code(baseId)
        quote = self.safe_currency_code(quoteId)
        return {
            'id': id,
            'symbol': base + '/' + quote,
            'base': base,
            'quote': quote,
            'settle': None,
            'baseId': baseId,
            'quoteId': quoteId,
            'settleId': None,
            'type': 'otc',
            'spot': False,
            'margin': False,
            'swap': False,
            'future': False,
            'option': False,
            'active': True,
            'contract': False,
            'linear': None,
            'inverse': None,
            'contractSize': None,
            'expiry': None,
            'expiryDatetime': None,
            'strike': None,
            'optionType': None,
            'precision': {
                'amount': self.safe_number(market, 'basePrecision'),
                'price': self.safe_number(market, 'quotePrecision'),
            },
            'limits': {
                'leverage': {'min': None, 'max': None},
                'amount': {'min': self.safe_number(market, 'minQty'), 'max': None},
                'price': {'min': None, 'max': None},
                'cost': {'min': self.safe_number(market, 'minNotional'), 'max': None},
            },
            'created': None,
            'info': market,
        }

    async def fetch_ticker(self, symbol: str, params={}) -> Ticker:
        """
        fetches a price ticker for an OTC market
        :param str symbol: unified symbol of the market to fetch the ticker for
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a `ticker structure <https://docs.ccxt.com/#/?id=ticker-structure>`
        """
        tickers = await self.fetch_tickers([symbol], params)
        return tickers[symbol]

    async def fetch_tickers(self, symbols: Strings = None, params={}) -> Tickers:
        """
        fetches price tickers for all OTC markets
        :param str[]|None symbols: unified symbols of the markets to fetch the tickers for
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a dictionary of `ticker structures <https://docs.ccxt.com/#/?id=ticker-structure>`
        """
        await self.load_markets()
        if symbols is not None:
            symbols = self.market_symbols(symbols)
        response = await self.publicGetApiV2MarketData(params)
        result = self.safe_dict(response, 'result', {})
        markets = self.safe_dict(result, 'symbols', {})
        marketIds = list(markets.keys())
        tickers = {}
        for i in range(0, len(marketIds)):
            ticker = self.parse_ticker(markets[marketIds[i]])
            tickers[ticker['symbol']] = ticker
        return self.filter_by_array_tickers(tickers, 'symbol', symbols)

    def parse_ticker(self, ticker, market: Market = None) -> Ticker:
        marketId = self.safe_string(ticker, 'symbol')
        market = self.safe_market(marketId, market)
        stats = self.safe_dict(ticker, 'stats', {})
        return self.safe_ticker({
            'symbol': market['symbol'],
            'timestamp': self.parse8601(self.safe_string(ticker, 'updatedAt')),
            'datetime': None,
            'high': None,
            'low': None,
            'bid': self.safe_string(stats, 'bidPrice'),
            'bidVolume': None,
            'ask': self.safe_string(stats, 'askPrice'),
            'askVolume': None,
            'vwap': None,
            'open': None,
            'close': self.safe_string(stats, 'lastPrice'),
            'last': self.safe_string(stats, 'lastPrice'),
            'previousClose': None,
            'change': None,
            'percentage': self.safe_string(stats, '24h_ch'),
            'average': None,
            'baseVolume': None,
            'quoteVolume': None,
            'info': ticker,
        }, market)

    def sign(self, path, api='public', method='GET', params={}, headers=None, body=None):
        url = self.urls['api'][api] + '/' + self.implode_params(path, params)
        query = self.omit(params, self.extract_params(path))
        if query:
            url += '?' + self.urlencode(query)
        headers = {'Accept': 'application/json'}
        return {'url': url, 'method': method, 'body': body, 'headers': headers}
