# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.async_support.base.exchange import Exchange
from ccxt.abstract.saraf import ImplicitAPI
from ccxt.base.types import Any, Market, Strings, Ticker, Tickers
from typing import List


class saraf(Exchange, ImplicitAPI):

    def describe(self) -> Any:
        return self.deep_extend(super(saraf, self).describe(), {
            'id': 'saraf',
            'name': 'Saraf',
            'countries': ['IR'],
            'rateLimit': 1000,
            'version': '3',
            'certified': False,
            'pro': False,
            'has': {
                'CORS': None,
                'spot': False,
                'margin': False,
                'swap': False,
                'future': False,
                'option': False,
                'addMargin': False,
                'cancelAllOrders': False,
                'cancelOrder': False,
                'cancelOrders': False,
                'createDepositAddress': False,
                'createOrder': False,
                'createStopLimitOrder': False,
                'createStopMarketOrder': False,
                'createStopOrder': False,
                'editOrder': False,
                'fetchBalance': False,
                'fetchBorrowInterest': False,
                'fetchBorrowRateHistories': False,
                'fetchBorrowRateHistory': False,
                'fetchClosedOrders': False,
                'fetchCrossBorrowRate': False,
                'fetchCrossBorrowRates': False,
                'fetchCurrencies': False,
                'fetchDepositAddress': False,
                'fetchDeposits': False,
                'fetchFundingHistory': False,
                'fetchFundingRate': False,
                'fetchFundingRateHistory': False,
                'fetchFundingRates': False,
                'fetchIndexOHLCV': False,
                'fetchIsolatedBorrowRate': False,
                'fetchIsolatedBorrowRates': False,
                'fetchL2OrderBook': False,
                'fetchL3OrderBook': False,
                'fetchLedger': False,
                'fetchLedgerEntry': False,
                'fetchLeverageTiers': False,
                'fetchMarkets': True,
                'fetchMarkOHLCV': False,
                'fetchMyTrades': False,
                'fetchOHLCV': False,
                'fetchOpenInterestHistory': False,
                'fetchOpenOrders': False,
                'fetchOrder': False,
                'fetchOrderBook': False,
                'fetchOrders': False,
                'fetchOrderTrades': 'emulated',
                'fetchPositions': False,
                'fetchPremiumIndexOHLCV': False,
                'fetchTicker': True,
                'fetchTickers': True,
                'fetchTime': False,
                'fetchTrades': False,
                'fetchTradingFee': False,
                'fetchTradingFees': False,
                'fetchWithdrawals': False,
                'otc': True,
                'setLeverage': False,
                'setMarginMode': False,
                'transfer': False,
                'withdraw': False,
            },
            'options': {
                'defaultType': 'otc',
            },
            'urls': {
                'logo': 'https://cdn.arz.digital/cr-odin/img/exchanges/saraf/64x64.png',
                'api': {
                    'public': 'https://api.saraf.app',
                },
                'www': 'https://saraf.app',
                'doc': [
                    'https://saraf.app',
                ],
            },
            'api': {
                'public': {
                    'get': {
                        'v1/prices/arzdigital': 1,
                    },
                },
            },
            'fees': {
                'trading': {
                    'tierBased': False,
                    'percentage': True,
                    'maker': self.parse_number('0'),
                    'taker': self.parse_number('0'),
                },
            },
        })

    def parse_market(self, market) -> Market:
        baseId = self.safe_string(market, 's')
        quoteId = 'IRT'
        base = self.safe_currency_code(baseId)
        quote = self.safe_currency_code(quoteId)
        return {
            'id': baseId,
            'symbol': base + '/' + quote,
            'base': base,
            'quote': quote,
            'settle': None,
            'baseId': baseId,
            'quoteId': quoteId,
            'settleId': None,
            'type': 'otc',
            'spot': False,
            'margin': False,
            'swap': False,
            'future': False,
            'option': False,
            'active': self.safe_bool(market, 'ct', True),
            'contract': False,
            'linear': None,
            'inverse': None,
            'contractSize': None,
            'expiry': None,
            'expiryDatetime': None,
            'strike': None,
            'optionType': None,
            'precision': {
                'amount': None,
                'price': self.safe_integer(market, 'r'),
            },
            'limits': {
                'leverage': {
                    'min': None,
                    'max': None,
                },
                'amount': {
                    'min': None,
                    'max': None,
                },
                'price': {
                    'min': None,
                    'max': None,
                },
                'cost': {
                    'min': None,
                    'max': None,
                },
            },
            'created': None,
            'info': market,
        }

    async def fetch_markets(self, params={}) -> List[Market]:
        """
        retrieves data on all markets for saraf
        https://api.saraf.app/v1/prices/arzdigital
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict[]: an array of objects representing market data
        """
        response = await self.publicGetV1PricesArzdigital(params)
        price = self.safe_dict(response, 'price', {})
        items = self.safe_dict(price, 'Items', {})
        lastUpdateTime = self.safe_integer(price, 'lastUpdateTime')
        itemKeys = list(items.keys())
        result = []
        for i in range(0, len(itemKeys)):
            item = self.safe_dict(items, itemKeys[i], {})
            item['lastUpdateTime'] = lastUpdateTime
            baseId = self.safe_string(item, 's')
            if (baseId is None) or (baseId == 'IRT'):
                continue
            result.append(self.parse_market(item))
        return result

    async def fetch_tickers(self, symbols: Strings = None, params={}) -> Tickers:
        """
        fetches price tickers for multiple markets
        https://api.saraf.app/v1/prices/arzdigital
        :param str[]|None symbols: unified symbols of the markets to fetch the ticker for, all market tickers are returned if not assigned
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a dictionary of `ticker structures <https://docs.ccxt.com/#/?id=ticker-structure>`
        """
        await self.load_markets()
        if symbols is not None:
            symbols = self.market_symbols(symbols)
        response = await self.publicGetV1PricesArzdigital(params)
        price = self.safe_dict(response, 'price', {})
        items = self.safe_dict(price, 'Items', {})
        lastUpdateTime = self.safe_integer(price, 'lastUpdateTime')
        itemKeys = list(items.keys())
        result = {}
        for i in range(0, len(itemKeys)):
            item = self.safe_dict(items, itemKeys[i], {})
            item['lastUpdateTime'] = lastUpdateTime
            baseId = self.safe_string(item, 's')
            if (baseId is None) or (baseId == 'IRT') or (baseId == 'FIXED'):
                continue
            ticker = self.parse_ticker(item)
            result[ticker['symbol']] = ticker
        return self.filter_by_array_tickers(result, 'symbol', symbols)

    async def fetch_ticker(self, symbol: str, params={}) -> Ticker:
        """
        fetches a price ticker, a statistical calculation for a specific market
        https://api.saraf.app/v1/prices/arzdigital
        :param str symbol: unified symbol of the market to fetch the ticker for
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a `ticker structure <https://docs.ccxt.com/#/?id=ticker-structure>`
        """
        tickers = await self.fetch_tickers([symbol], params)
        return tickers[symbol]

    def parse_ticker(self, ticker, market: Market = None) -> Ticker:
        baseId = self.safe_string(ticker, 's')
        quoteId = 'IRT'
        base = self.safe_currency_code(baseId)
        quote = self.safe_currency_code(quoteId)
        symbol = base + '/' + quote
        history = self.safe_list(ticker, 'h', [])
        high = None
        low = None
        open = None
        if len(history) > 0:
            high = self.safe_number(history, 0)
            low = self.safe_number(history, 0)
            open = self.safe_number(history, len(history) - 1)
            for i in range(1, len(history)):
                price = self.safe_number(history, i)
                high = max(high, price)
                low = min(low, price)
        last = self.safe_number(ticker, 'p')
        percentage = self.safe_number(ticker, 'c')
        timestamp = self.safe_integer_2(ticker, 'ut', 'lastUpdateTime')
        change = None
        if (last is not None) and (open is not None):
            change = last - open
        if market is None:
            market = self.safe_market_structure(self.parse_market(ticker))
        return self.safe_ticker({
            'symbol': symbol,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'high': high,
            'low': low,
            'bid': None,
            'bidVolume': None,
            'ask': None,
            'askVolume': None,
            'vwap': None,
            'open': open,
            'close': last,
            'last': last,
            'previousClose': None,
            'change': change,
            'percentage': percentage,
            'average': None,
            'baseVolume': None,
            'quoteVolume': None,
            'info': ticker,
        }, market)

    def sign(self, path, api='public', method='GET', params={}, headers=None, body=None):
        query = self.omit(params, self.extract_params(path))
        url = self.urls['api'][api] + '/' + self.implode_params(path, params)
        if query:
            url += '?' + self.urlencode(query)
        headers = {
            'Content-Type': 'application/json',
        }
        return {'url': url, 'method': method, 'body': body, 'headers': headers}
