# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.async_support.base.exchange import Exchange
from ccxt.abstract.zarniv import ImplicitAPI
from ccxt.base.types import Any, Market, Strings, Ticker, Tickers
from typing import List


class zarniv(Exchange, ImplicitAPI):

    def describe(self) -> Any:
        return self.deep_extend(super(zarniv, self).describe(), {
            'id': 'zarniv',
            'name': 'Zarniv',
            'countries': ['IR'],
            'rateLimit': 1000,
            'version': '1',
            'certified': False,
            'pro': False,
            'has': {
                'CORS': None,
                'spot': False,
                'margin': False,
                'swap': False,
                'future': False,
                'option': False,
                'fetchMarkets': True,
                'fetchTicker': True,
                'fetchTickers': True,
                'otc': True,
            },
            'options': {
                'defaultType': 'otc',
            },
            'urls': {
                'api': {
                    'public': 'https://zarniv.ir',
                },
                'www': 'https://zarniv.ir',
                'doc': 'https://zarniv.ir/user/get_gold_price/',
            },
            'api': {
                'public': {
                    'get': {
                        'user/get_gold_price': 1,
                        'user/get_silver_price': 1,
                    },
                },
            },
        })

    def fetch_price(self, metal: str, params={}):
        if metal == 'gold':
            return self.publicGetUserGetGoldPrice(params)
        return self.publicGetUserGetSilverPrice(params)

    async def fetch_markets(self, params={}) -> List[Market]:
        goldResponse = await self.fetch_price('gold', params)
        silverResponse = await self.fetch_price('silver', params)
        return [
            self.parse_market_entry(goldResponse, 'gold'),
            self.parse_market_entry(silverResponse, 'silver'),
        ]

    def parse_market_entry(self, response, metal: str) -> Market:
        base = 'XAG'
        if metal == 'gold':
            base = 'XAU18'
        quote = 'IRT'
        return {
            'id': base + quote,
            'symbol': base + '/' + quote,
            'base': base,
            'quote': quote,
            'settle': None,
            'baseId': metal,
            'quoteId': quote,
            'settleId': None,
            'type': 'otc',
            'spot': False,
            'margin': False,
            'swap': False,
            'future': False,
            'option': False,
            'active': self.safe_number(response, 'base_price_per_gram') is not None,
            'contract': False,
            'linear': None,
            'inverse': None,
            'contractSize': None,
            'expiry': None,
            'expiryDatetime': None,
            'strike': None,
            'optionType': None,
            'precision': {
                'amount': None,
                'price': None,
            },
            'limits': {
                'leverage': {'min': None, 'max': None},
                'amount': {'min': None, 'max': None},
                'price': {'min': None, 'max': None},
                'cost': {'min': None, 'max': None},
            },
            'created': None,
            'info': response,
        }

    async def fetch_ticker(self, symbol: str, params={}) -> Ticker:
        await self.load_markets()
        market = self.market(symbol)
        response = await self.fetch_price(market['baseId'], params)
        return self.parse_ticker(response, market)

    async def fetch_tickers(self, symbols: Strings = None, params={}) -> Tickers:
        await self.load_markets()
        if symbols is not None:
            symbols = self.market_symbols(symbols)
        goldResponse = await self.fetch_price('gold', params)
        silverResponse = await self.fetch_price('silver', params)
        goldMarket = self.market('XAU18/IRT')
        silverMarket = self.market('XAG/IRT')
        goldTicker = self.parse_ticker(goldResponse, goldMarket)
        silverTicker = self.parse_ticker(silverResponse, silverMarket)
        result = {}
        result[goldTicker['symbol']] = goldTicker
        result[silverTicker['symbol']] = silverTicker
        return self.filter_by_array_tickers(result, 'symbol', symbols)

    def parse_ticker(self, response, market: Market = None) -> Ticker:
        serverTime = self.safe_string(response, 'server_time')
        timestamp = None
        if serverTime is not None:
            timestamp = self.parse8601(serverTime + '+03:30')
        bid = self.safe_number(response, 'sell_price_per_gram')
        ask = self.safe_number(response, 'buy_price_per_gram')
        last = self.safe_number(response, 'base_price_per_gram')
        return self.safe_ticker({
            'symbol': market['symbol'],
            'timestamp': timestamp,
            'datetime': None,
            'high': None,
            'low': None,
            'bid': bid,
            'bidVolume': None,
            'ask': ask,
            'askVolume': None,
            'vwap': None,
            'open': None,
            'close': last,
            'last': last,
            'previousClose': None,
            'change': None,
            'percentage': None,
            'average': None,
            'baseVolume': None,
            'quoteVolume': None,
            'info': response,
        }, market)

    def sign(self, path, api='public', method='GET', params={}, headers=None, body=None):
        url = self.urls['api'][api] + '/' + self.implode_params(path, params)
        query = self.omit(params, self.extract_params(path))
        if query:
            url += '?' + self.urlencode(query)
        headers = {'Accept': 'application/json'}
        return {'url': url, 'method': method, 'body': body, 'headers': headers}
