<?php

namespace ccxt\async\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class bidarz extends \ccxt\async\Exchange {
    public function public_get_v1_arz_digital_spot_markets($params = array()) {
        return $this->request('v1/arz-digital/spot/markets', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_v1_arz_digital_otc_markets($params = array()) {
        return $this->request('v1/arz-digital/otc/markets', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetV1ArzDigitalSpotMarkets($params = array()) {
        return $this->request('v1/arz-digital/spot/markets', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetV1ArzDigitalOtcMarkets($params = array()) {
        return $this->request('v1/arz-digital/otc/markets', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
}
