<?php

namespace ccxt\async\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class bitwana extends \ccxt\async\Exchange {
    public function public_get_api_1_markets($params = array()) {
        return $this->request('api/1/markets', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_api_1_markets_id($params = array()) {
        return $this->request('api/1/markets/{id}', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetApi1Markets($params = array()) {
        return $this->request('api/1/markets', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetApi1MarketsId($params = array()) {
        return $this->request('api/1/markets/{id}', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
}
