<?php

namespace ccxt\async\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class iranexchange extends \ccxt\async\Exchange {
    public function public_get_v1_client_listproduct($params = array()) {
        return $this->request('v1/client/listProduct', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_v1_client_getbysymbol($params = array()) {
        return $this->request('v1/client/getBySymbol', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetV1ClientListProduct($params = array()) {
        return $this->request('v1/client/listProduct', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetV1ClientGetBySymbol($params = array()) {
        return $this->request('v1/client/getBySymbol', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
}
