<?php

namespace ccxt\async\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class melligold extends \ccxt\async\Exchange {
    public function public_get_api_v1_exchange_buy_sell_price($params = array()) {
        return $this->request('api/v1/exchange/buy-sell-price/', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetApiV1ExchangeBuySellPrice($params = array()) {
        return $this->request('api/v1/exchange/buy-sell-price/', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
}
