<?php

namespace ccxt\async\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class technogold extends \ccxt\async\Exchange {
    public function public_get_customer_tradeables_only_price_1($params = array()) {
        return $this->request('customer/tradeables/only-price/1', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetCustomerTradeablesOnlyPrice1($params = array()) {
        return $this->request('customer/tradeables/only-price/1', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
}
