<?php

namespace ccxt\async\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class wallgold extends \ccxt\async\Exchange {
    public function public_get_api_v1_price($params = array()) {
        return $this->request('api/v1/price', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetApiV1Price($params = array()) {
        return $this->request('api/v1/price', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
}
