<?php

namespace ccxt\async\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class zarafza extends \ccxt\async\Exchange {
    public function public_get_v2_prices($params = array()) {
        return $this->request('v2/prices', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetV2Prices($params = array()) {
        return $this->request('v2/prices', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
}
