<?php

namespace ccxt\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class asacoine extends \ccxt\Exchange {
    public function public_get_v1_market_pairs_pricing($params = array()) {
        return $this->request('v1/market/pairs/pricing', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_v1_market_pairs_cumulative($params = array()) {
        return $this->request('v1/market/pairs/cumulative', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetV1MarketPairsPricing($params = array()) {
        return $this->request('v1/market/pairs/pricing', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetV1MarketPairsCumulative($params = array()) {
        return $this->request('v1/market/pairs/cumulative', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
}
