<?php

namespace ccxt\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class baazar extends \ccxt\Exchange {
    public function public_get_landing_v1_price_daily_30($params = array()) {
        return $this->request('landing/v1/price/DAILY/30', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetLandingV1PriceDAILY30($params = array()) {
        return $this->request('landing/v1/price/DAILY/30', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
}
