<?php

namespace ccxt\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class daric extends \ccxt\Exchange {
    public function public_get_public_general_pairlist($params = array()) {
        return $this->request('public/general/PairList', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetPublicGeneralPairList($params = array()) {
        return $this->request('public/general/PairList', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
}
