<?php

namespace ccxt\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class digikalagold extends \ccxt\Exchange {
    public function public_get_non_inventory_v1_prices($params = array()) {
        return $this->request('non-inventory/v1/prices/', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetNonInventoryV1Prices($params = array()) {
        return $this->request('non-inventory/v1/prices/', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
}
