<?php

namespace ccxt\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class hamrahgold extends \ccxt\Exchange {
    public function public_get_api_v1_market_price_xau_changes($params = array()) {
        return $this->request('api/v1/market/price/xau/changes', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetApiV1MarketPriceXauChanges($params = array()) {
        return $this->request('api/v1/market/price/xau/changes', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
}
