<?php

namespace ccxt\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class ourbit extends \ccxt\Exchange {
    public function spot_get_api_platform_spot_market_v2_tickers($params = array()) {
        return $this->request('api/platform/spot/market/v2/tickers', 'spot', 'GET', $params, null, null, array());
    }
    public function spot_get_api_platform_spot_market_v2_symbol_ticker($params = array()) {
        return $this->request('api/platform/spot/market/v2/symbol/ticker', 'spot', 'GET', $params, null, null, array());
    }
    public function futures_get_api_v1_contract_ticker($params = array()) {
        return $this->request('api/v1/contract/ticker', 'futures', 'GET', $params, null, null, array());
    }
    public function spotGetApiPlatformSpotMarketV2Tickers($params = array()) {
        return $this->request('api/platform/spot/market/v2/tickers', 'spot', 'GET', $params, null, null, array());
    }
    public function spotGetApiPlatformSpotMarketV2SymbolTicker($params = array()) {
        return $this->request('api/platform/spot/market/v2/symbol/ticker', 'spot', 'GET', $params, null, null, array());
    }
    public function futuresGetApiV1ContractTicker($params = array()) {
        return $this->request('api/v1/contract/ticker', 'futures', 'GET', $params, null, null, array());
    }
}
