<?php

namespace ccxt\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class saraf extends \ccxt\Exchange {
    public function public_get_v1_prices_listed($params = array()) {
        return $this->request('v1/prices/listed', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetV1PricesListed($params = array()) {
        return $this->request('v1/prices/listed', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
}
