<?php

namespace ccxt\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class tehran_exchange extends \ccxt\Exchange {
    public function public_get_otc_v1_market_pair($params = array()) {
        return $this->request('otc/v1/market/pair', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_otc_v1_market_order_pair_price($params = array()) {
        return $this->request('otc/v1/market/order/pair/price', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetOtcV1MarketPair($params = array()) {
        return $this->request('otc/v1/market/pair', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetOtcV1MarketOrderPairPrice($params = array()) {
        return $this->request('otc/v1/market/order/pair/price', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
}
