<?php

namespace ccxt\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class zarniv extends \ccxt\Exchange {
    public function public_get_user_get_gold_price($params = array()) {
        return $this->request('user/get_gold_price', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_user_get_silver_price($params = array()) {
        return $this->request('user/get_silver_price', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetUserGetGoldPrice($params = array()) {
        return $this->request('user/get_gold_price', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetUserGetSilverPrice($params = array()) {
        return $this->request('user/get_silver_price', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
}
