<?php

namespace ccxt\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class zarpin extends \ccxt\Exchange {
    public function public_get_v1_prc_prices($params = array()) {
        return $this->request('v1/prc/prices', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetV1PrcPrices($params = array()) {
        return $this->request('v1/prc/prices', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
}
