<?php

namespace ccxt;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use ccxt\abstract\ariomex as Exchange;

class ariomex extends Exchange {

    public function describe(): mixed {
        return $this->deep_extend(parent::describe(), array(
            'id' => 'ariomex',
            'name' => 'Ariomex',
            'countries' => array( 'IR' ),
            'rateLimit' => 1000,
            'version' => 'v1',
            'certified' => false,
            'pro' => false,
            'has' => array(
                'CORS' => null,
                'spot' => true,
                'margin' => false,
                'swap' => false,
                'future' => false,
                'option' => false,
                'fetchMarkets' => true,
                'fetchTicker' => true,
                'fetchTickers' => true,
                'fetchTime' => true,
            ),
            'urls' => array(
                'api' => array(
                    'public' => 'https://api.ariomex.ir',
                ),
                'www' => 'https://ariomex.ir',
                'doc' => 'https://api.ariomex.ir/v1/public/markets_details',
            ),
            'api' => array(
                'public' => array(
                    'get' => array(
                        'v1/public/markets_details' => 1,
                    ),
                ),
            ),
        ));
    }

    public function fetch_markets($params = array ()): array {
        /**
         * retrieves data on all $markets for ariomex
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {array[]} an array of objects representing market data
         */
        $response = $this->publicGetV1PublicMarketsDetails ($params);
        $markets = $this->safe_list($response, 'result');
        $result = array();
        for ($i = 0; $i < count($markets); $i++) {
            $result[] = $this->parse_market($markets[$i]);
        }
        return $result;
    }

    public function parse_market($market): array {
        // {
        //     'symbol' => 'btcusdt',
        //     'base' => 'btc',
        //     'quote' => 'usdt',
        //     'spot_enabled' => 'true',
        //     'base_market_precision' => '5',
        //     'quote_market_precision' => '2',
        //     'base_coin_precision' => '8',
        //     'quote_coin_precision' => '8',
        // }
        $id = $this->safe_string($market, 'symbol');
        $baseId = $this->safe_string($market, 'base');
        $quoteId = $this->safe_string($market, 'quote');
        $base = $this->safe_currency_code($baseId);
        $quote = $this->safe_currency_code($quoteId);
        return array(
            'id' => $id,
            'symbol' => $base . '/' . $quote,
            'base' => $base,
            'quote' => $quote,
            'settle' => null,
            'baseId' => $baseId,
            'quoteId' => $quoteId,
            'settleId' => null,
            'type' => 'spot',
            'spot' => true,
            'margin' => false,
            'swap' => false,
            'future' => false,
            'option' => false,
            'active' => $this->safe_bool($market, 'spot_enabled'),
            'contract' => false,
            'linear' => null,
            'inverse' => null,
            'contractSize' => null,
            'expiry' => null,
            'expiryDatetime' => null,
            'strike' => null,
            'optionType' => null,
            'precision' => array(
                'amount' => $this->safe_number($market, 'base_market_precision'),
                'price' => $this->safe_number($market, 'quote_market_precision'),
            ),
            'limits' => array(
                'leverage' => array( 'min' => null, 'max' => null ),
                'amount' => array( 'min' => null, 'max' => null ),
                'price' => array( 'min' => null, 'max' => null ),
                'cost' => array( 'min' => null, 'max' => null ),
            ),
            'created' => $this->safe_integer($market, 'time_listed'),
            'info' => $market,
        );
    }

    public function fetch_time($params = array ()): float {
        $response = $this->publicGetV1PublicMarketsDetails ($params);
        return $this->safe_integer($response, 'serverTime');
    }

    public function fetch_ticker(string $symbol, $params = array ()): array {
        /**
         * fetches a price ticker for a market
         * @param {string} $symbol unified $symbol of the market to fetch the ticker for
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {array} a ~@link https://docs.ccxt.com/#/?id=ticker-structure ticker structure~
         */
        $tickers = $this->fetch_tickers(array( $symbol ), $params);
        return $tickers[$symbol];
    }

    public function fetch_tickers(?array $symbols = null, $params = array ()): array {
        /**
         * fetches price tickers for all $markets
         * @param {string[]|null} $symbols unified $symbols of the $markets to fetch the tickers for
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {array} a dictionary of ~@link https://docs.ccxt.com/#/?id=$ticker-structure $ticker structures~
         */
        $this->load_markets();
        if ($symbols !== null) {
            $symbols = $this->market_symbols($symbols);
        }
        $response = $this->publicGetV1PublicMarketsDetails ($params);
        $timestamp = $this->safe_integer($response, 'serverTime');
        $markets = $this->safe_list($response, 'result');
        $result = array();
        for ($i = 0; $i < count($markets); $i++) {
            $markets[$i]['timestamp'] = $timestamp;
            $ticker = $this->parse_ticker($markets[$i]);
            $result[$ticker['symbol']] = $ticker;
        }
        return $this->filter_by_array_tickers($result, 'symbol', $symbols);
    }

    public function parse_ticker($ticker, ?array $market = null): array {
        $marketId = $this->safe_string($ticker, 'symbol');
        $market = $this->safe_market($marketId, $market);
        return $this->safe_ticker(array(
            'symbol' => $market['symbol'],
            'timestamp' => $this->safe_integer($ticker, 'timestamp'),
            'datetime' => null,
            'high' => $this->safe_string($ticker, 'highest_price'),
            'low' => $this->safe_string($ticker, 'lowest_price'),
            'bid' => $this->safe_string($ticker, 'bid_price'),
            'bidVolume' => null,
            'ask' => $this->safe_string($ticker, 'ask_price'),
            'askVolume' => null,
            'vwap' => null,
            'open' => null,
            'close' => $this->safe_string($ticker, 'last_price'),
            'last' => $this->safe_string($ticker, 'last_price'),
            'previousClose' => null,
            'change' => $this->safe_string($ticker, 'change_price'),
            'percentage' => $this->safe_string($ticker, 'change_percentage'),
            'average' => null,
            'baseVolume' => $this->safe_string($ticker, 'volume'),
            'quoteVolume' => null,
            'info' => $ticker,
        ), $market);
    }

    public function sign($path, $api = 'public', $method = 'GET', $params = array (), $headers = null, $body = null) {
        $url = $this->urls['api'][$api] . '/' . $this->implode_params($path, $params);
        $query = $this->omit($params, $this->extract_params($path));
        if ($query) {
            $url .= '?' . $this->urlencode($query);
        }
        $headers = array( 'Accept' => 'application/json' );
        return array( 'url' => $url, 'method' => $method, 'body' => $body, 'headers' => $headers );
    }
}
