<?php

namespace ccxt;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use ccxt\abstract\asacoine as Exchange;

class asacoine extends Exchange {

    public function describe(): mixed {
        return $this->deep_extend(parent::describe(), array(
            'id' => 'asacoine',
            'name' => 'Asacoine',
            'countries' => array( 'IR' ),
            'rateLimit' => 1000,
            'version' => 'v1',
            'certified' => false,
            'pro' => false,
            'has' => array(
                'CORS' => null,
                'spot' => true,
                'margin' => false,
                'swap' => false,
                'future' => false,
                'option' => false,
                'fetchMarkets' => true,
                'fetchTicker' => true,
                'fetchTickers' => true,
                'otc' => true,
            ),
            'urls' => array(
                'logo' => 'https://cdn.arz.digital/cr-odin/img/exchanges/asacoine/64x64.png',
                'api' => array(
                    'public' => 'https://api.asacoine.com/api',
                ),
                'www' => 'https://asacoine.com',
                'doc' => 'https://api.asacoine.com/api/v1/market/pairs/pricing',
            ),
            'api' => array(
                'public' => array(
                    'get' => array(
                        'v1/market/pairs/pricing' => 1,
                        'v1/market/pairs/cumulative' => 1,
                    ),
                ),
            ),
            'commonCurrencies' => array(
                'TMN' => 'IRT',
            ),
            'fees' => array(
                'trading' => array(
                    'tierBased' => false,
                    'percentage' => true,
                    'maker' => $this->parse_number('0'),
                    'taker' => $this->parse_number('0'),
                ),
            ),
        ));
    }

    public function parse_market($market): array {
        $baseId = $this->safe_string($market, 'baseId');
        $quoteId = $this->safe_string($market, 'quoteId');
        $base = $this->safe_currency_code($baseId);
        $quote = $this->safe_currency_code($quoteId);
        return array(
            'id' => $baseId . '/' . $quoteId,
            'symbol' => $base . '/' . $quote,
            'base' => $base,
            'quote' => $quote,
            'settle' => null,
            'baseId' => $baseId,
            'quoteId' => $quoteId,
            'settleId' => null,
            'type' => 'spot',
            'spot' => true,
            'margin' => false,
            'swap' => false,
            'future' => false,
            'option' => false,
            'active' => true,
            'contract' => false,
            'linear' => null,
            'inverse' => null,
            'contractSize' => null,
            'expiry' => null,
            'expiryDatetime' => null,
            'strike' => null,
            'optionType' => null,
            'precision' => array(
                'amount' => null,
                'price' => null,
            ),
            'limits' => array(
                'leverage' => array(
                    'min' => null,
                    'max' => null,
                ),
                'amount' => array(
                    'min' => null,
                    'max' => null,
                ),
                'price' => array(
                    'min' => null,
                    'max' => null,
                ),
                'cost' => array(
                    'min' => null,
                    'max' => null,
                ),
            ),
            'created' => null,
            'info' => $this->safe_value($market, 'info', $market),
        );
    }

    public function parse_otc_market($market): array {
        $baseId = $this->safe_string($market, 'baseId');
        $quoteId = $this->safe_string($market, 'quoteId');
        $base = $this->safe_currency_code($baseId);
        $quote = $this->safe_currency_code($quoteId);
        return array(
            'id' => $baseId . '/' . $quoteId,
            'symbol' => $base . '/' . $quote,
            'base' => $base,
            'quote' => $quote,
            'settle' => null,
            'baseId' => $baseId,
            'quoteId' => $quoteId,
            'settleId' => null,
            'type' => 'otc',
            'spot' => false,
            'margin' => false,
            'swap' => false,
            'future' => false,
            'option' => false,
            'active' => true,
            'contract' => false,
            'linear' => null,
            'inverse' => null,
            'contractSize' => null,
            'expiry' => null,
            'expiryDatetime' => null,
            'strike' => null,
            'optionType' => null,
            'precision' => array(
                'amount' => null,
                'price' => null,
            ),
            'limits' => array(
                'leverage' => array(
                    'min' => null,
                    'max' => null,
                ),
                'amount' => array(
                    'min' => null,
                    'max' => null,
                ),
                'price' => array(
                    'min' => null,
                    'max' => null,
                ),
                'cost' => array(
                    'min' => null,
                    'max' => null,
                ),
            ),
            'created' => null,
            'info' => $this->safe_value($market, 'info', $market),
        );
    }

    public function parse_markets($response): array {
        $data = $this->safe_dict($response, 'data', array());
        $baseIds = is_array($data) ? array_keys($data) : array();
        $result = array();
        for ($i = 0; $i < count($baseIds); $i++) {
            $baseId = $baseIds[$i];
            $quotes = $this->safe_dict($data, $baseId, array());
            $quoteIds = is_array($quotes) ? array_keys($quotes) : array();
            for ($j = 0; $j < count($quoteIds); $j++) {
                $quoteId = $quoteIds[$j];
                $ticker = $this->safe_dict($quotes, $quoteId, array());
                $result[] = $this->parse_market(array( 'baseId' => $baseId, 'quoteId' => $quoteId, 'info' => $ticker ));
            }
        }
        return $result;
    }

    public function parse_cumulative_markets($response): array {
        $data = $this->safe_dict($response, 'data', array());
        $keys = $this->safe_list($data, 'keys', array());
        $values = $this->safe_list($data, 'values', array());
        $result = array();
        for ($i = 0; $i < count($values); $i++) {
            $row = $values[$i];
            $market = array();
            for ($j = 0; $j < count($keys); $j++) {
                $market[$keys[$j]] = $row[$j];
            }
            $marketTypes = $this->safe_list($market, 'marketTypes', array());
            if (!$this->in_array('otc', $marketTypes)) {
                continue;
            }
            $name = $this->safe_string($market, 'name');
            list($baseId, $quoteId) = explode('-', $name);
            $market['baseId'] = $baseId;
            $market['quoteId'] = $quoteId;
            $result[] = $this->parse_otc_market($market);
        }
        return $result;
    }

    public function fetch_markets($params = array ()) {
        /**
         * retrieves data on all markets for asacoine
         * @see https://api.asacoine.com/api/v1/market/pairs/pricing
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {array[]} an array of objects representing market data
         */
        $type = $this->safe_string($params, 'type', 'spot');
        $request = $this->omit($params, array( 'type' ));
        if ($type === 'otc') {
            $cumulativeResponse = $this->publicGetV1MarketPairsCumulative ($request);
            return $this->parse_cumulative_markets($cumulativeResponse);
        }
        $response = $this->publicGetV1MarketPairsPricing ($request);
        return $this->parse_markets($response);
    }

    public function parse_ticker($ticker, ?array $market = null): array {
        $bid = $this->safe_list($ticker, 'bid', array());
        $ask = $this->safe_list($ticker, 'ask', array());
        $nestedOrderBook = $this->safe_dict($ticker, 'orderBook');
        $cumulativeOrderBook = $nestedOrderBook;
        if (($nestedOrderBook === null) && ($this->safe_string($ticker, 'bestBid') !== null)) {
            $cumulativeOrderBook = $ticker;
        }
        $orderBook = $cumulativeOrderBook;
        if ($orderBook === null) {
            $orderBook = array();
        }
        $bidPriceString = $this->safe_string($orderBook, 'bestBid');
        $askPriceString = $this->safe_string($orderBook, 'bestAsk');
        $bidVolume = $this->safe_number($orderBook, 'bidSize');
        $askVolume = $this->safe_number($orderBook, 'askSize');
        if ($cumulativeOrderBook === null) {
            $bidPriceString = $this->safe_string($bid, 0);
            $askPriceString = $this->safe_string($ask, 0);
            $bidVolume = $this->safe_number($bid, 1);
            $askVolume = $this->safe_number($ask, 1);
        }
        $bidPrice = $this->parse_number($bidPriceString);
        $askPrice = $this->parse_number($askPriceString);
        $last = null;
        if (($bidPriceString !== null) && ($askPriceString !== null)) {
            $last = $this->parse_number(Precise::string_div(Precise::string_add($bidPriceString, $askPriceString), '2'));
        }
        return $this->safe_ticker(array(
            'symbol' => $this->safe_string($market, 'symbol'),
            'timestamp' => null,
            'datetime' => null,
            'high' => null,
            'low' => null,
            'bid' => $bidPrice,
            'bidVolume' => $bidVolume,
            'ask' => $askPrice,
            'askVolume' => $askVolume,
            'vwap' => null,
            'open' => null,
            'close' => $last,
            'last' => $last,
            'previousClose' => null,
            'change' => null,
            'percentage' => null,
            'average' => $last,
            'baseVolume' => null,
            'quoteVolume' => null,
            'info' => $ticker,
        ), $market);
    }

    public function fetch_tickers(?array $symbols = null, $params = array ()): array {
        /**
         * fetches price tickers for multiple markets
         * @see https://api.asacoine.com/api/v1/market/pairs/pricing
         * @param {string[]|null} $symbols unified $symbols of the markets to fetch the tickers for, all $market tickers are returned if not assigned
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {array} a dictionary of ~@link https://docs.ccxt.com/#/?id=$ticker-structure $ticker structures~
         */
        $type = $this->safe_string($params, 'type', 'spot');
        $request = $this->omit($params, array( 'type' ));
        $this->load_markets(false, array( 'type' => $type ));
        if ($symbols !== null) {
            $symbols = $this->market_symbols($symbols);
        }
        $response = array();
        if ($type === 'otc') {
            $response = $this->publicGetV1MarketPairsCumulative ($request);
        } else {
            $response = $this->publicGetV1MarketPairsPricing ($request);
        }
        if ($type === 'otc') {
            $cumulativeData = $this->safe_dict($response, 'data', array());
            $keys = $this->safe_list($cumulativeData, 'keys', array());
            $values = $this->safe_list($cumulativeData, 'values', array());
            $cumulativeTickers = array();
            for ($i = 0; $i < count($values); $i++) {
                $row = $values[$i];
                $raw = array();
                for ($j = 0; $j < count($keys); $j++) {
                    $raw[$keys[$j]] = $row[$j];
                }
                $name = $this->safe_string($raw, 'name');
                list($baseId, $quoteId) = explode('-', $name);
                $base = $this->safe_currency_code($baseId);
                $quote = $this->safe_currency_code($quoteId);
                $market = $this->safe_market($base . '/' . $quote);
                $parsed = $this->parse_ticker($this->safe_dict($raw, 'orderBook', array()), $market);
                $cumulativeTickers[$parsed['symbol']] = $parsed;
            }
            return $this->filter_by_array_tickers($cumulativeTickers, 'symbol', $symbols);
        }
        $data = $this->safe_dict($response, 'data', array());
        $baseIds = is_array($data) ? array_keys($data) : array();
        $result = array();
        for ($i = 0; $i < count($baseIds); $i++) {
            $baseId = $baseIds[$i];
            $quotes = $this->safe_dict($data, $baseId, array());
            $quoteIds = is_array($quotes) ? array_keys($quotes) : array();
            for ($j = 0; $j < count($quoteIds); $j++) {
                $quoteId = $quoteIds[$j];
                $ticker = $this->safe_dict($quotes, $quoteId, array());
                $market = $this->safe_market($baseId . '/' . $quoteId);
                $parsed = $this->parse_ticker($ticker, $market);
                $result[$parsed['symbol']] = $parsed;
            }
        }
        return $this->filter_by_array_tickers($result, 'symbol', $symbols);
    }

    public function fetch_ticker(string $symbol, $params = array ()) {
        /**
         * fetches a price ticker, a statistical calculation for a specific market
         * @see https://api.asacoine.com/api/v1/market/pairs/pricing
         * @param {string} $symbol unified $symbol of the market to fetch the ticker for
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {array} a ~@link https://docs.ccxt.com/#/?id=ticker-structure ticker structure~
         */
        $tickers = $this->fetch_tickers(array( $symbol ), $params);
        return $tickers[$symbol];
    }

    public function sign($path, $api = 'public', $method = 'GET', $params = array (), $headers = null, $body = null) {
        $query = $this->omit($params, $this->extract_params($path));
        $url = $this->urls['api'][$api] . '/' . $this->implode_params($path, $params);
        if ($query) {
            $url .= '?' . $this->urlencode($query);
        }
        $headers = array(
            'Content-Type' => 'application/json',
        );
        return array( 'url' => $url, 'method' => $method, 'body' => $body, 'headers' => $headers );
    }
}
