<?php

namespace ccxt;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use ccxt\abstract\bitwana as Exchange;

class bitwana extends Exchange {

    public function market_type_to_symbol(string $base, string $quote, $marketType = 'spot'): string {
        return $base . '/' . $quote;
    }

    public function describe(): mixed {
        return $this->deep_extend(parent::describe(), array(
            'id' => 'bitwana',
            'name' => 'Bitwana',
            'countries' => array( 'IR' ),
            'rateLimit' => 1000,
            'version' => '1',
            'certified' => false,
            'pro' => false,
            'has' => array(
                'CORS' => null,
                'spot' => true,
                'margin' => false,
                'swap' => false,
                'future' => false,
                'option' => false,
                'addMargin' => false,
                'cancelAllOrders' => false,
                'cancelOrder' => false,
                'cancelOrders' => false,
                'createDepositAddress' => false,
                'createOrder' => false,
                'createStopLimitOrder' => false,
                'createStopMarketOrder' => false,
                'createStopOrder' => false,
                'editOrder' => false,
                'fetchBalance' => false,
                'fetchBorrowInterest' => false,
                'fetchBorrowRateHistories' => false,
                'fetchBorrowRateHistory' => false,
                'fetchClosedOrders' => false,
                'fetchCrossBorrowRate' => false,
                'fetchCrossBorrowRates' => false,
                'fetchCurrencies' => false,
                'fetchDepositAddress' => false,
                'fetchDeposits' => false,
                'fetchFundingHistory' => false,
                'fetchFundingRate' => false,
                'fetchFundingRateHistory' => false,
                'fetchFundingRates' => false,
                'fetchIndexOHLCV' => false,
                'fetchIsolatedBorrowRate' => false,
                'fetchIsolatedBorrowRates' => false,
                'fetchL2OrderBook' => false,
                'fetchL3OrderBook' => false,
                'fetchLedger' => false,
                'fetchLedgerEntry' => false,
                'fetchLeverageTiers' => false,
                'fetchMarkets' => true,
                'fetchMarkOHLCV' => false,
                'fetchMyTrades' => false,
                'fetchOHLCV' => false,
                'fetchOpenInterestHistory' => false,
                'fetchOpenOrders' => false,
                'fetchOrder' => false,
                'fetchOrderBook' => false,
                'fetchOrders' => false,
                'fetchOrderTrades' => 'emulated',
                'fetchPositions' => false,
                'fetchPremiumIndexOHLCV' => false,
                'fetchTicker' => true,
                'fetchTickers' => true,
                'fetchTime' => false,
                'fetchTrades' => false,
                'fetchTradingFee' => false,
                'fetchTradingFees' => false,
                'fetchWithdrawals' => false,
                'otc' => true,
                'setLeverage' => false,
                'setMarginMode' => false,
                'transfer' => false,
                'withdraw' => false,
            ),
            'comment' => 'This comment is optional',
            'urls' => array(
                'logo' => 'https://bitwana.com/favicon.ico',
                'api' => array(
                    'public' => 'https://bitwana.com',
                ),
                'www' => 'https://bitwana.com/',
                'doc' => array(
                    'https://bitwana.com/',
                ),
            ),
            'api' => array(
                'public' => array(
                    'get' => array(
                        'api/1/markets' => 1,
                        'api/1/markets/{id}' => 1,
                    ),
                ),
            ),
            'fees' => array(
            ),
        ));
    }

    public function parse_spot_market($market): array {
        // {
        //     "id" => "BTC_IRT",
        //     "symbol" => "بیت‌کوین-تومان",
        //     "base" => "BTC",
        //     "quote" => "IRT",
        //     "buyPrice" => "10222846365",
        //     "sellPrice" => "10233403625",
        //     "userOrderPricePrecision" => 0,
        //     "quantityPrecision" => 6,
        //     "minimumOrder" => 100000,
        //     "maximumOrder" => 300000000,
        //     "lastTradedPrice" => "10249911984",
        //     "lowestPrice" => "10063564406",
        //     "highestPrice" => "10320391247",
        //     "sourceVolume" => "0.036557",
        //     "destinationVolume" => "371770611.78",
        //     "tradingEnabled" => true,
        //     "otcEnabled" => false,
        // }
        $id = $this->safe_string($market, 'id');
        $baseId = $this->safe_string($market, 'base');
        $quoteId = $this->safe_string($market, 'quote');
        $base = $this->safe_currency_code($baseId);
        $quote = $this->safe_currency_code($quoteId);
        return array(
            'id' => $id,
            'symbol' => $this->market_type_to_symbol($base, $quote, 'spot'),
            'base' => $base,
            'quote' => $quote,
            'settle' => null,
            'baseId' => $baseId,
            'quoteId' => $quoteId,
            'settleId' => null,
            'type' => 'spot',
            'spot' => true,
            'margin' => false,
            'swap' => false,
            'future' => false,
            'option' => false,
            'active' => true,
            'contract' => false,
            'linear' => null,
            'inverse' => null,
            'contractSize' => null,
            'expiry' => null,
            'expiryDatetime' => null,
            'strike' => null,
            'optionType' => null,
            'precision' => array(
                'amount' => $this->safe_integer($market, 'quantityPrecision'),
                'price' => $this->safe_integer($market, 'userOrderPricePrecision'),
            ),
            'limits' => array(
                'leverage' => array(
                    'min' => null,
                    'max' => null,
                ),
                'amount' => array(
                    'min' => null,
                    'max' => null,
                ),
                'price' => array(
                    'min' => null,
                    'max' => null,
                ),
                'cost' => array(
                    'min' => $this->safe_number($market, 'minimumOrder'),
                    'max' => $this->safe_number($market, 'maximumOrder'),
                ),
            ),
            'created' => null,
            'info' => $market,
        );
    }

    public function parse_otc_market($market): array {
        $rawId = $this->safe_string($market, 'id');
        $baseId = $this->safe_string($market, 'base');
        $quoteId = $this->safe_string($market, 'quote');
        $base = $this->safe_currency_code($baseId);
        $quote = $this->safe_currency_code($quoteId);
        return array(
            'id' => $rawId . '_OTC',
            'symbol' => $this->market_type_to_symbol($base, $quote, 'otc'),
            'base' => $base,
            'quote' => $quote,
            'settle' => null,
            'baseId' => $baseId,
            'quoteId' => $quoteId,
            'settleId' => null,
            'type' => 'otc',
            'spot' => false,
            'margin' => false,
            'swap' => false,
            'future' => false,
            'option' => false,
            'active' => true,
            'contract' => false,
            'linear' => null,
            'inverse' => null,
            'contractSize' => null,
            'expiry' => null,
            'expiryDatetime' => null,
            'strike' => null,
            'optionType' => null,
            'precision' => array(
                'amount' => $this->safe_integer($market, 'quantityPrecision'),
                'price' => $this->safe_integer($market, 'userOrderPricePrecision'),
            ),
            'limits' => array(
                'leverage' => array(
                    'min' => null,
                    'max' => null,
                ),
                'amount' => array(
                    'min' => null,
                    'max' => null,
                ),
                'price' => array(
                    'min' => null,
                    'max' => null,
                ),
                'cost' => array(
                    'min' => $this->safe_number($market, 'minimumOrder'),
                    'max' => $this->safe_number($market, 'maximumOrder'),
                ),
            ),
            'created' => null,
            'info' => $market,
        );
    }

    public function fetch_markets($params = array ()): array {
        /**
         * retrieves data on all $markets for bitwana
         * @see https://bitwana.com/api/1/markets?with_price=true
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {array[]} an array of objects representing $market data
         */
        $marketType = $this->safe_string($params, 'type', 'spot');
        $request = array(
            'with_price' => true,
        );
        $response = $this->publicGetApi1Markets ($this->extend($request, $params));
        $markets = $this->safe_list($response, 'content', array());
        $result = array();
        for ($i = 0; $i < count($markets); $i++) {
            $market = $markets[$i];
            if ($marketType === 'otc') {
                $result[] = $this->parse_otc_market($market);
            } else {
                $result[] = $this->parse_spot_market($market);
            }
        }
        return $result;
    }

    public function fetch_tickers(?array $symbols = null, $params = array ()): array {
        /**
         * fetches price tickers for multiple $markets, statistical information calculated over the past 24 hours for each $market
         * @see https://bitwana.com/api/1/markets?with_price=true
         * @param {string[]|null} $symbols unified $symbols of the $markets to fetch the ticker for, all $market tickers are returned if not assigned
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {array} a dictionary of ~@link https://docs.ccxt.com/#/?id=ticker-structure ticker structures~
         */
        $marketType = $this->safe_string($params, 'type', 'spot');
        $this->load_markets(false, array( 'type' => $marketType ));
        if ($symbols !== null) {
            $symbols = $this->market_symbols($symbols);
        }
        $request = array(
            'with_price' => true,
        );
        $response = $this->publicGetApi1Markets ($this->extend($request, $params));
        $markets = $this->safe_list($response, 'content', array());
        $result = array();
        for ($i = 0; $i < count($markets); $i++) {
            $market = $markets[$i];
            if ($marketType === 'otc') {
                $otcTicker = $this->parse_otc_ticker($market);
                $result[$otcTicker['symbol']] = $otcTicker;
            } else {
                $spotTicker = $this->parse_spot_ticker($market);
                $result[$spotTicker['symbol']] = $spotTicker;
            }
        }
        return $this->filter_by_array_tickers($result, 'symbol', $symbols);
    }

    public function fetch_ticker(string $symbol, $params = array ()): array {
        /**
         * fetches a price $ticker, a statistical calculation with the information calculated over the past 24 hours for a specific $market
         * @see https://bitwana.com/api/1/markets/BTC_IRT?with_price=true
         * @param {string} $symbol unified $symbol of the $market to fetch the $ticker for
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {array} a ~@link https://docs.ccxt.com/#/?id=$ticker-structure $ticker structure~
         */
        $marketType = $this->safe_string($params, 'type', 'spot');
        $this->load_markets(false, array( 'type' => $marketType ));
        $market = $this->market($symbol);
        $request = array(
            'id' => $this->safe_string($market['info'], 'id'),
            'with_price' => true,
        );
        $response = $this->publicGetApi1MarketsId ($this->extend($request, $params));
        $ticker = $this->safe_dict($response, 'content');
        if ($marketType === 'otc') {
            return $this->parse_otc_ticker($ticker, $market);
        }
        return $this->parse_spot_ticker($ticker, $market);
    }

    public function parse_spot_ticker($ticker, ?array $market = null): array {
        $baseId = $this->safe_string($ticker, 'base');
        $quoteId = $this->safe_string($ticker, 'quote');
        $base = $this->safe_currency_code($baseId);
        $quote = $this->safe_currency_code($quoteId);
        $symbol = $this->market_type_to_symbol($base, $quote, 'spot');
        if ($market !== null) {
            $symbol = $market['symbol'];
        }
        $high = $this->safe_number($ticker, 'highestPrice');
        $low = $this->safe_number($ticker, 'lowestPrice');
        $bid = $this->safe_number($ticker, 'buyPrice');
        $ask = $this->safe_number($ticker, 'sellPrice');
        $last = $this->safe_number($ticker, 'lastTradedPrice');
        $change = $this->safe_number($ticker, 'changePrice');
        $percentage = $this->safe_number($ticker, 'changeRate');
        $baseVolume = $this->safe_number($ticker, 'sourceVolume');
        $quoteVolume = $this->safe_number($ticker, 'destinationVolume');
        return $this->safe_ticker(array(
            'symbol' => $symbol,
            'timestamp' => null,
            'datetime' => null,
            'high' => $high,
            'low' => $low,
            'bid' => $bid,
            'bidVolume' => null,
            'ask' => $ask,
            'askVolume' => null,
            'vwap' => null,
            'open' => null,
            'close' => $last,
            'last' => $last,
            'previousClose' => null,
            'change' => $change,
            'percentage' => $percentage,
            'average' => null,
            'baseVolume' => $baseVolume,
            'quoteVolume' => $quoteVolume,
            'info' => $ticker,
        ), $market);
    }

    public function parse_otc_ticker($ticker, ?array $market = null): array {
        $baseId = $this->safe_string($ticker, 'base');
        $quoteId = $this->safe_string($ticker, 'quote');
        $base = $this->safe_currency_code($baseId);
        $quote = $this->safe_currency_code($quoteId);
        $symbol = $this->market_type_to_symbol($base, $quote, 'otc');
        if ($market !== null) {
            $symbol = $market['symbol'];
        }
        $high = $this->safe_number($ticker, 'highestPrice');
        $low = $this->safe_number($ticker, 'lowestPrice');
        $bid = $this->safe_number($ticker, 'buyPrice');
        $ask = $this->safe_number($ticker, 'sellPrice');
        $last = $this->safe_number($ticker, 'lastTradedPrice');
        $change = $this->safe_number($ticker, 'changePrice');
        $percentage = $this->safe_number($ticker, 'changeRate');
        return $this->safe_ticker(array(
            'symbol' => $symbol,
            'timestamp' => null,
            'datetime' => null,
            'high' => $high,
            'low' => $low,
            'bid' => $bid,
            'bidVolume' => null,
            'ask' => $ask,
            'askVolume' => null,
            'vwap' => null,
            'open' => null,
            'close' => $last,
            'last' => $last,
            'previousClose' => null,
            'change' => $change,
            'percentage' => $percentage,
            'average' => null,
            'baseVolume' => null,
            'quoteVolume' => null,
            'info' => $ticker,
        ), $market);
    }

    public function sign($path, $api = 'public', $method = 'GET', $params = array (), $headers = null, $body = null) {
        $query = $this->omit($params, $this->extract_params($path));
        $url = $this->urls['api'][$api] . '/' . $this->implode_params($path, $params);
        if ($query) {
            $url .= '?' . $this->urlencode($query);
        }
        $headers = array( 'Content-Type' => 'application/json' );
        return array( 'url' => $url, 'method' => $method, 'body' => $body, 'headers' => $headers );
    }
}
