<?php

namespace ccxt;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use ccxt\abstract\digikalagold as Exchange;

class digikalagold extends Exchange {

    public function describe(): mixed {
        return $this->deep_extend(parent::describe(), array(
            'id' => 'digikalagold',
            'name' => 'Digikala Gold',
            'countries' => array( 'IR' ),
            'rateLimit' => 1000,
            'version' => 'v1',
            'certified' => false,
            'pro' => false,
            'has' => array(
                'CORS' => null,
                'spot' => false,
                'margin' => false,
                'swap' => false,
                'future' => false,
                'option' => false,
                'fetchMarkets' => true,
                'fetchTicker' => true,
                'fetchTickers' => true,
                'otc' => true,
            ),
            'options' => array(
                'defaultType' => 'otc',
            ),
            'urls' => array(
                'api' => array(
                    'public' => 'https://api.digikala.com',
                ),
                'www' => 'https://www.digikala.com',
                'doc' => 'https://api.digikala.com/non-inventory/v1/prices/',
            ),
            'api' => array(
                'public' => array(
                    'get' => array(
                        'non-inventory/v1/prices/' => 1,
                    ),
                ),
            ),
        ));
    }

    public function fetch_markets($params = array ()): array {
        $response = $this->fetch_price($params);
        return array(
            $this->parse_market_entry($response, 'gold18'),
            $this->parse_market_entry($response, 'silver999'),
        );
    }

    public function fetch_price($params = array ()) {
        $response = $this->publicGetNonInventoryV1Prices ($params);
        $gold = $this->safe_dict($response, 'gold18', array());
        if ($this->safe_number($gold, 'price') !== null) {
            return $response;
        }
        throw new ExchangeError($this->id . ' returned an invalid response');
    }

    public function parse_market_entry($response, string $id): array {
        $isGold = $id === 'gold18';
        $base = 'XAG';
        if ($isGold) {
            $base = 'XAU18';
        }
        $quote = 'IRT';
        $info = $this->safe_dict($response, $id, array());
        return array(
            'id' => $base . $quote,
            'symbol' => $base . '/' . $quote,
            'base' => $base,
            'quote' => $quote,
            'settle' => null,
            'baseId' => $id,
            'quoteId' => $quote,
            'settleId' => null,
            'type' => 'otc',
            'spot' => false,
            'margin' => false,
            'swap' => false,
            'future' => false,
            'option' => false,
            'active' => true,
            'contract' => false,
            'linear' => null,
            'inverse' => null,
            'contractSize' => null,
            'expiry' => null,
            'expiryDatetime' => null,
            'strike' => null,
            'optionType' => null,
            'precision' => array(
                'amount' => null,
                'price' => null,
            ),
            'limits' => array(
                'leverage' => array( 'min' => null, 'max' => null ),
                'amount' => array( 'min' => null, 'max' => null ),
                'price' => array( 'min' => null, 'max' => null ),
                'cost' => array( 'min' => null, 'max' => null ),
            ),
            'created' => null,
            'info' => $info,
        );
    }

    public function fetch_ticker(string $symbol, $params = array ()): array {
        $this->load_markets();
        $market = $this->market($symbol);
        $response = $this->fetch_price($params);
        return $this->parse_ticker($response, $market);
    }

    public function fetch_tickers(?array $symbols = null, $params = array ()): array {
        $this->load_markets();
        if ($symbols !== null) {
            $symbols = $this->market_symbols($symbols);
        }
        $response = $this->fetch_price($params);
        $result = array();
        $marketSymbols = array( 'XAU18/IRT', 'XAG/IRT' );
        for ($i = 0; $i < count($marketSymbols); $i++) {
            $symbol = $marketSymbols[$i];
            $market = $this->market($symbol);
            $ticker = $this->parse_ticker($response, $market);
            $result[$ticker['symbol']] = $ticker;
        }
        return $this->filter_by_array_tickers($result, 'symbol', $symbols);
    }

    public function parse_ticker($response, ?array $market = null): array {
        $data = $this->safe_dict($response, $market['baseId'], array());
        $price = $this->safe_number($data, 'price');
        if ($price !== null) {
            $price = $price * 100;
        }
        return $this->safe_ticker(array(
            'symbol' => $market['symbol'],
            'timestamp' => null,
            'datetime' => null,
            'high' => null,
            'low' => null,
            'bid' => $price,
            'bidVolume' => null,
            'ask' => $price,
            'askVolume' => null,
            'vwap' => null,
            'open' => null,
            'close' => $price,
            'last' => $price,
            'previousClose' => null,
            'change' => null,
            'percentage' => null,
            'average' => null,
            'baseVolume' => null,
            'quoteVolume' => null,
            'info' => $data,
        ), $market);
    }

    public function sign($path, $api = 'public', $method = 'GET', $params = array (), $headers = null, $body = null) {
        $url = $this->urls['api'][$api] . '/' . $this->implode_params($path, $params);
        $query = $this->omit($params, $this->extract_params($path));
        if ($query) {
            $url .= '?' . $this->urlencode($query);
        }
        $headers = array( 'Accept' => 'application/json' );
        return array( 'url' => $url, 'method' => $method, 'body' => $body, 'headers' => $headers );
    }
}
