<?php

namespace ccxt;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use ccxt\abstract\hamrahgold as Exchange;

class hamrahgold extends Exchange {

    public function describe(): mixed {
        return $this->deep_extend(parent::describe(), array(
            'id' => 'hamrahgold',
            'name' => 'HamrahGold',
            'countries' => array( 'IR' ),
            'rateLimit' => 1000,
            'version' => 'v1',
            'certified' => false,
            'pro' => false,
            'has' => array(
                'CORS' => null,
                'spot' => false,
                'margin' => false,
                'swap' => false,
                'future' => false,
                'option' => false,
                'fetchMarkets' => true,
                'fetchTicker' => true,
                'fetchTickers' => true,
                'otc' => true,
            ),
            'options' => array(
                'defaultType' => 'otc',
            ),
            'urls' => array(
                'api' => array(
                    'public' => 'https://pwa.hamrahgold.com',
                ),
                'www' => 'https://hamrahgold.com',
                'doc' => 'https://pwa.hamrahgold.com/api/v1/market/price/xau/changes?type=sell',
            ),
            'api' => array(
                'public' => array(
                    'get' => array(
                        'api/v1/market/price/xau/changes' => 1,
                    ),
                ),
            ),
        ));
    }

    public function fetch_price(string $type, $params = array ()) {
        return $this->publicGetApiV1MarketPriceXauChanges ($this->extend(array( 'type' => $type ), $params));
    }

    public function fetch_markets($params = array ()): array {
        $response = $this->fetch_price('sell', $params);
        return array( $this->parse_market($response) );
    }

    public function parse_market($response): array {
        return array(
            'id' => 'XAU18IRT',
            'symbol' => 'XAU18/IRT',
            'base' => 'XAU18',
            'quote' => 'IRT',
            'settle' => null,
            'baseId' => 'XAU18',
            'quoteId' => 'IRT',
            'settleId' => null,
            'type' => 'otc',
            'spot' => false,
            'margin' => false,
            'swap' => false,
            'future' => false,
            'option' => false,
            'active' => $this->safe_bool($response, 'success', false),
            'contract' => false,
            'linear' => null,
            'inverse' => null,
            'contractSize' => null,
            'expiry' => null,
            'expiryDatetime' => null,
            'strike' => null,
            'optionType' => null,
            'precision' => array(
                'amount' => null,
                'price' => null,
            ),
            'limits' => array(
                'leverage' => array( 'min' => null, 'max' => null ),
                'amount' => array( 'min' => null, 'max' => null ),
                'price' => array( 'min' => null, 'max' => null ),
                'cost' => array( 'min' => null, 'max' => null ),
            ),
            'created' => null,
            'info' => $response,
        );
    }

    public function fetch_ticker(string $symbol, $params = array ()): array {
        $this->load_markets();
        $market = $this->market($symbol);
        $buyResponse = $this->fetch_price('buy', $params);
        $sellResponse = $this->fetch_price('sell', $params);
        return $this->parse_ticker($buyResponse, $market, $sellResponse);
    }

    public function fetch_tickers(?array $symbols = null, $params = array ()): array {
        $this->load_markets();
        if ($symbols !== null) {
            $symbols = $this->market_symbols($symbols);
        }
        $buyResponse = $this->fetch_price('buy', $params);
        $sellResponse = $this->fetch_price('sell', $params);
        $market = $this->market('XAU18/IRT');
        $ticker = $this->parse_ticker($buyResponse, $market, $sellResponse);
        $result = array();
        $result[$ticker['symbol']] = $ticker;
        return $this->filter_by_array_tickers($result, 'symbol', $symbols);
    }

    public function parse_ticker($buyResponse, ?array $market = null, $sellResponse = null): array {
        $buy = $this->safe_dict($buyResponse, 'data', array());
        $sell = $this->safe_dict($sellResponse, 'data', array());
        $changes = $this->safe_dict($sell, 'changes', array());
        $dailyChange = $this->safe_dict($changes, '1d', array());
        $bid = $this->safe_number($buy, 'current');
        $ask = $this->safe_number($sell, 'current');
        $previousClose = $this->safe_number($dailyChange, 'price');
        if ($bid !== null) {
            $bid = $bid / 10;
        }
        if ($ask !== null) {
            $ask = $ask / 10;
        }
        if ($previousClose !== null) {
            $previousClose = $previousClose / 10;
        }
        return $this->safe_ticker(array(
            'symbol' => $market['symbol'],
            'timestamp' => null,
            'datetime' => null,
            'high' => null,
            'low' => null,
            'bid' => $bid,
            'bidVolume' => null,
            'ask' => $ask,
            'askVolume' => null,
            'vwap' => null,
            'open' => null,
            'close' => $ask,
            'last' => $ask,
            'previousClose' => $previousClose,
            'change' => null,
            'percentage' => $this->safe_number($dailyChange, 'percent'),
            'average' => null,
            'baseVolume' => null,
            'quoteVolume' => null,
            'info' => array( 'buy' => $buyResponse, 'sell' => $sellResponse ),
        ), $market);
    }

    public function sign($path, $api = 'public', $method = 'GET', $params = array (), $headers = null, $body = null) {
        $url = $this->urls['api'][$api] . '/' . $this->implode_params($path, $params);
        $query = $this->omit($params, $this->extract_params($path));
        if ($query) {
            $url .= '?' . $this->urlencode($query);
        }
        $headers = array( 'Accept' => 'application/json' );
        return array( 'url' => $url, 'method' => $method, 'body' => $body, 'headers' => $headers );
    }
}
