<?php

namespace ccxt;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use ccxt\abstract\poulyar as Exchange;

class poulyar extends Exchange {

    public function describe(): mixed {
        return $this->deep_extend(parent::describe(), array(
            'id' => 'poulyar',
            'name' => 'Poulyar',
            'countries' => array( 'IR' ),
            'rateLimit' => 1000,
            'version' => 'v2',
            'certified' => false,
            'pro' => false,
            'has' => array(
                'CORS' => null,
                'spot' => false,
                'margin' => false,
                'swap' => false,
                'future' => false,
                'option' => false,
                'fetchMarkets' => true,
                'fetchTicker' => true,
                'fetchTickers' => true,
                'otc' => true,
            ),
            'options' => array(
                'defaultType' => 'otc',
            ),
            'urls' => array(
                'api' => array(
                    'public' => 'https://api.poulyar.com',
                ),
                'www' => 'https://poulyar.com',
                'doc' => 'https://api.poulyar.com/api/v2/market-data',
            ),
            'api' => array(
                'public' => array(
                    'get' => array(
                        'api/v2/market-data' => 1,
                    ),
                ),
            ),
        ));
    }

    public function fetch_markets($params = array ()): array {
        /**
         * retrieves data on all OTC $markets for poulyar
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {array[]} an array of objects representing market data
         */
        $response = $this->publicGetApiV2MarketData ($params);
        $result = $this->safe_dict($response, 'result', array());
        $markets = $this->safe_dict($result, 'symbols', array());
        $marketIds = is_array($markets) ? array_keys($markets) : array();
        $parsedMarkets = array();
        for ($i = 0; $i < count($marketIds); $i++) {
            $parsedMarkets[] = $this->parse_market($markets[$marketIds[$i]]);
        }
        return $parsedMarkets;
    }

    public function parse_market($market): array {
        $id = $this->safe_string($market, 'symbol');
        $baseId = $this->safe_string($market, 'baseAsset');
        $quoteId = $this->safe_string($market, 'quoteAsset');
        $base = $this->safe_currency_code($baseId);
        $quote = $this->safe_currency_code($quoteId);
        return array(
            'id' => $id,
            'symbol' => $base . '/' . $quote,
            'base' => $base,
            'quote' => $quote,
            'settle' => null,
            'baseId' => $baseId,
            'quoteId' => $quoteId,
            'settleId' => null,
            'type' => 'otc',
            'spot' => false,
            'margin' => false,
            'swap' => false,
            'future' => false,
            'option' => false,
            'active' => true,
            'contract' => false,
            'linear' => null,
            'inverse' => null,
            'contractSize' => null,
            'expiry' => null,
            'expiryDatetime' => null,
            'strike' => null,
            'optionType' => null,
            'precision' => array(
                'amount' => $this->safe_number($market, 'basePrecision'),
                'price' => $this->safe_number($market, 'quotePrecision'),
            ),
            'limits' => array(
                'leverage' => array( 'min' => null, 'max' => null ),
                'amount' => array( 'min' => $this->safe_number($market, 'minQty'), 'max' => null ),
                'price' => array( 'min' => null, 'max' => null ),
                'cost' => array( 'min' => $this->safe_number($market, 'minNotional'), 'max' => null ),
            ),
            'created' => null,
            'info' => $market,
        );
    }

    public function fetch_ticker(string $symbol, $params = array ()): array {
        /**
         * fetches a price ticker for an OTC market
         * @param {string} $symbol unified $symbol of the market to fetch the ticker for
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {array} a ~@link https://docs.ccxt.com/#/?id=ticker-structure ticker structure~
         */
        $tickers = $this->fetch_tickers(array( $symbol ), $params);
        return $tickers[$symbol];
    }

    public function fetch_tickers(?array $symbols = null, $params = array ()): array {
        /**
         * fetches price $tickers for all OTC $markets
         * @param {string[]|null} $symbols unified $symbols of the $markets to fetch the $tickers for
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {array} a dictionary of ~@link https://docs.ccxt.com/#/?id=$ticker-structure $ticker structures~
         */
        $this->load_markets();
        if ($symbols !== null) {
            $symbols = $this->market_symbols($symbols);
        }
        $response = $this->publicGetApiV2MarketData ($params);
        $result = $this->safe_dict($response, 'result', array());
        $markets = $this->safe_dict($result, 'symbols', array());
        $marketIds = is_array($markets) ? array_keys($markets) : array();
        $tickers = array();
        for ($i = 0; $i < count($marketIds); $i++) {
            $ticker = $this->parse_ticker($markets[$marketIds[$i]]);
            $tickers[$ticker['symbol']] = $ticker;
        }
        return $this->filter_by_array_tickers($tickers, 'symbol', $symbols);
    }

    public function parse_ticker($ticker, ?array $market = null): array {
        $marketId = $this->safe_string($ticker, 'symbol');
        $market = $this->safe_market($marketId, $market);
        $stats = $this->safe_dict($ticker, 'stats', array());
        return $this->safe_ticker(array(
            'symbol' => $market['symbol'],
            'timestamp' => $this->parse8601($this->safe_string($ticker, 'updatedAt')),
            'datetime' => null,
            'high' => null,
            'low' => null,
            'bid' => $this->safe_string($stats, 'bidPrice'),
            'bidVolume' => null,
            'ask' => $this->safe_string($stats, 'askPrice'),
            'askVolume' => null,
            'vwap' => null,
            'open' => null,
            'close' => $this->safe_string($stats, 'lastPrice'),
            'last' => $this->safe_string($stats, 'lastPrice'),
            'previousClose' => null,
            'change' => null,
            'percentage' => $this->safe_string($stats, '24h_ch'),
            'average' => null,
            'baseVolume' => null,
            'quoteVolume' => null,
            'info' => $ticker,
        ), $market);
    }

    public function sign($path, $api = 'public', $method = 'GET', $params = array (), $headers = null, $body = null) {
        $url = $this->urls['api'][$api] . '/' . $this->implode_params($path, $params);
        $query = $this->omit($params, $this->extract_params($path));
        if ($query) {
            $url .= '?' . $this->urlencode($query);
        }
        $headers = array( 'Accept' => 'application/json' );
        return array( 'url' => $url, 'method' => $method, 'body' => $body, 'headers' => $headers );
    }
}
