<?php

namespace ccxt;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use ccxt\abstract\talapp as Exchange;

class talapp extends Exchange {

    public function describe(): mixed {
        return $this->deep_extend(parent::describe(), array(
            'id' => 'talapp',
            'name' => 'Talapp',
            'countries' => array( 'IR' ),
            'rateLimit' => 1000,
            'version' => 'v1',
            'certified' => false,
            'pro' => false,
            'has' => array(
                'CORS' => null,
                'spot' => false,
                'margin' => false,
                'swap' => false,
                'future' => false,
                'option' => false,
                'fetchMarkets' => true,
                'fetchTicker' => true,
                'fetchTickers' => true,
                'otc' => true,
            ),
            'options' => array(
                'defaultType' => 'otc',
            ),
            'urls' => array(
                'api' => array(
                    'public' => 'https://talapp.ir',
                ),
                'www' => 'https://talapp.ir',
                'doc' => 'https://talapp.ir/wp-json/talapp/v1/gold-prices',
            ),
            'api' => array(
                'public' => array(
                    'get' => array(
                        'wp-json/talapp/v1/gold-prices' => 1,
                    ),
                ),
            ),
        ));
    }

    public function fetch_markets($params = array ()): array {
        $response = $this->publicGetWpJsonTalappV1GoldPrices ($params);
        return array( $this->parse_market($response) );
    }

    public function parse_market($response): array {
        $stale = $this->safe_bool($response, 'stale', false);
        return array(
            'id' => 'XAU18IRT',
            'symbol' => 'XAU18/IRT',
            'base' => 'XAU18',
            'quote' => 'IRT',
            'settle' => null,
            'baseId' => 'XAU18',
            'quoteId' => 'IRT',
            'settleId' => null,
            'type' => 'otc',
            'spot' => false,
            'margin' => false,
            'swap' => false,
            'future' => false,
            'option' => false,
            'active' => !$stale,
            'contract' => false,
            'linear' => null,
            'inverse' => null,
            'contractSize' => null,
            'expiry' => null,
            'expiryDatetime' => null,
            'strike' => null,
            'optionType' => null,
            'precision' => array(
                'amount' => null,
                'price' => null,
            ),
            'limits' => array(
                'leverage' => array( 'min' => null, 'max' => null ),
                'amount' => array( 'min' => null, 'max' => null ),
                'price' => array( 'min' => null, 'max' => null ),
                'cost' => array( 'min' => null, 'max' => null ),
            ),
            'created' => null,
            'info' => $response,
        );
    }

    public function fetch_ticker(string $symbol, $params = array ()): array {
        $this->load_markets();
        $market = $this->market($symbol);
        $response = $this->publicGetWpJsonTalappV1GoldPrices ($params);
        return $this->parse_ticker($response, $market);
    }

    public function fetch_tickers(?array $symbols = null, $params = array ()): array {
        $this->load_markets();
        if ($symbols !== null) {
            $symbols = $this->market_symbols($symbols);
        }
        $response = $this->publicGetWpJsonTalappV1GoldPrices ($params);
        $market = $this->market('XAU18/IRT');
        $ticker = $this->parse_ticker($response, $market);
        $result = array();
        $result[$ticker['symbol']] = $ticker;
        return $this->filter_by_array_tickers($result, 'symbol', $symbols);
    }

    public function parse_ticker($response, ?array $market = null): array {
        $fetchedAt = $this->safe_string($response, 'fetched_at');
        $timestamp = null;
        if ($fetchedAt !== null) {
            $timestamp = $this->parse8601(str_replace(' ', 'T', $fetchedAt) . '+03:30');
        }
        return $this->safe_ticker(array(
            'symbol' => $market['symbol'],
            'timestamp' => $timestamp,
            'datetime' => null,
            'high' => null,
            'low' => null,
            'bid' => $this->safe_number($response, 'buy_gold'),
            'bidVolume' => null,
            'ask' => $this->safe_number($response, 'sell_gold'),
            'askVolume' => null,
            'vwap' => null,
            'open' => null,
            'close' => $this->safe_number($response, 'sell_gold'),
            'last' => $this->safe_number($response, 'sell_gold'),
            'previousClose' => null,
            'change' => null,
            'percentage' => $this->safe_number($response, 'sell_diff'),
            'average' => null,
            'baseVolume' => null,
            'quoteVolume' => null,
            'info' => $response,
        ), $market);
    }

    public function sign($path, $api = 'public', $method = 'GET', $params = array (), $headers = null, $body = null) {
        $url = $this->urls['api'][$api] . '/' . $this->implode_params($path, $params);
        $query = $this->omit($params, $this->extract_params($path));
        if ($query) {
            $url .= '?' . $this->urlencode($query);
        }
        $headers = array( 'Accept' => 'application/json' );
        return array( 'url' => $url, 'method' => $method, 'body' => $body, 'headers' => $headers );
    }
}
